#!/usr/bin/env python3
"""
Seeds clinical assessment form schemas into assessment_forms table.
Idempotent — skips any subcategory key that already exists.
Run from backend/ directory:  python seed_assessment_forms.py
Run all batches:               python seed_assessment_forms.py --all
Run a specific batch:          python seed_assessment_forms.py --batch general
Available batches: general, cardiology, clinical, ent, gastro, obg, ortho, peds, specialty, systems
"""
import sys, os, argparse
sys.path.insert(0, os.path.dirname(__file__))

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if not DATABASE_URL:
    print("[seed] DATABASE_URL not set — skipping"); sys.exit(0)

if "postgresql+asyncpg" in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("postgresql+asyncpg", "postgresql")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+psycopg2://", 1)
elif DATABASE_URL.startswith("postgresql://") and "+psycopg2" not in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg2://", 1)

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.models.models import AssessmentForm
from datetime import datetime

engine = create_engine(DATABASE_URL, pool_pre_ping=True,
                       connect_args={"options": "-c prepared_statement_cache_size=0"})
DB = sessionmaker(bind=engine)

# ─── compact schema helpers ───────────────────────────────────────────────────

_n = [0]; _s = [0]

def fld(t, label, fid, **kw):
    _n[0] += 1
    b = {
        'id': f'f{_n[0]}', 'type': t, 'label': label, 'field_id': fid,
        'required': kw.pop('req', False), 'col_span': kw.pop('span', 1),
        'help_text': kw.pop('help', ''), 'placeholder': kw.pop('ph', ''),
        'default_value': '', 'read_only': False, 'hidden': False,
        'options': kw.pop('opts', []), 'conditions': [], 'alert_rules': [],
    }
    b.update(kw); return b

def O(*ls):
    return [{'label': l, 'value': l.lower().replace(' ','_').replace('/','_')
             .replace('-','_').replace('(','').replace(')','')
             .replace(',','').replace('.','').strip('_'), 'score_weight': 0} for l in ls]

def sec(title, *fields, na=False, cols=2):
    _s[0] += 1
    return {'id': f's{_s[0]}', 'title': title, 'layout': cols,
            'applicability_mode': 'na_allowed' if na else 'required',
            'fields': list(fields)}

def S(*secs): return {'sections': list(secs)}

# field shortcuts
def txt(l, f, **k): return fld('text', l, f, **k)
def num(l, f, **k): return fld('number', l, f, **k)
def ta(l, f, **k):  return fld('textarea', l, f, span=2, **k)
def dt(l, f, **k):  return fld('date', l, f, **k)
def dd(l, f, o, **k): return fld('dropdown', l, f, opts=o, **k)
def rb(l, f, o, **k): return fld('radio', l, f, opts=o, **k)
def cb(l, f, o, **k): return fld('checkbox', l, f, opts=o, span=2, **k)
def yn(l, f, **k):  return fld('yes_no', l, f, **k)
def sc(l, f, mn=0, mx=10, ml='None', xl='Severe', **k):
    return fld('scale', l, f, span=2, min=mn, max=mx, min_label=ml, max_label=xl, **k)
def nr(l, f, mn, mx, u='', **k):
    return fld('numeric_range', l, f, min=mn, max=mx, unit=u, **k)

# ─── BATCH: general ───────────────────────────────────────────────────────────

GENERAL = [
    {
        'title': 'Vital Signs',
        'desc': 'Complete vital signs including temperature, pulse, BP, SpO2, weight and pain score.',
        'cat': 'vitals', 'sub': 'vital-signs', 'icon': '🩺',
        'schema': S(
            sec('Anthropometrics',
                nr('Height', 'height', 50, 250, 'cm'),
                nr('Weight', 'weight', 1, 300, 'kg'),
                num('BMI', 'bmi'),
                dt('Measured At', 'measured_at'),
            ),
            sec('Temperature',
                nr('Temperature', 'temperature', 34.0, 42.0, '°C'),
                dd('Site', 'temp_site', O('Oral', 'Axillary', 'Rectal', 'Tympanic')),
            ),
            sec('Cardiovascular',
                nr('Systolic BP', 'bp_systolic', 60, 250, 'mmHg'),
                nr('Diastolic BP', 'bp_diastolic', 40, 150, 'mmHg'),
                nr('Pulse Rate', 'pulse_rate', 30, 250, 'bpm'),
                dd('Pulse Character', 'pulse_char', O('Regular', 'Irregular', 'Weak', 'Bounding')),
            ),
            sec('Respiratory & SpO2',
                nr('Respiratory Rate', 'resp_rate', 4, 60, '/min'),
                nr('SpO2', 'spo2', 50, 100, '%'),
                dd('O2 Delivery', 'o2_delivery',
                   O('Room Air', 'Nasal Prongs', 'Face Mask', 'Non-rebreather', 'HFNO', 'Ventilator')),
            ),
            sec('Neurological & Pain',
                nr('GCS Total', 'gcs_total', 3, 15),
                sc('Pain Score', 'pain_score', 0, 10, 'No pain', 'Worst pain'),
            ),
            sec('Notes', ta('Clinical Notes', 'clinical_notes')),
        ),
    },
    {
        'title': 'Pain Assessment',
        'desc': 'Detailed pain assessment using PQRST framework.',
        'cat': 'general', 'sub': 'pain-assessment', 'icon': '😣',
        'schema': S(
            sec('Pain Scores',
                sc('Current Pain', 'pain_score', 0, 10, 'No pain', 'Worst imaginable pain'),
                sc('Pain at Rest', 'pain_rest', 0, 10, 'None', 'Severe'),
                sc('Pain on Movement', 'pain_movement', 0, 10, 'None', 'Severe'),
            ),
            sec('Pain Characteristics',
                cb('Location', 'pain_location',
                   O('Head', 'Face', 'Neck', 'Chest', 'Upper Abdomen', 'Lower Abdomen',
                     'Back', 'Shoulder', 'Arm', 'Hand', 'Hip', 'Thigh', 'Leg', 'Foot')),
                rb('Onset', 'onset', O('Sudden', 'Gradual')),
                rb('Pattern', 'pattern', O('Constant', 'Intermittent', 'Colicky')),
                cb('Quality', 'quality',
                   O('Sharp', 'Dull', 'Burning', 'Throbbing', 'Stabbing', 'Cramping', 'Aching', 'Pressure')),
                rb('Radiation', 'radiation', O('None', 'Arm', 'Jaw', 'Back', 'Groin', 'Leg')),
                num('Duration (hours)', 'duration_hours'),
            ),
            sec('Aggravating & Relieving',
                cb('Aggravating Factors', 'aggravating',
                   O('Movement', 'Deep breathing', 'Eating', 'Palpation', 'Stress', 'Lying flat')),
                cb('Relieving Factors', 'relieving',
                   O('Rest', 'Analgesia', 'Heat', 'Cold', 'Position change', 'Eating')),
            ),
            sec('Functional Impact',
                rb('Sleep Impact', 'sleep_impact', O('None', 'Mild', 'Moderate', 'Severe')),
                rb('Mobility Impact', 'mobility_impact', O('None', 'Mild', 'Moderate', 'Severe')),
                rb('Daily Activity Impact', 'activity_impact', O('None', 'Mild', 'Moderate', 'Severe')),
            ),
            sec('Management', ta('Pain Management Plan', 'pain_plan')),
        ),
    },
    {
        'title': 'Asthma Assessment (Basic)',
        'desc': 'Basic asthma assessment — symptom control, triggers, and current management.',
        'cat': 'respiratory', 'sub': 'asthma-basic', 'icon': '🌬️',
        'schema': S(
            sec('Symptoms',
                yn('Wheeze', 'wheeze'), yn('Breathlessness', 'breathlessness'),
                yn('Nocturnal Cough', 'nocturnal_cough'), yn('Chest Tightness', 'chest_tightness'),
                num('Symptom days/week', 'symptom_days'),
                num('Nocturnal wakings/month', 'nocturnal_wakings'),
            ),
            sec('Triggers',
                cb('Identified Triggers', 'triggers',
                   O('Exercise', 'Dust', 'Pollen', 'Pet dander', 'Cold air', 'Smoke',
                     'Infections', 'NSAIDs', 'Stress', 'Mould', 'Cockroach', 'Foods')),
            ),
            sec('Current Control (GINA)',
                rb('Control Level', 'control_level',
                   O('Well controlled', 'Partly controlled', 'Uncontrolled')),
                num('SABA puffs/week (rescue)', 'saba_per_week'),
                dd('Current Step', 'gina_step',
                   O('Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5')),
            ),
            sec('Lung Function',
                nr('Peak Flow', 'peak_flow', 60, 900, 'L/min'),
                nr('FEV1', 'fev1', 20, 120, '% predicted'),
                nr('FEV1/FVC Ratio', 'fev1_fvc', 0.3, 1.0),
            ),
            sec('Management Plan',
                ta('Step-up/Step-down Plan', 'asthma_plan'),
                ta('Written Action Plan Given', 'action_plan'),
            ),
        ),
    },
    {
        'title': 'Medical History',
        'desc': 'Comprehensive past medical, surgical, and medication history.',
        'cat': 'history', 'sub': 'medical-history', 'icon': '📋',
        'schema': S(
            sec('Past Medical History',
                cb('Chronic Conditions', 'chronic_conditions',
                   O('Hypertension', 'Diabetes Mellitus', 'Coronary Artery Disease', 'Heart Failure',
                     'Atrial Fibrillation', 'Asthma/COPD', 'CKD', 'Stroke/TIA',
                     'Hypothyroidism', 'Epilepsy', 'Psychiatric disorder', 'Malignancy', 'HIV', 'TB')),
                ta('Other Medical Conditions', 'other_medical'),
            ),
            sec('Past Surgical History',
                cb('Previous Surgeries', 'prev_surgeries',
                   O('Appendicectomy', 'Cholecystectomy', 'CABG', 'PCI/Stenting', 'Joint Replacement',
                     'Hysterectomy', 'LSCS', 'Bowel surgery', 'Hernia repair', 'Thyroidectomy')),
                ta('Surgical Details (dates/complications)', 'surgical_details'),
            ),
            sec('Hospitalisations',
                yn('Previous hospitalisations', 'prev_hosp'),
                ta('Hospitalisation Details', 'hosp_details'),
            ),
            sec('Current Medications',
                ta('Current Medications', 'current_meds',
                   ph='List name, dose, frequency for each medication…'),
                yn('Compliant with medications', 'med_compliant'),
            ),
            sec('Immunisation History',
                rb('Immunisation Status', 'immunisation',
                   O('Up to date', 'Incomplete', 'Unknown')),
                ta('Immunisation Notes', 'immunisation_notes'),
            ),
        ),
    },
    {
        'title': 'Family History',
        'desc': 'Immediate and extended family medical history.',
        'cat': 'history', 'sub': 'family-history', 'icon': '👨‍👩‍👧',
        'schema': S(
            sec('First-Degree Relatives',
                cb('Father', 'father_conditions',
                   O('Hypertension', 'Diabetes', 'CAD/MI', 'Stroke', 'Cancer', 'CKD', 'Psychiatric', 'Deceased young')),
                cb('Mother', 'mother_conditions',
                   O('Hypertension', 'Diabetes', 'CAD/MI', 'Stroke', 'Cancer', 'CKD', 'Psychiatric', 'Deceased young')),
                cb('Siblings', 'sibling_conditions',
                   O('Hypertension', 'Diabetes', 'CAD/MI', 'Stroke', 'Cancer', 'Genetic disorder')),
            ),
            sec('Heritable Conditions',
                yn('Family history of premature CVD (<55 M / <65 F)', 'family_cad'),
                yn('Family history of sudden cardiac death', 'family_scd'),
                yn('Family history of malignancy', 'family_cancer'),
                txt('Cancer type if yes', 'family_cancer_type'),
                yn('Family history of genetic disorder', 'family_genetic'),
                txt('Genetic disorder if yes', 'family_genetic_type'),
            ),
            sec('Notes', ta('Family History Notes', 'family_notes')),
        ),
    },
    {
        'title': 'Social History',
        'desc': 'Lifestyle, substance use, occupation, and living situation.',
        'cat': 'history', 'sub': 'social-history', 'icon': '🏠',
        'schema': S(
            sec('Lifestyle',
                rb('Smoking Status', 'smoking',
                   O('Never', 'Ex-smoker', 'Current smoker')),
                num('Pack-years (if ever)', 'pack_years'),
                rb('Alcohol Use', 'alcohol',
                   O('Never', 'Occasional', 'Moderate', 'Heavy (>14 units/week)')),
                num('Units/week', 'alcohol_units'),
                rb('Physical Activity', 'activity',
                   O('Sedentary', 'Moderate (<150 min/week)', 'Active (≥150 min/week)')),
            ),
            sec('Substance Use',
                yn('Recreational drug use', 'drug_use'),
                cb('Substances (if yes)', 'substances',
                   O('Cannabis', 'Opioids', 'Cocaine', 'Amphetamines', 'Benzodiazepines', 'Other')),
                ta('Substance Use Notes', 'substance_notes'),
            ),
            sec('Occupation & Environment',
                txt('Occupation', 'occupation'),
                rb('Occupational Exposures', 'occ_exposure',
                   O('None', 'Dust/Asbestos', 'Chemicals', 'Noise', 'Radiation', 'Other')),
                rb('Living Situation', 'living',
                   O('Alone', 'With family', 'Shared accommodation', 'Care home', 'Homeless')),
                rb('Social Support', 'social_support', O('Good', 'Moderate', 'Poor', 'None')),
            ),
            sec('Diet & Nutrition',
                rb('Dietary Habit', 'diet', O('Vegetarian', 'Non-vegetarian', 'Vegan')),
                yn('Special dietary restrictions', 'diet_restrict'),
                ta('Diet Notes', 'diet_notes'),
            ),
        ),
    },
    {
        'title': 'Allergies',
        'desc': 'Drug, food and environmental allergy documentation.',
        'cat': 'general', 'sub': 'allergies', 'icon': '⚠️',
        'schema': S(
            sec('Allergy Status',
                yn('No Known Drug Allergies (NKDA)', 'nkda'),
                yn('No Known Allergies (NKA)', 'nka'),
            ),
            sec('Drug Allergies', na=True,
                cb('Drug Allergens', 'drug_allergens',
                   O('Penicillin', 'Amoxicillin', 'Aspirin', 'NSAIDs', 'Sulfonamides',
                     'Codeine', 'Morphine/Opioids', 'Metronidazole', 'Contrast Dye/Iodine',
                     'Metformin', 'Quinolones', 'Cephalosporins', 'Latex')),
                cb('Drug Allergy Reactions', 'drug_reactions',
                   O('Rash/Hives', 'Urticaria', 'Angioedema', 'Anaphylaxis',
                     'Bronchospasm', 'GI Upset', 'Stevens-Johnson', 'Fixed Drug Eruption')),
                rb('Drug Allergy Severity', 'drug_severity',
                   O('Mild', 'Moderate', 'Severe', 'Life-threatening')),
                ta('Drug Allergy Details', 'drug_allergy_notes', ph='Specify exact drug, dose, reaction…'),
            ),
            sec('Food Allergies', na=True,
                cb('Food Allergens', 'food_allergens',
                   O('Peanuts', 'Tree Nuts', 'Shellfish', 'Fish', 'Milk/Dairy',
                     'Eggs', 'Wheat/Gluten', 'Soy', 'Sesame')),
                cb('Food Allergy Reactions', 'food_reactions',
                   O('Rash', 'Angioedema', 'Anaphylaxis', 'GI Upset', 'Vomiting')),
                rb('Food Allergy Severity', 'food_severity', O('Mild', 'Moderate', 'Severe', 'Life-threatening')),
            ),
            sec('Environmental Allergies', na=True,
                cb('Environmental Allergens', 'env_allergens',
                   O('Dust Mites', 'Cockroach', 'Pollen/Grass', 'Mould/Fungal', 'Pet Dander (Dog)',
                     'Pet Dander (Cat)', 'Nickel/Metal', 'Cosmetics/Fragrance', 'Insect Sting')),
                ta('Environmental Allergy Notes', 'env_notes'),
            ),
            sec('Notes', ta('Allergy Summary Notes', 'allergy_notes')),
        ),
    },
    {
        'title': 'Systems Review',
        'desc': 'Comprehensive review of systems — cardiovascular, respiratory, GI, neuro, MSK, GU, endocrine, skin.',
        'cat': 'general', 'sub': 'systems-review', 'icon': '🔍',
        'schema': S(
            sec('General',
                cb('General Symptoms', 'general_sx',
                   O('Fever', 'Weight loss', 'Weight gain', 'Fatigue', 'Night sweats', 'Appetite loss')),
            ),
            sec('Cardiovascular',
                cb('CVS Symptoms', 'cvs_sx',
                   O('Chest pain', 'Palpitations', 'Breathlessness', 'Orthopnoea', 'PND',
                     'Ankle swelling', 'Syncope', 'Claudication')),
            ),
            sec('Respiratory',
                cb('Respiratory Symptoms', 'resp_sx',
                   O('Cough', 'Haemoptysis', 'Wheeze', 'Breathlessness', 'Pleuritic pain', 'Sputum')),
            ),
            sec('Gastrointestinal',
                cb('GI Symptoms', 'gi_sx',
                   O('Nausea', 'Vomiting', 'Dysphagia', 'Heartburn', 'Abdominal pain',
                     'Diarrhoea', 'Constipation', 'PR bleed', 'Malaena', 'Jaundice')),
            ),
            sec('Neurological',
                cb('Neurological Symptoms', 'neuro_sx',
                   O('Headache', 'Seizures', 'Weakness', 'Sensory loss', 'Visual changes',
                     'Dizziness', 'Memory problems', 'Speech problems', 'Tremor')),
            ),
            sec('Musculoskeletal',
                cb('MSK Symptoms', 'msk_sx',
                   O('Joint pain', 'Joint swelling', 'Back pain', 'Muscle weakness', 'Morning stiffness')),
            ),
            sec('Genitourinary & Endocrine',
                cb('GU Symptoms', 'gu_sx',
                   O('Dysuria', 'Frequency', 'Haematuria', 'Polyuria', 'Polydipsia',
                     'Incontinence', 'Menstrual irregularity', 'Discharge')),
                cb('Endocrine Symptoms', 'endo_sx',
                   O('Heat intolerance', 'Cold intolerance', 'Excessive sweating', 'Skin/hair changes')),
            ),
            sec('Skin & Psychiatric',
                cb('Skin Symptoms', 'skin_sx',
                   O('Rash', 'Pruritus', 'Jaundice', 'Pallor', 'Cyanosis', 'Ulcers')),
                cb('Psychiatric Symptoms', 'psych_sx',
                   O('Depression', 'Anxiety', 'Sleep disturbance', 'Mood swings', 'Suicidal ideation')),
            ),
        ),
    },
    {
        'title': 'Patient Profile',
        'desc': 'Demographics, contact information, insurance and emergency contacts.',
        'cat': 'general', 'sub': 'patient-profile', 'icon': '👤',
        'schema': S(
            sec('Demographics',
                txt('Full Name', 'full_name', req=True),
                dt('Date of Birth', 'dob', req=True),
                dd('Gender', 'gender', O('Male', 'Female', 'Other', 'Prefer not to say')),
                dd('Blood Group', 'blood_group', O('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Unknown')),
                txt('National ID / Aadhaar', 'national_id'),
                txt('BH-ID', 'bh_id'),
            ),
            sec('Contact Information',
                txt('Mobile Number', 'mobile', req=True),
                txt('Alternate Mobile', 'mobile_alt'),
                txt('Email', 'email'),
                ta('Address', 'address'),
                txt('Pincode', 'pincode'),
                txt('City', 'city'),
            ),
            sec('Emergency Contact',
                txt('Emergency Contact Name', 'emergency_name'),
                txt('Relationship', 'emergency_relation'),
                txt('Emergency Contact Mobile', 'emergency_mobile'),
            ),
            sec('Insurance / Scheme',
                rb('Insurance Type', 'insurance_type',
                   O('None', 'ESI', 'CGHS', 'ECHS', 'Private Insurance', 'Ayushman Bharat (PMJAY)', 'Other')),
                txt('Policy / Scheme Number', 'policy_number'),
                txt('Insurer Name', 'insurer_name'),
            ),
        ),
    },
    {
        'title': 'Chief Complaint',
        'desc': 'Patient chief complaint, duration and associated symptoms.',
        'cat': 'general', 'sub': 'chief-complaint', 'icon': '📝',
        'schema': S(
            sec('Chief Complaint',
                ta('Chief Complaint', 'chief_complaint', req=True, ph='Patient\'s presenting complaint in their own words…'),
                rb('Onset', 'complaint_onset', O('Sudden', 'Gradual', 'Insidious')),
                num('Duration (days)', 'complaint_duration_days'),
                rb('Duration Unit', 'complaint_duration_unit', O('Hours', 'Days', 'Weeks', 'Months', 'Years')),
                rb('Course', 'complaint_course', O('Improving', 'Worsening', 'Static', 'Episodic')),
            ),
            sec('Associated Symptoms',
                cb('Associated Symptoms', 'associated_symptoms',
                   O('Fever', 'Chills', 'Weight loss', 'Fatigue', 'Nausea', 'Vomiting',
                     'Diarrhoea', 'Constipation', 'Breathlessness', 'Chest pain',
                     'Headache', 'Dizziness', 'Sweating', 'Swelling')),
            ),
            sec('Prior Treatment',
                yn('Seen elsewhere for this complaint', 'seen_elsewhere'),
                ta('Prior Treatment & Response', 'prior_treatment'),
            ),
            sec('Notes', ta('Additional Clinical Notes', 'chief_notes')),
        ),
    },
]

# ─── BATCH: cardiology ────────────────────────────────────────────────────────

CARDIOLOGY = [
    {
        'title': 'ACS Assessment',
        'desc': 'Acute Coronary Syndrome — STEMI/NSTEMI/UA classification, GRACE risk, reperfusion.',
        'cat': 'cardiology', 'sub': 'cardiology-acs', 'icon': '❤️',
        'schema': S(
            sec('Presentation',
                rb('ACS Type', 'acs_type', O('STEMI', 'NSTEMI', 'Unstable Angina', 'Unclear')),
                num('Symptom Onset (hours ago)', 'onset_hours'),
                cb('Presenting Symptoms', 'symptoms',
                   O('Chest pain', 'Breathlessness', 'Diaphoresis', 'Nausea/Vomiting',
                     'Jaw/Arm radiation', 'Syncope', 'Palpitations')),
                cb('Cardiovascular Risk Factors', 'risk_factors',
                   O('Hypertension', 'Diabetes', 'Dyslipidaemia', 'Smoking', 'Family history',
                     'Obesity', 'CKD', 'Prior ACS')),
            ),
            sec('ECG & Haemodynamics',
                rb('ST Changes', 'st_changes',
                   O('ST Elevation', 'ST Depression', 'T-wave Inversion', 'New LBBB', 'Normal')),
                cb('ST Elevation Location', 'ste_location',
                   O('II/III/aVF (Inferior)', 'V1-V4 (Anterior)', 'I/aVL (Lateral)',
                     'V5-V6 (Lateral)', 'Posterior')),
                nr('Systolic BP', 'sbp', 60, 250, 'mmHg'),
                nr('Heart Rate', 'heart_rate', 30, 250, 'bpm'),
                dd('Killip Class', 'killip',
                   O('I — No HF signs', 'II — Mild HF', 'III — Pulmonary oedema', 'IV — Cardiogenic shock')),
            ),
            sec('Investigations',
                rb('Troponin 1', 'trop1', O('Negative', 'Borderline', 'Positive')),
                rb('Troponin 2 (3h/6h)', 'trop2', O('Negative', 'Borderline', 'Positive', 'Not done')),
                rb('CXR', 'cxr', O('Normal', 'Pulmonary oedema', 'Cardiomegaly', 'Other')),
                rb('Echo Available', 'echo_done', O('Yes', 'No', 'Pending')),
                nr('LV EF', 'lvef', 10, 80, '%'),
            ),
            sec('Reperfusion & Acute Management',
                rb('Reperfusion Strategy', 'reperfusion',
                   O('Primary PCI', 'Thrombolysis', 'Conservative', 'Awaiting decision')),
                cb('Acute Medications Given', 'acute_meds',
                   O('Aspirin', 'P2Y12 inhibitor', 'LMWH/Heparin', 'Nitrates',
                     'Beta-blocker', 'Statin', 'ACE inhibitor')),
                ta('Reperfusion Notes', 'reperfusion_notes'),
            ),
            sec('Secondary Prevention',
                cb('DAPT Given', 'dapt', O('Aspirin', 'Clopidogrel', 'Ticagrelor', 'Prasugrel')),
                yn('Statin Prescribed', 'statin'),
                yn('ACEi/ARB Prescribed', 'acei_arb'),
                yn('Beta-blocker Prescribed', 'beta_blocker'),
                ta('Secondary Prevention Plan', 'secondary_plan'),
            ),
        ),
    },
    {
        'title': 'Atrial Fibrillation Assessment',
        'desc': 'AF classification, CHA₂DS₂-VASc risk scoring, rate/rhythm control and anticoagulation.',
        'cat': 'cardiology', 'sub': 'cardiology-af', 'icon': '💓',
        'schema': S(
            sec('AF Classification',
                rb('AF Type', 'af_type',
                   O('First detected', 'Paroxysmal', 'Persistent', 'Long-standing persistent', 'Permanent')),
                num('Duration of current episode (hours)', 'episode_duration'),
                rb('Rhythm', 'rhythm', O('AF', 'Atrial Flutter', 'Sinus rhythm (post-cardioversion)')),
                cb('Symptoms', 'af_symptoms',
                   O('Palpitations', 'Breathlessness', 'Fatigue', 'Dizziness', 'Chest pain', 'Syncope', 'Asymptomatic')),
            ),
            sec('CHA₂DS₂-VASc Score',
                yn('Congestive Heart Failure (1pt)', 'chads_chf'),
                yn('Hypertension (1pt)', 'chads_htn'),
                yn('Age ≥75 (2pts)', 'chads_age75'),
                yn('Diabetes (1pt)', 'chads_dm'),
                yn('Stroke/TIA/TE History (2pts)', 'chads_stroke'),
                yn('Vascular Disease (1pt)', 'chads_vasc'),
                yn('Age 65–74 (1pt)', 'chads_age65'),
                yn('Female Sex (1pt)', 'chads_female'),
                num('CHA₂DS₂-VASc Total', 'chads_total'),
            ),
            sec('HAS-BLED Bleeding Risk',
                yn('Hypertension (1pt)', 'hasbled_htn'),
                yn('Renal/Liver dysfunction (1-2pts)', 'hasbled_renal_liver'),
                yn('Stroke history (1pt)', 'hasbled_stroke'),
                yn('Bleeding history/tendency (1pt)', 'hasbled_bleed'),
                yn('INR Labile (1pt)', 'hasbled_inr'),
                yn('Age >65 (1pt)', 'hasbled_age'),
                yn('Alcohol/drugs (1-2pts)', 'hasbled_drugs'),
                num('HAS-BLED Total', 'hasbled_total'),
            ),
            sec('Rate & Rhythm Control',
                rb('Strategy', 'strategy', O('Rate control', 'Rhythm control', 'Both')),
                nr('Resting Heart Rate', 'resting_hr', 30, 200, 'bpm'),
                cb('Rate Control Agents', 'rate_agents',
                   O('Beta-blocker', 'Diltiazem/Verapamil', 'Digoxin')),
                cb('Rhythm Control Agents', 'rhythm_agents',
                   O('Amiodarone', 'Flecainide', 'Dronedarone', 'Sotalol', 'DC Cardioversion')),
            ),
            sec('Anticoagulation',
                rb('Anticoagulation Decision', 'anticoag',
                   O('Indicated — starting', 'Indicated — already on', 'Not indicated', 'Contraindicated')),
                dd('Anticoagulant', 'anticoag_drug',
                   O('None', 'Warfarin', 'Apixaban', 'Rivaroxaban', 'Dabigatran', 'Edoxaban')),
                ta('Anticoagulation Notes', 'anticoag_notes'),
            ),
        ),
    },
    {
        'title': 'Cardiomyopathy Assessment',
        'desc': 'Cardiomyopathy type, echo parameters, genetics and management.',
        'cat': 'cardiology', 'sub': 'cardiology-cardiomyopathy', 'icon': '🫀',
        'schema': S(
            sec('Classification',
                rb('Type', 'cm_type',
                   O('Dilated (DCM)', 'Hypertrophic (HCM)', 'Restrictive (RCM)',
                     'Arrhythmogenic (ARVC)', 'Peripartum', 'Stress (Takotsubo)', 'Unclassified')),
                cb('Aetiology', 'aetiology',
                   O('Idiopathic', 'Genetic/Familial', 'Ischaemic', 'Viral/Inflammatory',
                     'Alcohol', 'Chemotherapy', 'Infiltrative', 'Autoimmune')),
                num('Duration of symptoms (months)', 'symptom_months'),
            ),
            sec('Symptoms & Functional Class',
                cb('Symptoms', 'cm_symptoms',
                   O('Breathlessness', 'Orthopnoea', 'PND', 'Oedema', 'Palpitations',
                     'Syncope', 'Chest pain', 'Fatigue')),
                dd('NYHA Class', 'nyha',
                   O('NYHA I — Asymptomatic', 'NYHA II — Mild symptoms',
                     'NYHA III — Moderate symptoms', 'NYHA IV — Severe symptoms')),
            ),
            sec('Echo Parameters',
                nr('LVEF', 'lvef', 10, 80, '%'),
                nr('LVEDD', 'lvedd', 20, 100, 'mm'),
                nr('IVS Thickness', 'ivs', 6, 35, 'mm'),
                nr('LVPW Thickness', 'lvpw', 6, 30, 'mm'),
                rb('LV Function', 'lv_function', O('Normal', 'Mildly reduced', 'Moderately reduced', 'Severely reduced')),
                rb('Diastolic Function', 'diastolic', O('Normal', 'Grade I', 'Grade II', 'Grade III')),
            ),
            sec('Family History & Genetics',
                yn('Family history of cardiomyopathy', 'family_cm'),
                yn('Family history of sudden cardiac death', 'family_scd'),
                yn('Genetic testing done', 'genetic_testing'),
                ta('Genetic Testing Results', 'genetic_results', na=True),
            ),
            sec('Management',
                cb('Medications', 'cm_meds',
                   O('ACEi/ARB', 'Beta-blocker', 'MRA', 'Diuretics', 'SGLT2i', 'ICD', 'CRT')),
                yn('ICD Implanted', 'icd'),
                yn('CRT Device', 'crt'),
                ta('Management Plan', 'cm_plan'),
            ),
        ),
    },
    {
        'title': 'Chest Pain Assessment',
        'desc': 'Systematic chest pain evaluation including characteristics, risk factors and differential.',
        'cat': 'cardiology', 'sub': 'cardiology-chest-pain', 'icon': '💔',
        'schema': S(
            sec('Pain Characteristics',
                sc('Pain Score', 'pain_score', 0, 10, 'No pain', 'Worst pain'),
                rb('Onset', 'cp_onset', O('Sudden', 'Gradual', 'At rest', 'On exertion')),
                num('Duration (minutes)', 'cp_duration'),
                cb('Quality', 'cp_quality',
                   O('Crushing/Pressure', 'Sharp/Stabbing', 'Burning', 'Dull', 'Tearing', 'Pleuritic')),
                rb('Radiation', 'cp_radiation',
                   O('No radiation', 'Left arm', 'Jaw', 'Back', 'Epigastrium', 'Both arms')),
                cb('Associated Symptoms', 'cp_assoc',
                   O('Diaphoresis', 'Nausea', 'Breathlessness', 'Palpitations', 'Syncope', 'Dizziness')),
            ),
            sec('Risk Factors',
                cb('Cardiac Risk Factors', 'cp_risk',
                   O('Hypertension', 'Diabetes', 'Dyslipidaemia', 'Smoking', 'Family history',
                     'Prior ACS/PCI/CABG', 'Obesity', 'CKD')),
                rb('Gender', 'gender', O('Male', 'Female')),
                num('Age (years)', 'age'),
            ),
            sec('Examination',
                nr('Systolic BP', 'sbp', 60, 250, 'mmHg'),
                nr('Heart Rate', 'hr', 30, 250, 'bpm'),
                rb('JVP', 'jvp', O('Normal', 'Raised', 'Not assessable')),
                rb('Heart Sounds', 'heart_sounds',
                   O('Normal S1S2', 'S3 gallop', 'S4 gallop', 'Murmur', 'Muffled')),
                rb('Lung Bases', 'lung_bases', O('Clear', 'Basal crackles', 'Wheeze', 'Reduced')),
            ),
            sec('Investigations',
                rb('ECG', 'cp_ecg',
                   O('Normal', 'ST elevation', 'ST depression', 'T-wave changes', 'LBBB', 'Other')),
                rb('Troponin', 'cp_trop', O('Negative', 'Borderline', 'Positive', 'Pending')),
                rb('CXR', 'cp_cxr',
                   O('Normal', 'Cardiomegaly', 'Pulmonary oedema', 'Pneumothorax', 'Widened mediastinum', 'Other')),
            ),
            sec('Differential & Plan',
                rb('Working Diagnosis', 'cp_dx',
                   O('ACS', 'Aortic Dissection', 'PE', 'Pericarditis', 'Musculoskeletal', 'GERD', 'Other')),
                ta('Management Plan', 'cp_plan'),
            ),
        ),
    },
    {
        'title': 'Dyslipidaemia Assessment',
        'desc': 'Lipid profile, cardiovascular risk stratification and management.',
        'cat': 'cardiology', 'sub': 'cardiology-dyslipidemia', 'icon': '🩸',
        'schema': S(
            sec('Lipid Profile',
                nr('Total Cholesterol', 'total_chol', 100, 500, 'mg/dL'),
                nr('LDL-C', 'ldl', 30, 400, 'mg/dL'),
                nr('HDL-C', 'hdl', 10, 150, 'mg/dL'),
                nr('Triglycerides', 'tg', 30, 2000, 'mg/dL'),
                nr('Non-HDL Cholesterol', 'non_hdl', 50, 400, 'mg/dL'),
                num('TC/HDL Ratio', 'tc_hdl_ratio'),
            ),
            sec('Cardiovascular Risk',
                rb('CV Risk Category', 'cv_risk',
                   O('Very High (≥10% 10yr)', 'High (5–10%)', 'Moderate (1–5%)', 'Low (<1%)')),
                cb('CV Risk Factors', 'cv_risk_factors',
                   O('Hypertension', 'Diabetes', 'Smoking', 'Obesity', 'Family history CVD',
                     'Prior CVD event', 'CKD', 'Age ≥55M/≥65F')),
                yn('Established ASCVD', 'established_ascvd'),
                yn('Familial Hypercholesterolaemia', 'fh'),
            ),
            sec('LDL Target & Treatment Goal',
                rb('LDL Target', 'ldl_target',
                   O('<55 mg/dL (Very High risk)', '<70 mg/dL (High risk)',
                     '<100 mg/dL (Moderate risk)', '<116 mg/dL (Low risk)')),
                yn('At LDL target', 'at_ldl_target'),
            ),
            sec('Management',
                cb('Lifestyle Advice Given', 'lifestyle_advice',
                   O('Diet modification', 'Weight loss', 'Exercise', 'Smoking cessation', 'Alcohol reduction')),
                cb('Lipid-lowering Therapy', 'lipid_meds',
                   O('Statin (low intensity)', 'Statin (moderate intensity)', 'Statin (high intensity)',
                     'Ezetimibe', 'PCSK9 inhibitor', 'Fibrate', 'Omega-3 fatty acids')),
                ta('Management Plan', 'dyslipid_plan'),
            ),
        ),
    },
    {
        'title': 'Heart Failure Assessment',
        'desc': 'Heart failure classification, symptoms, echo and management.',
        'cat': 'cardiology', 'sub': 'cardiology-heart-failure', 'icon': '💗',
        'schema': S(
            sec('Classification',
                rb('HF Type', 'hf_type',
                   O('HFrEF (EF<40%)', 'HFmrEF (EF 40-49%)', 'HFpEF (EF≥50%)', 'Unknown')),
                dd('NYHA Class', 'nyha',
                   O('I — No symptoms', 'II — Mild symptoms on exertion', 'III — Marked limitation', 'IV — Symptoms at rest')),
                rb('ACC/AHA Stage', 'aha_stage',
                   O('A — At risk', 'B — Structural disease, no symptoms', 'C — Symptomatic HF', 'D — Advanced HF')),
            ),
            sec('Symptoms',
                cb('Symptoms', 'hf_symptoms',
                   O('Breathlessness on exertion', 'Orthopnoea', 'PND', 'Ankle/leg oedema',
                     'Fatigue', 'Palpitations', 'Chest pain', 'Abdominal distension', 'Cough')),
                num('Pillows used at night', 'pillows'),
                num('Exercise tolerance (metres)', 'ex_tolerance'),
            ),
            sec('Examination',
                nr('Systolic BP', 'hf_sbp', 60, 250, 'mmHg'),
                nr('Diastolic BP', 'hf_dbp', 40, 150, 'mmHg'),
                nr('Heart Rate', 'hf_hr', 30, 200, 'bpm'),
                nr('Weight', 'hf_weight', 20, 300, 'kg'),
                rb('JVP', 'hf_jvp', O('Normal', 'Mildly elevated', 'Elevated')),
                rb('Peripheral Oedema', 'oedema', O('None', 'Mild (+)', 'Moderate (++)', 'Severe (+++)','Anasarca')),
            ),
            sec('Echo & Investigations',
                nr('LVEF', 'hf_lvef', 10, 80, '%'),
                rb('Diastolic Function', 'hf_diastolic',
                   O('Normal', 'Grade I (Impaired relaxation)', 'Grade II (Pseudonormal)', 'Grade III (Restrictive)')),
                nr('NT-proBNP/BNP', 'bnp', 0, 50000, 'pg/mL'),
                nr('Serum Creatinine', 'creatinine', 0.3, 20, 'mg/dL'),
            ),
            sec('Management',
                cb('Medications', 'hf_meds',
                   O('ACEi/ARB', 'Beta-blocker', 'MRA', 'SGLT2i', 'Diuretics (frusemide)',
                     'Hydralazine+Nitrate', 'Digoxin', 'Ivabradine')),
                yn('Device therapy', 'hf_device'),
                dd('Device', 'hf_device_type', O('None', 'ICD', 'CRT-P', 'CRT-D', 'ICD + CRT')),
                ta('Management Plan', 'hf_plan'),
            ),
        ),
    },
    {
        'title': 'Hypertension Assessment',
        'desc': 'Blood pressure readings, target organ damage, lifestyle and medication management.',
        'cat': 'cardiology', 'sub': 'cardiology-hypertension', 'icon': '🩺',
        'schema': S(
            sec('Blood Pressure Readings',
                nr('SBP Reading 1', 'sbp1', 60, 260, 'mmHg'),
                nr('DBP Reading 1', 'dbp1', 40, 150, 'mmHg'),
                nr('SBP Reading 2', 'sbp2', 60, 260, 'mmHg'),
                nr('DBP Reading 2', 'dbp2', 40, 150, 'mmHg'),
                nr('Mean SBP', 'mean_sbp', 60, 260, 'mmHg'),
                nr('Heart Rate', 'htn_hr', 30, 200, 'bpm'),
                rb('BP Stage (JNC/ISH 2020)', 'bp_stage',
                   O('Normal (<120/80)', 'Elevated (120-129/<80)', 'Grade 1 (130-139/80-89)',
                     'Grade 2 (≥140/≥90)', 'Hypertensive crisis (≥180/≥120)')),
            ),
            sec('Target Organ Damage',
                yn('LVH on ECG/Echo', 'lvh'),
                yn('Retinopathy', 'retinopathy'),
                yn('Proteinuria', 'proteinuria'),
                yn('CKD (eGFR <60)', 'ckd'),
                yn('Prior stroke/TIA', 'prior_stroke'),
                yn('Prior MI/ACS', 'prior_mi'),
                yn('Peripheral arterial disease', 'pad'),
            ),
            sec('CV Risk Factors',
                cb('Risk Factors', 'htn_risk',
                   O('Diabetes', 'Dyslipidaemia', 'Smoking', 'Obesity', 'Physical inactivity',
                     'Family history CVD', 'Male sex', 'Age ≥55')),
                rb('Overall CV Risk', 'overall_cv_risk', O('Low', 'Moderate', 'High', 'Very High')),
            ),
            sec('Lifestyle Modifications',
                cb('Lifestyle Advice Given', 'htn_lifestyle',
                   O('Salt reduction (<5g/day)', 'DASH diet', 'Weight loss', 'Regular exercise',
                     'Smoking cessation', 'Alcohol reduction', 'Stress management')),
            ),
            sec('Medications',
                cb('Antihypertensives', 'htn_meds',
                   O('ACE inhibitor', 'ARB', 'Calcium channel blocker', 'Thiazide diuretic',
                     'Beta-blocker', 'Alpha-blocker', 'Spironolactone', 'Clonidine')),
                yn('On combination therapy', 'combo_therapy'),
                ta('Medication Plan & Target BP', 'htn_plan'),
            ),
        ),
    },
    {
        'title': 'Pericardial Disease Assessment',
        'desc': 'Acute pericarditis, pericardial effusion, tamponade and constrictive pericarditis.',
        'cat': 'cardiology', 'sub': 'cardiology-pericardial', 'icon': '🫀',
        'schema': S(
            sec('Type & Aetiology',
                rb('Pericardial Diagnosis', 'peri_dx',
                   O('Acute Pericarditis', 'Recurrent Pericarditis', 'Constrictive Pericarditis',
                     'Pericardial Effusion', 'Cardiac Tamponade')),
                rb('Aetiology', 'peri_aetiology',
                   O('Idiopathic/Viral', 'Bacterial (including TB)', 'Autoimmune/Inflammatory',
                     'Malignant', 'Post-MI (Dressler)', 'Post-cardiac surgery', 'Uraemic', 'Iatrogenic')),
            ),
            sec('Symptoms',
                cb('Symptoms', 'peri_symptoms',
                   O('Sharp pleuritic chest pain', 'Breathlessness', 'Fever', 'Friction rub',
                     'Dry cough', 'Dysphagia', 'Hiccups', 'Dizziness/Presyncope')),
                rb('Pain relief on', 'pain_position', O('Sitting forward', 'Lying flat', 'Not position dependent')),
            ),
            sec('ECG & Echo',
                rb('ECG Changes', 'peri_ecg',
                   O('Normal', 'Diffuse ST elevation (saddle shape)', 'PR depression',
                     'Electrical alternans', 'Low voltage')),
                nr('Echo Effusion Size', 'effusion_size', 0, 40, 'mm'),
                rb('Effusion Haemodynamic Impact', 'echo_hd',
                   O('None', 'Small — haemodynamically stable', 'Moderate', 'Large', 'Tamponade physiology')),
            ),
            sec('Management',
                cb('Medications', 'peri_meds',
                   O('NSAIDs', 'Colchicine', 'Corticosteroids', 'Antibiotics', 'Pericardiocentesis done')),
                ta('Management Plan', 'peri_plan'),
            ),
        ),
    },
    {
        'title': 'Rheumatic Heart Disease Assessment',
        'desc': 'Acute rheumatic fever history, valve involvement, echo findings and prophylaxis.',
        'cat': 'cardiology', 'sub': 'cardiology-rhd', 'icon': '🫀',
        'schema': S(
            sec('Acute RF History',
                yn('History of Acute Rheumatic Fever', 'arf_history'),
                dt('First episode date', 'arf_first_date'),
                num('Number of ARF episodes', 'arf_episodes'),
                cb('Jones Criteria (major)', 'jones_major',
                   O('Carditis', 'Polyarthritis', 'Chorea', 'Erythema marginatum', 'Subcutaneous nodules')),
                cb('Jones Criteria (minor)', 'jones_minor',
                   O('Fever', 'Elevated CRP/ESR', 'Prolonged PR interval', 'Arthralgia')),
                yn('Evidence of preceding GAS infection (ASOT/anti-DNaseB)', 'gas_evidence'),
            ),
            sec('Valve Involvement',
                rb('Mitral Valve', 'mitral',
                   O('Normal', 'Mild regurgitation', 'Moderate regurgitation', 'Severe regurgitation',
                     'Mild stenosis', 'Moderate stenosis', 'Severe stenosis')),
                rb('Aortic Valve', 'aortic',
                   O('Normal', 'Mild regurgitation', 'Moderate regurgitation', 'Severe regurgitation',
                     'Mild stenosis', 'Moderate stenosis', 'Severe stenosis')),
                yn('Tricuspid involvement', 'tricuspid'),
                yn('Pulmonary involvement', 'pulmonary'),
            ),
            sec('Echo Measurements',
                nr('Mitral Valve Area', 'mva', 0.5, 5.0, 'cm²'),
                nr('Mean Mitral Gradient', 'mean_mg', 0, 40, 'mmHg'),
                nr('LVEF', 'rhd_lvef', 10, 80, '%'),
                rb('Pulmonary Hypertension', 'phtn', O('None', 'Mild', 'Moderate', 'Severe')),
            ),
            sec('Prophylaxis',
                rb('Penicillin Prophylaxis', 'prophylaxis',
                   O('On benzathine penicillin IM', 'On oral penicillin', 'Penicillin allergy — on erythromycin', 'Not on prophylaxis')),
                num('Prophylaxis planned duration (years)', 'prophylaxis_years'),
                ta('Plan & Follow-up', 'rhd_plan'),
            ),
        ),
    },
    {
        'title': 'Valvular Heart Disease Assessment',
        'desc': 'Valve disease type, severity, symptoms and intervention planning.',
        'cat': 'cardiology', 'sub': 'cardiology-valvular', 'icon': '🫀',
        'schema': S(
            sec('Valve & Lesion',
                cb('Valve(s) Affected', 'valve',
                   O('Mitral', 'Aortic', 'Tricuspid', 'Pulmonary')),
                rb('Primary Lesion', 'lesion',
                   O('Regurgitation', 'Stenosis', 'Mixed (stenosis + regurgitation)')),
                rb('Aetiology', 'valve_aetiology',
                   O('Degenerative/Calcific', 'Rheumatic', 'Congenital', 'Infective endocarditis',
                     'Post-MI', 'Connective tissue disorder')),
            ),
            sec('Severity (Echo)',
                rb('Severity', 'valve_severity', O('Mild', 'Moderate', 'Severe')),
                nr('LVEF', 'valve_lvef', 10, 80, '%'),
                nr('Aortic Valve Area (if AS)', 'ava', 0.3, 4.0, 'cm²'),
                nr('Mean Gradient (if stenosis)', 'mean_grad', 0, 100, 'mmHg'),
                nr('Vena Contracta (if regurgitation)', 'vena_contracta', 0, 20, 'mm'),
            ),
            sec('Symptoms',
                dd('NYHA Class', 'valve_nyha',
                   O('I — Asymptomatic', 'II — Mild', 'III — Moderate', 'IV — Severe')),
                cb('Symptoms', 'valve_symptoms',
                   O('Breathlessness', 'Chest pain', 'Syncope', 'Fatigue', 'Palpitations',
                     'Oedema', 'Orthopnoea', 'Haemoptysis')),
            ),
            sec('Management',
                rb('Management Strategy', 'valve_mgmt',
                   O('Watchful waiting', 'Medical management', 'Intervention indicated')),
                rb('Planned Intervention', 'valve_intervention',
                   O('None', 'Surgical valve repair', 'Surgical valve replacement (bioprosthetic)',
                     'Surgical valve replacement (mechanical)', 'TAVI', 'TMVR', 'Balloon valvuloplasty')),
                ta('Management Plan', 'valve_plan'),
            ),
        ),
    },
]

# ─── All batches registry ────────────────────────────────────────────────────

BATCHES = {
    'general':    GENERAL,
    'cardiology': CARDIOLOGY,
    # Phase 2 batches — added by seed_assessment_forms_p2.py:
    # 'clinical', 'ent', 'gastro', 'obg', 'ortho', 'peds', 'specialty', 'systems'
}

# ─── Seeding logic ───────────────────────────────────────────────────────────

def seed_batch(batch_name, db):
    forms = BATCHES.get(batch_name)
    if not forms:
        print(f"[seed] Unknown batch '{batch_name}' — available: {', '.join(BATCHES)}")
        return 0, 0

    inserted = skipped = 0
    for f in forms:
        exists = db.query(AssessmentForm.id).filter(
            AssessmentForm.subcategory == f['sub']
        ).first()
        if exists:
            print(f"  [skip] {f['sub']}")
            skipped += 1
            continue
        row = AssessmentForm(
            title            = f['title'],
            description      = f.get('desc', ''),
            category         = f['cat'],
            subcategory      = f['sub'],
            icon             = f.get('icon', '📋'),
            schema           = f['schema'],
            status           = 'published',
            version          = 1,
            is_template      = False,
            is_iview_enabled = False,
            created_at       = datetime.utcnow(),
            updated_at       = datetime.utcnow(),
            published_at     = datetime.utcnow(),
        )
        db.add(row)
        print(f"  [add]  {f['sub']} — {f['title']}")
        inserted += 1

    db.commit()
    return inserted, skipped


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--all', action='store_true', help='Seed all batches')
    parser.add_argument('--batch', help='Seed a specific batch by name')
    args = parser.parse_args()

    db = DB()
    try:
        if args.all:
            total_ins = total_skip = 0
            for name in BATCHES:
                print(f"\n── {name} ──")
                ins, skip = seed_batch(name, db)
                total_ins += ins; total_skip += skip
            print(f"\n✓ Done — inserted {total_ins}, skipped {total_skip}")
        elif args.batch:
            print(f"\n── {args.batch} ──")
            ins, skip = seed_batch(args.batch, db)
            print(f"\n✓ Done — inserted {ins}, skipped {skip}")
        else:
            print("Usage: python seed_assessment_forms.py --all  OR  --batch <name>")
            print(f"Batches: {', '.join(BATCHES)}")
    finally:
        db.close()


if __name__ == '__main__':
    main()
