"""
Anatomy & topographic terminology — curated for clinical use.
Covers: surface regions, bones, joints, muscles, organs, vessels, nerves,
        brain, spinal cord, endocrine glands, lymphatics.
Format: {display, specialty, synonyms}
System: fma (Foundational Model of Anatomy) — no ICD-10 code needed.
"""

ANATOMY = [
    # ── Surface / Regional ────────────────────────────────────────────────────
    {"display": "Scalp", "specialty": "neurology", "synonyms": "scalp|calvaria"},
    {"display": "Forehead", "specialty": "general_medicine", "synonyms": "forehead|frontal region"},
    {"display": "Temple", "specialty": "general_medicine", "synonyms": "temple|temporal region"},
    {"display": "Occiput", "specialty": "neurology", "synonyms": "occiput|back of head|occipital region"},
    {"display": "Face", "specialty": "general_medicine", "synonyms": "face|facial region"},
    {"display": "Orbit (Eye socket)", "specialty": "ophthalmology", "synonyms": "orbit|eye socket|orbital region"},
    {"display": "Nasal cavity", "specialty": "ent", "synonyms": "nasal cavity|nose inside|nares"},
    {"display": "Paranasal sinuses", "specialty": "ent", "synonyms": "sinuses|frontal sinus|maxillary sinus|ethmoid|sphenoid"},
    {"display": "External ear (Pinna)", "specialty": "ent", "synonyms": "pinna|auricle|external ear"},
    {"display": "External auditory canal", "specialty": "ent", "synonyms": "ear canal|EAC|auditory meatus"},
    {"display": "Middle ear", "specialty": "ent", "synonyms": "middle ear|tympanic cavity|ossicles"},
    {"display": "Mastoid", "specialty": "ent", "synonyms": "mastoid|mastoid process|mastoid region"},
    {"display": "Oral cavity", "specialty": "ent", "synonyms": "mouth|oral cavity|buccal cavity"},
    {"display": "Tongue", "specialty": "ent", "synonyms": "tongue|lingua"},
    {"display": "Pharynx", "specialty": "ent", "synonyms": "pharynx|throat|oropharynx|nasopharynx|hypopharynx"},
    {"display": "Larynx", "specialty": "ent", "synonyms": "larynx|voice box|glottis|vocal cords"},
    {"display": "Neck (anterior)", "specialty": "general_medicine", "synonyms": "anterior neck|front of neck|cervical region"},
    {"display": "Neck (posterior)", "specialty": "general_medicine", "synonyms": "posterior neck|back of neck|nape"},
    {"display": "Chest wall", "specialty": "general_medicine", "synonyms": "chest wall|thoracic wall|ribcage surface"},
    {"display": "Sternum", "specialty": "general_medicine", "synonyms": "sternum|breastbone|sternal region"},
    {"display": "Anterior chest", "specialty": "cardiology", "synonyms": "anterior chest|front chest|precordium"},
    {"display": "Precordium", "specialty": "cardiology", "synonyms": "precordium|cardiac region|chest over heart"},
    {"display": "Axilla", "specialty": "general_medicine", "synonyms": "axilla|armpit|axillary region"},
    {"display": "Breast", "specialty": "general_medicine", "synonyms": "breast|mammary gland|bosom"},
    {"display": "Epigastrium", "specialty": "gastroenterology", "synonyms": "epigastrium|epigastric region|upper abdomen centre"},
    {"display": "Umbilical region", "specialty": "gastroenterology", "synonyms": "periumbilical|umbilical|navel region"},
    {"display": "Right hypochondrium", "specialty": "gastroenterology", "synonyms": "RHC|right hypochondrium|right upper abdomen"},
    {"display": "Left hypochondrium", "specialty": "gastroenterology", "synonyms": "LHC|left hypochondrium|left upper abdomen"},
    {"display": "Right iliac fossa", "specialty": "gastroenterology", "synonyms": "RIF|right iliac fossa|right lower abdomen|McBurney"},
    {"display": "Left iliac fossa", "specialty": "gastroenterology", "synonyms": "LIF|left iliac fossa|left lower abdomen"},
    {"display": "Hypogastrium", "specialty": "gastroenterology", "synonyms": "hypogastrium|suprapubic region|lower abdomen centre"},
    {"display": "Flank", "specialty": "urology", "synonyms": "flank|loin|lumbar region|renal angle"},
    {"display": "Perineum", "specialty": "urology", "synonyms": "perineum|perineal region"},
    {"display": "Groin", "specialty": "general_medicine", "synonyms": "groin|inguinal region|inguinal area"},
    {"display": "Gluteal region", "specialty": "orthopedics", "synonyms": "buttock|gluteal region|gluteus"},
    {"display": "Sacral region", "specialty": "orthopedics", "synonyms": "sacrum surface|sacral region|tailbone area"},

    # ── Spine / Vertebral column ──────────────────────────────────────────────
    {"display": "Cervical spine (C1–C7)", "specialty": "orthopedics", "synonyms": "cervical spine|neck spine|C-spine|cervical vertebrae"},
    {"display": "C1 Atlas", "specialty": "orthopedics", "synonyms": "atlas|C1 vertebra|first cervical"},
    {"display": "C2 Axis", "specialty": "orthopedics", "synonyms": "axis|C2 vertebra|second cervical|dens"},
    {"display": "C3 vertebra", "specialty": "orthopedics", "synonyms": "C3|third cervical vertebra"},
    {"display": "C4 vertebra", "specialty": "orthopedics", "synonyms": "C4|fourth cervical vertebra"},
    {"display": "C5 vertebra", "specialty": "orthopedics", "synonyms": "C5|fifth cervical vertebra"},
    {"display": "C6 vertebra", "specialty": "orthopedics", "synonyms": "C6|sixth cervical vertebra"},
    {"display": "C7 vertebra", "specialty": "orthopedics", "synonyms": "C7|seventh cervical vertebra|vertebra prominens"},
    {"display": "Thoracic spine (T1–T12)", "specialty": "orthopedics", "synonyms": "thoracic spine|dorsal spine|T-spine"},
    {"display": "T1 vertebra", "specialty": "orthopedics", "synonyms": "T1|first thoracic vertebra"},
    {"display": "T2 vertebra", "specialty": "orthopedics", "synonyms": "T2|second thoracic vertebra"},
    {"display": "T3 vertebra", "specialty": "orthopedics", "synonyms": "T3|third thoracic vertebra"},
    {"display": "T4 vertebra", "specialty": "orthopedics", "synonyms": "T4|fourth thoracic vertebra"},
    {"display": "T5 vertebra", "specialty": "orthopedics", "synonyms": "T5|fifth thoracic vertebra"},
    {"display": "T6 vertebra", "specialty": "orthopedics", "synonyms": "T6|sixth thoracic vertebra"},
    {"display": "T7 vertebra", "specialty": "orthopedics", "synonyms": "T7|seventh thoracic vertebra"},
    {"display": "T8 vertebra", "specialty": "orthopedics", "synonyms": "T8|eighth thoracic vertebra"},
    {"display": "T9 vertebra", "specialty": "orthopedics", "synonyms": "T9|ninth thoracic vertebra"},
    {"display": "T10 vertebra", "specialty": "orthopedics", "synonyms": "T10|tenth thoracic vertebra"},
    {"display": "T11 vertebra", "specialty": "orthopedics", "synonyms": "T11|eleventh thoracic vertebra"},
    {"display": "T12 vertebra", "specialty": "orthopedics", "synonyms": "T12|twelfth thoracic vertebra"},
    {"display": "Lumbar spine (L1–L5)", "specialty": "orthopedics", "synonyms": "lumbar spine|lower back spine|L-spine"},
    {"display": "L1 vertebra", "specialty": "orthopedics", "synonyms": "L1|first lumbar vertebra"},
    {"display": "L2 vertebra", "specialty": "orthopedics", "synonyms": "L2|second lumbar vertebra"},
    {"display": "L3 vertebra", "specialty": "orthopedics", "synonyms": "L3|third lumbar vertebra"},
    {"display": "L4 vertebra", "specialty": "orthopedics", "synonyms": "L4|fourth lumbar vertebra"},
    {"display": "L5 vertebra", "specialty": "orthopedics", "synonyms": "L5|fifth lumbar vertebra"},
    {"display": "Sacrum (S1–S5)", "specialty": "orthopedics", "synonyms": "sacrum|sacral vertebrae|S1-S5"},
    {"display": "Coccyx", "specialty": "orthopedics", "synonyms": "coccyx|tailbone|coccygeal vertebrae"},
    {"display": "Intervertebral disc (cervical)", "specialty": "orthopedics", "synonyms": "cervical disc|neck disc|C disc"},
    {"display": "Intervertebral disc (lumbar)", "specialty": "orthopedics", "synonyms": "lumbar disc|lower back disc|L disc|PIVD"},
    {"display": "Sacroiliac joint", "specialty": "orthopedics", "synonyms": "SI joint|sacroiliac|sacroiliac joint"},
    {"display": "Spinal cord", "specialty": "neurology", "synonyms": "spinal cord|myelon|cord"},
    {"display": "Cauda equina", "specialty": "neurology", "synonyms": "cauda equina|horse tail|lower spinal roots"},

    # ── Skull / Cranium ───────────────────────────────────────────────────────
    {"display": "Skull", "specialty": "neurology", "synonyms": "skull|cranium|calvaria"},
    {"display": "Frontal bone", "specialty": "neurology", "synonyms": "frontal bone|forehead bone"},
    {"display": "Parietal bone", "specialty": "neurology", "synonyms": "parietal bone|parietal"},
    {"display": "Temporal bone", "specialty": "neurology", "synonyms": "temporal bone|temple bone"},
    {"display": "Occipital bone", "specialty": "neurology", "synonyms": "occipital bone|occiput bone"},
    {"display": "Mandible", "specialty": "ent", "synonyms": "mandible|jaw bone|lower jaw"},
    {"display": "Maxilla", "specialty": "ent", "synonyms": "maxilla|upper jaw|maxillary bone"},
    {"display": "Temporomandibular joint (TMJ)", "specialty": "ent", "synonyms": "TMJ|jaw joint|temporomandibular"},

    # ── Thoracic bones ────────────────────────────────────────────────────────
    {"display": "Clavicle", "specialty": "orthopedics", "synonyms": "clavicle|collarbone"},
    {"display": "Scapula", "specialty": "orthopedics", "synonyms": "scapula|shoulder blade"},
    {"display": "Sternum", "specialty": "general_medicine", "synonyms": "sternum|breastbone|manubrium|xiphoid"},
    {"display": "Rib 1", "specialty": "orthopedics", "synonyms": "first rib|rib 1|1st rib"},
    {"display": "Rib 2", "specialty": "orthopedics", "synonyms": "second rib|rib 2"},
    {"display": "Rib 3", "specialty": "orthopedics", "synonyms": "third rib|rib 3"},
    {"display": "Rib 4", "specialty": "orthopedics", "synonyms": "fourth rib|rib 4"},
    {"display": "Rib 5", "specialty": "orthopedics", "synonyms": "fifth rib|rib 5"},
    {"display": "Rib 6", "specialty": "orthopedics", "synonyms": "sixth rib|rib 6"},
    {"display": "Rib 7", "specialty": "orthopedics", "synonyms": "seventh rib|rib 7"},
    {"display": "Rib 8", "specialty": "orthopedics", "synonyms": "eighth rib|rib 8"},
    {"display": "Rib 9", "specialty": "orthopedics", "synonyms": "ninth rib|rib 9"},
    {"display": "Rib 10", "specialty": "orthopedics", "synonyms": "tenth rib|rib 10"},
    {"display": "Rib 11 (floating)", "specialty": "orthopedics", "synonyms": "11th rib|floating rib"},
    {"display": "Rib 12 (floating)", "specialty": "orthopedics", "synonyms": "12th rib|floating rib"},

    # ── Upper limb bones ──────────────────────────────────────────────────────
    {"display": "Humerus", "specialty": "orthopedics", "synonyms": "humerus|upper arm bone"},
    {"display": "Radius", "specialty": "orthopedics", "synonyms": "radius|forearm bone lateral"},
    {"display": "Ulna", "specialty": "orthopedics", "synonyms": "ulna|forearm bone medial"},
    {"display": "Carpal bones", "specialty": "orthopedics", "synonyms": "carpals|wrist bones|scaphoid|lunate|triquetrum|pisiform|trapezium|trapezoid|capitate|hamate"},
    {"display": "Metacarpal bones", "specialty": "orthopedics", "synonyms": "metacarpals|hand bones|palm bones"},
    {"display": "Phalanges (hand)", "specialty": "orthopedics", "synonyms": "finger bones|phalanges hand|proximal middle distal phalanx"},

    # ── Lower limb bones ──────────────────────────────────────────────────────
    {"display": "Pelvis", "specialty": "orthopedics", "synonyms": "pelvis|pelvic bone|hip bone|os coxae"},
    {"display": "Ilium", "specialty": "orthopedics", "synonyms": "ilium|iliac bone|iliac crest"},
    {"display": "Ischium", "specialty": "orthopedics", "synonyms": "ischium|ischial bone|ischial tuberosity"},
    {"display": "Pubis", "specialty": "orthopedics", "synonyms": "pubis|pubic bone|pubic symphysis"},
    {"display": "Femur", "specialty": "orthopedics", "synonyms": "femur|thigh bone|femoral"},
    {"display": "Patella", "specialty": "orthopedics", "synonyms": "patella|kneecap"},
    {"display": "Tibia", "specialty": "orthopedics", "synonyms": "tibia|shin bone|tibial"},
    {"display": "Fibula", "specialty": "orthopedics", "synonyms": "fibula|calf bone|fibular"},
    {"display": "Tarsal bones", "specialty": "orthopedics", "synonyms": "tarsals|ankle bones|calcaneus|talus|navicular|cuboid|cuneiform"},
    {"display": "Calcaneus (Heel bone)", "specialty": "orthopedics", "synonyms": "calcaneus|heel bone|os calcis"},
    {"display": "Metatarsal bones", "specialty": "orthopedics", "synonyms": "metatarsals|foot bones"},
    {"display": "Phalanges (foot)", "specialty": "orthopedics", "synonyms": "toe bones|phalanges foot"},

    # ── Major joints ──────────────────────────────────────────────────────────
    {"display": "Shoulder joint (Glenohumeral)", "specialty": "orthopedics", "synonyms": "shoulder joint|glenohumeral|shoulder"},
    {"display": "Acromioclavicular joint", "specialty": "orthopedics", "synonyms": "AC joint|acromioclavicular"},
    {"display": "Elbow joint", "specialty": "orthopedics", "synonyms": "elbow joint|cubital joint|elbow"},
    {"display": "Wrist joint", "specialty": "orthopedics", "synonyms": "wrist joint|radiocarpal joint|wrist"},
    {"display": "Hip joint", "specialty": "orthopedics", "synonyms": "hip joint|coxofemoral joint|hip"},
    {"display": "Knee joint", "specialty": "orthopedics", "synonyms": "knee joint|tibiofemoral|knee|femorotibial"},
    {"display": "Ankle joint", "specialty": "orthopedics", "synonyms": "ankle joint|talocrural joint|ankle"},
    {"display": "First MTP joint (Big toe)", "specialty": "orthopedics", "synonyms": "big toe joint|first MTP|hallux joint"},
    {"display": "Interphalangeal joints (hand)", "specialty": "orthopedics", "synonyms": "finger joints|IP joints|PIP DIP joints"},
    {"display": "Interphalangeal joints (foot)", "specialty": "orthopedics", "synonyms": "toe joints|IP joints foot"},

    # ── Brain regions ─────────────────────────────────────────────────────────
    {"display": "Brain", "specialty": "neurology", "synonyms": "brain|cerebrum|encephalon"},
    {"display": "Frontal lobe", "specialty": "neurology", "synonyms": "frontal lobe|prefrontal cortex|motor cortex"},
    {"display": "Parietal lobe", "specialty": "neurology", "synonyms": "parietal lobe|sensory cortex|somatosensory"},
    {"display": "Temporal lobe", "specialty": "neurology", "synonyms": "temporal lobe|auditory cortex|Wernicke"},
    {"display": "Occipital lobe", "specialty": "neurology", "synonyms": "occipital lobe|visual cortex"},
    {"display": "Cerebellum", "specialty": "neurology", "synonyms": "cerebellum|little brain|cerebellar"},
    {"display": "Brainstem", "specialty": "neurology", "synonyms": "brainstem|midbrain|pons|medulla oblongata"},
    {"display": "Basal ganglia", "specialty": "neurology", "synonyms": "basal ganglia|caudate|putamen|globus pallidus"},
    {"display": "Thalamus", "specialty": "neurology", "synonyms": "thalamus|thalamic"},
    {"display": "Hypothalamus", "specialty": "neurology", "synonyms": "hypothalamus|hypothalamic"},
    {"display": "Hippocampus", "specialty": "neurology", "synonyms": "hippocampus|hippocampal"},
    {"display": "Corpus callosum", "specialty": "neurology", "synonyms": "corpus callosum|commissure"},
    {"display": "Cerebral ventricles", "specialty": "neurology", "synonyms": "ventricles|lateral ventricle|third ventricle|fourth ventricle|CSF space"},

    # ── Peripheral nerves ─────────────────────────────────────────────────────
    {"display": "Brachial plexus", "specialty": "neurology", "synonyms": "brachial plexus|arm nerve plexus|C5-T1 roots"},
    {"display": "Radial nerve", "specialty": "neurology", "synonyms": "radial nerve|posterior interosseous"},
    {"display": "Median nerve", "specialty": "neurology", "synonyms": "median nerve|carpal tunnel nerve"},
    {"display": "Ulnar nerve", "specialty": "neurology", "synonyms": "ulnar nerve|funny bone nerve"},
    {"display": "Sciatic nerve", "specialty": "neurology", "synonyms": "sciatic nerve|sciatica nerve"},
    {"display": "Femoral nerve", "specialty": "neurology", "synonyms": "femoral nerve|anterior thigh nerve"},
    {"display": "Peroneal nerve (Common fibular)", "specialty": "neurology", "synonyms": "peroneal nerve|common fibular|CPN"},
    {"display": "Tibial nerve", "specialty": "neurology", "synonyms": "tibial nerve|posterior tibial"},
    {"display": "Lumbosacral plexus", "specialty": "neurology", "synonyms": "lumbosacral plexus|L1-S3|leg nerve plexus"},
    {"display": "Facial nerve (CN VII)", "specialty": "neurology", "synonyms": "facial nerve|cranial nerve 7|CN VII"},
    {"display": "Trigeminal nerve (CN V)", "specialty": "neurology", "synonyms": "trigeminal nerve|CN V|facial sensation nerve"},
    {"display": "Vagus nerve (CN X)", "specialty": "neurology", "synonyms": "vagus nerve|CN X|cranial nerve 10"},
    {"display": "Optic nerve (CN II)", "specialty": "neurology", "synonyms": "optic nerve|CN II|cranial nerve 2|visual nerve"},

    # ── Cardiovascular ────────────────────────────────────────────────────────
    {"display": "Heart", "specialty": "cardiology", "synonyms": "heart|cardiac|cor"},
    {"display": "Left ventricle", "specialty": "cardiology", "synonyms": "left ventricle|LV|left ventricular"},
    {"display": "Right ventricle", "specialty": "cardiology", "synonyms": "right ventricle|RV|right ventricular"},
    {"display": "Left atrium", "specialty": "cardiology", "synonyms": "left atrium|LA|left atrial"},
    {"display": "Right atrium", "specialty": "cardiology", "synonyms": "right atrium|RA|right atrial"},
    {"display": "Mitral valve", "specialty": "cardiology", "synonyms": "mitral valve|bicuspid valve|MV"},
    {"display": "Aortic valve", "specialty": "cardiology", "synonyms": "aortic valve|AV"},
    {"display": "Tricuspid valve", "specialty": "cardiology", "synonyms": "tricuspid valve|TV"},
    {"display": "Pulmonary valve", "specialty": "cardiology", "synonyms": "pulmonary valve|pulmonic valve|PV"},
    {"display": "Aorta", "specialty": "cardiology", "synonyms": "aorta|ascending aorta|aortic arch|descending aorta"},
    {"display": "Coronary arteries", "specialty": "cardiology", "synonyms": "coronary artery|LAD|LCx|RCA|coronaries"},
    {"display": "Left anterior descending artery (LAD)", "specialty": "cardiology", "synonyms": "LAD|left anterior descending|widow maker"},
    {"display": "Right coronary artery (RCA)", "specialty": "cardiology", "synonyms": "RCA|right coronary artery"},
    {"display": "Left circumflex artery (LCx)", "specialty": "cardiology", "synonyms": "LCx|left circumflex|circumflex artery"},
    {"display": "Pulmonary artery", "specialty": "cardiology", "synonyms": "pulmonary artery|PA|pulmonary trunk"},
    {"display": "Inferior vena cava (IVC)", "specialty": "cardiology", "synonyms": "IVC|inferior vena cava"},
    {"display": "Superior vena cava (SVC)", "specialty": "cardiology", "synonyms": "SVC|superior vena cava"},
    {"display": "Carotid artery", "specialty": "cardiology", "synonyms": "carotid|common carotid|internal carotid|external carotid"},
    {"display": "Jugular vein", "specialty": "cardiology", "synonyms": "jugular vein|IJV|internal jugular|external jugular"},
    {"display": "Femoral artery", "specialty": "cardiology", "synonyms": "femoral artery|common femoral|superficial femoral"},
    {"display": "Popliteal artery", "specialty": "cardiology", "synonyms": "popliteal artery|behind knee artery"},
    {"display": "Renal artery", "specialty": "nephrology", "synonyms": "renal artery|kidney artery"},
    {"display": "Portal vein", "specialty": "gastroenterology", "synonyms": "portal vein|hepatic portal|portal circulation"},
    {"display": "Hepatic artery", "specialty": "gastroenterology", "synonyms": "hepatic artery|liver artery"},

    # ── Respiratory ───────────────────────────────────────────────────────────
    {"display": "Trachea", "specialty": "pulmonology", "synonyms": "trachea|windpipe"},
    {"display": "Right lung", "specialty": "pulmonology", "synonyms": "right lung|right pulmonary"},
    {"display": "Left lung", "specialty": "pulmonology", "synonyms": "left lung|left pulmonary"},
    {"display": "Right upper lobe (RUL)", "specialty": "pulmonology", "synonyms": "RUL|right upper lobe|right apex"},
    {"display": "Right middle lobe (RML)", "specialty": "pulmonology", "synonyms": "RML|right middle lobe"},
    {"display": "Right lower lobe (RLL)", "specialty": "pulmonology", "synonyms": "RLL|right lower lobe|right base"},
    {"display": "Left upper lobe (LUL)", "specialty": "pulmonology", "synonyms": "LUL|left upper lobe|lingula"},
    {"display": "Left lower lobe (LLL)", "specialty": "pulmonology", "synonyms": "LLL|left lower lobe|left base"},
    {"display": "Bronchi (main)", "specialty": "pulmonology", "synonyms": "main bronchus|left bronchus|right bronchus|mainstem bronchus"},
    {"display": "Pleura", "specialty": "pulmonology", "synonyms": "pleura|pleural space|visceral pleura|parietal pleura"},
    {"display": "Diaphragm", "specialty": "pulmonology", "synonyms": "diaphragm|breathing muscle"},
    {"display": "Pleural cavity", "specialty": "pulmonology", "synonyms": "pleural cavity|pleural space|hemithorax"},

    # ── Abdominal organs ──────────────────────────────────────────────────────
    {"display": "Liver", "specialty": "gastroenterology", "synonyms": "liver|hepatic|hepar"},
    {"display": "Right lobe of liver", "specialty": "gastroenterology", "synonyms": "right hepatic lobe|right lobe liver"},
    {"display": "Left lobe of liver", "specialty": "gastroenterology", "synonyms": "left hepatic lobe|left lobe liver"},
    {"display": "Gallbladder", "specialty": "gastroenterology", "synonyms": "gallbladder|gall bladder|biliary"},
    {"display": "Bile duct (Common bile duct)", "specialty": "gastroenterology", "synonyms": "CBD|common bile duct|bile duct|choledochus"},
    {"display": "Spleen", "specialty": "general_medicine", "synonyms": "spleen|splenic"},
    {"display": "Pancreas", "specialty": "gastroenterology", "synonyms": "pancreas|pancreatic|head of pancreas|tail of pancreas"},
    {"display": "Stomach", "specialty": "gastroenterology", "synonyms": "stomach|gastric|gaster"},
    {"display": "Duodenum", "specialty": "gastroenterology", "synonyms": "duodenum|duodenal|first part duodenum"},
    {"display": "Small intestine (Jejunum/Ileum)", "specialty": "gastroenterology", "synonyms": "small intestine|jejunum|ileum|small bowel"},
    {"display": "Appendix", "specialty": "gastroenterology", "synonyms": "appendix|vermiform appendix"},
    {"display": "Caecum", "specialty": "gastroenterology", "synonyms": "caecum|cecum|ileocaecal"},
    {"display": "Ascending colon", "specialty": "gastroenterology", "synonyms": "ascending colon|right colon"},
    {"display": "Transverse colon", "specialty": "gastroenterology", "synonyms": "transverse colon"},
    {"display": "Descending colon", "specialty": "gastroenterology", "synonyms": "descending colon|left colon"},
    {"display": "Sigmoid colon", "specialty": "gastroenterology", "synonyms": "sigmoid colon|sigmoid|pelvic colon"},
    {"display": "Rectum", "specialty": "gastroenterology", "synonyms": "rectum|rectal"},
    {"display": "Anus", "specialty": "gastroenterology", "synonyms": "anus|anal canal|anal sphincter"},
    {"display": "Oesophagus", "specialty": "gastroenterology", "synonyms": "oesophagus|esophagus|gullet|food pipe"},

    # ── Kidneys / Urinary ─────────────────────────────────────────────────────
    {"display": "Right kidney", "specialty": "nephrology", "synonyms": "right kidney|right renal"},
    {"display": "Left kidney", "specialty": "nephrology", "synonyms": "left kidney|left renal"},
    {"display": "Renal pelvis", "specialty": "nephrology", "synonyms": "renal pelvis|pelvicalyceal system|PCS"},
    {"display": "Ureter (right)", "specialty": "urology", "synonyms": "right ureter|ureteral"},
    {"display": "Ureter (left)", "specialty": "urology", "synonyms": "left ureter|ureteral"},
    {"display": "Urinary bladder", "specialty": "urology", "synonyms": "bladder|urinary bladder|vesical"},
    {"display": "Urethra", "specialty": "urology", "synonyms": "urethra|urethral"},
    {"display": "Prostate", "specialty": "urology", "synonyms": "prostate|prostate gland|prostatic"},
    {"display": "Testis", "specialty": "urology", "synonyms": "testis|testicle|testes|orchis"},
    {"display": "Epididymis", "specialty": "urology", "synonyms": "epididymis|epididymal"},
    {"display": "Scrotum", "specialty": "urology", "synonyms": "scrotum|scrotal sac"},
    {"display": "Penis", "specialty": "urology", "synonyms": "penis|penile|phallus"},

    # ── Female reproductive ───────────────────────────────────────────────────
    {"display": "Uterus", "specialty": "obstetrics/gynecology", "synonyms": "uterus|womb|uterine|fundus"},
    {"display": "Cervix", "specialty": "obstetrics/gynecology", "synonyms": "cervix|cervical os|uterine cervix"},
    {"display": "Right ovary", "specialty": "obstetrics/gynecology", "synonyms": "right ovary|right ovarian"},
    {"display": "Left ovary", "specialty": "obstetrics/gynecology", "synonyms": "left ovary|left ovarian"},
    {"display": "Fallopian tube (right)", "specialty": "obstetrics/gynecology", "synonyms": "right fallopian tube|right oviduct|right salpinx"},
    {"display": "Fallopian tube (left)", "specialty": "obstetrics/gynecology", "synonyms": "left fallopian tube|left oviduct|left salpinx"},
    {"display": "Vagina", "specialty": "obstetrics/gynecology", "synonyms": "vagina|vaginal canal|birth canal"},
    {"display": "Vulva", "specialty": "obstetrics/gynecology", "synonyms": "vulva|external genitalia female|labia"},
    {"display": "Endometrium", "specialty": "obstetrics/gynecology", "synonyms": "endometrium|uterine lining|endometrial"},

    # ── Endocrine glands ──────────────────────────────────────────────────────
    {"display": "Pituitary gland", "specialty": "endocrinology", "synonyms": "pituitary|hypophysis|master gland|sella turcica"},
    {"display": "Thyroid gland", "specialty": "endocrinology", "synonyms": "thyroid|thyroid gland|thyroidal"},
    {"display": "Parathyroid glands", "specialty": "endocrinology", "synonyms": "parathyroid|PTH gland"},
    {"display": "Right adrenal gland", "specialty": "endocrinology", "synonyms": "right adrenal|right suprarenal|right adrenal gland"},
    {"display": "Left adrenal gland", "specialty": "endocrinology", "synonyms": "left adrenal|left suprarenal|left adrenal gland"},
    {"display": "Pancreatic islets (Islets of Langerhans)", "specialty": "endocrinology", "synonyms": "islets of Langerhans|beta cells|pancreatic endocrine|insulin-secreting"},
    {"display": "Pineal gland", "specialty": "endocrinology", "synonyms": "pineal gland|pineal body|epiphysis cerebri"},
    {"display": "Gonads (Ovaries/Testes)", "specialty": "endocrinology", "synonyms": "gonads|sex glands|ovaries testes"},

    # ── Lymphatics ────────────────────────────────────────────────────────────
    {"display": "Cervical lymph nodes", "specialty": "general_medicine", "synonyms": "cervical nodes|neck lymph nodes|jugulodigastric"},
    {"display": "Axillary lymph nodes", "specialty": "general_medicine", "synonyms": "axillary nodes|armpit lymph nodes"},
    {"display": "Inguinal lymph nodes", "specialty": "general_medicine", "synonyms": "inguinal nodes|groin lymph nodes"},
    {"display": "Mediastinal lymph nodes", "specialty": "pulmonology", "synonyms": "mediastinal nodes|hilar nodes|paratracheal"},
    {"display": "Mesenteric lymph nodes", "specialty": "gastroenterology", "synonyms": "mesenteric nodes|abdominal lymph nodes"},
    {"display": "Thymus", "specialty": "general_medicine", "synonyms": "thymus|thymic|anterior mediastinum gland"},

    # ── Key muscles ───────────────────────────────────────────────────────────
    {"display": "Rotator cuff", "specialty": "orthopedics", "synonyms": "rotator cuff|supraspinatus|infraspinatus|subscapularis|teres minor"},
    {"display": "Quadriceps femoris", "specialty": "orthopedics", "synonyms": "quadriceps|quads|rectus femoris|vastus"},
    {"display": "Hamstrings", "specialty": "orthopedics", "synonyms": "hamstrings|biceps femoris|semimembranosus|semitendinosus"},
    {"display": "Gastrocnemius / Soleus (Calf)", "specialty": "orthopedics", "synonyms": "calf muscle|gastrocnemius|soleus"},
    {"display": "Iliotibial band (IT band)", "specialty": "orthopedics", "synonyms": "IT band|iliotibial band|iliotibial tract"},
    {"display": "Achilles tendon", "specialty": "orthopedics", "synonyms": "achilles tendon|calcaneal tendon|tendo calcaneus"},
    {"display": "Patellar tendon / ligament", "specialty": "orthopedics", "synonyms": "patellar tendon|patellar ligament|infrapatellar"},
    {"display": "Anterior cruciate ligament (ACL)", "specialty": "orthopedics", "synonyms": "ACL|anterior cruciate ligament"},
    {"display": "Posterior cruciate ligament (PCL)", "specialty": "orthopedics", "synonyms": "PCL|posterior cruciate ligament"},
    {"display": "Medial collateral ligament (MCL)", "specialty": "orthopedics", "synonyms": "MCL|medial collateral ligament"},
    {"display": "Lateral collateral ligament (LCL)", "specialty": "orthopedics", "synonyms": "LCL|lateral collateral ligament"},
    {"display": "Meniscus (medial)", "specialty": "orthopedics", "synonyms": "medial meniscus|medial cartilage knee"},
    {"display": "Meniscus (lateral)", "specialty": "orthopedics", "synonyms": "lateral meniscus|lateral cartilage knee"},
    {"display": "Psoas muscle", "specialty": "orthopedics", "synonyms": "psoas|iliopsoas|hip flexor"},
    {"display": "Trapezius muscle", "specialty": "orthopedics", "synonyms": "trapezius|upper trapezius|trap muscle"},
    {"display": "Erector spinae", "specialty": "orthopedics", "synonyms": "erector spinae|paraspinal muscles|back muscles"},

    # ── Skin / Dermatomes ─────────────────────────────────────────────────────
    {"display": "Dermatome C4", "specialty": "neurology", "synonyms": "C4 dermatome|shoulder cape|supraclavicular"},
    {"display": "Dermatome C5", "specialty": "neurology", "synonyms": "C5 dermatome|lateral arm"},
    {"display": "Dermatome C6", "specialty": "neurology", "synonyms": "C6 dermatome|thumb side|lateral forearm"},
    {"display": "Dermatome C7", "specialty": "neurology", "synonyms": "C7 dermatome|middle finger"},
    {"display": "Dermatome C8", "specialty": "neurology", "synonyms": "C8 dermatome|little finger side|medial forearm"},
    {"display": "Dermatome T4", "specialty": "neurology", "synonyms": "T4 dermatome|nipple level"},
    {"display": "Dermatome T10", "specialty": "neurology", "synonyms": "T10 dermatome|umbilicus level"},
    {"display": "Dermatome L1", "specialty": "neurology", "synonyms": "L1 dermatome|groin region"},
    {"display": "Dermatome L2-L3", "specialty": "neurology", "synonyms": "L2 L3 dermatome|anterior thigh"},
    {"display": "Dermatome L4", "specialty": "neurology", "synonyms": "L4 dermatome|medial leg|big toe"},
    {"display": "Dermatome L5", "specialty": "neurology", "synonyms": "L5 dermatome|lateral leg|dorsum foot"},
    {"display": "Dermatome S1", "specialty": "neurology", "synonyms": "S1 dermatome|lateral foot|heel"},
    {"display": "Dermatome S2-S4", "specialty": "neurology", "synonyms": "S2 S3 S4 dermatome|saddle area|perineum"},
]
