"""
Disease-specific patient counselling tips, indexed by ICD-10 prefix or condition name.
Used by the Encounter page to auto-suggest counselling points when a diagnosis is tagged.

Each entry: { icd10_prefix, condition, tips: [str, ...] }
Tips are short, patient-facing sentences.
"""

DISEASE_COUNSELLING = [

    # ── Diabetes & Metabolic ─────────────────────────────────────────────────────
    {
        "icd10_prefix": "E11",
        "condition": "Type 2 Diabetes Mellitus",
        "tips": [
            "Check your blood sugar at home as advised — record and bring readings to every visit",
            "Eat small, frequent meals; avoid white rice, maida, sugary drinks and sweets",
            "Walk for at least 30–45 minutes every day; any physical activity helps",
            "Never skip meals when on insulin or sulphonylurea medicines",
            "Check your feet daily for cuts, blisters, or sores — report immediately",
            "Keep your HbA1c below 7% — recheck every 3 months",
            "Quit smoking and limit alcohol completely",
            "Carry glucose tablets or sweet biscuits in case of hypoglycaemia (giddiness, sweating)",
            "Get your eyes, kidneys, and feet checked every year",
            "Wear well-fitting footwear at all times — never walk barefoot",
            "Take medicines at the same time every day; do not stop without asking your doctor",
            "Stay hydrated — drink 8–10 glasses of water daily",
        ],
    },
    {
        "icd10_prefix": "E10",
        "condition": "Type 1 Diabetes Mellitus",
        "tips": [
            "Never miss insulin doses — this is life-sustaining treatment",
            "Rotate injection sites to prevent lipodystrophy",
            "Monitor blood sugar before meals, 2 hours after, and at bedtime",
            "Keep a hypoglycaemia rescue kit (glucose tablets, glucagon if prescribed) always available",
            "Inform school/workplace about your condition and what to do if you collapse",
            "Adjust insulin dose during illness, exercise, and travel as advised by your doctor",
            "Wear a medical ID bracelet stating you have Type 1 Diabetes",
            "Annual eye, kidney, and foot check-ups are essential",
        ],
    },
    {
        "icd10_prefix": "E78",
        "condition": "Dyslipidaemia / High Cholesterol",
        "tips": [
            "Avoid fried foods, ghee, vanaspati, and full-fat dairy",
            "Eat more fruits, vegetables, oats, beans, and fish",
            "Exercise for at least 30 minutes most days of the week",
            "Take statin medicines at night as prescribed — do not stop without advice",
            "Report muscle pain or weakness to your doctor immediately if on statins",
            "Avoid alcohol and smoking — both worsen cholesterol levels",
            "Recheck your lipid profile after 3 months of treatment",
        ],
    },
    {
        "icd10_prefix": "E66",
        "condition": "Obesity",
        "tips": [
            "Aim to lose 0.5–1 kg per week — crash diets are harmful",
            "Eat smaller portions; use a smaller plate",
            "Avoid sugary drinks, packaged snacks, and fast food",
            "Walk 10,000 steps daily or 45 minutes brisk walking",
            "Sleep 7–8 hours a night — sleep deprivation increases weight",
            "Keep a food diary to track what you eat",
            "Weigh yourself weekly at the same time of day",
        ],
    },
    {
        "icd10_prefix": "E04",
        "condition": "Hypothyroidism",
        "tips": [
            "Take levothyroxine on an empty stomach, 30–60 minutes before breakfast",
            "Do not take with calcium, iron, antacids, or milk — gap of at least 4 hours",
            "Take medicine at the same time every day",
            "Recheck TSH after 6–8 weeks of any dose change",
            "Annual TSH monitoring once on stable dose",
            "Symptoms improve slowly over weeks — do not stop medicine early",
            "Inform your doctor if you become pregnant — dose needs adjustment",
        ],
    },
    {
        "icd10_prefix": "E05",
        "condition": "Hyperthyroidism / Graves' Disease",
        "tips": [
            "Take antithyroid medicines (carbimazole/methimazole) as prescribed without skipping",
            "Report sore throat, fever, or mouth ulcers immediately — rare but serious side effect",
            "Avoid iodine-rich foods (excess seaweed, iodised supplements) during treatment",
            "Wear sunglasses if your eyes are affected (Graves' ophthalmopathy)",
            "Recheck thyroid function every 4–6 weeks initially",
            "Radioiodine or surgery may be discussed if medicines don't control it",
            "Avoid caffeine and smoking — both worsen thyroid disease",
        ],
    },
    {
        "icd10_prefix": "E83",
        "condition": "Vitamin D Deficiency",
        "tips": [
            "Get 15–20 minutes of direct sunlight exposure on arms and legs daily, preferably before 10 AM",
            "Take prescribed Vitamin D supplements with a fatty meal for better absorption",
            "Eat more eggs, fatty fish (salmon, mackerel), and fortified foods",
            "Recheck Vitamin D levels after 3 months of supplementation",
            "Do not self-supplement with high doses — Vitamin D toxicity is real",
        ],
    },
    {
        "icd10_prefix": "D50",
        "condition": "Iron Deficiency Anaemia",
        "tips": [
            "Take iron tablets on an empty stomach or with Vitamin C (lemon juice, orange juice) for better absorption",
            "Avoid taking iron with tea, coffee, milk, or antacids — they block absorption",
            "Dark-green leafy vegetables, jaggery, sesame seeds, and red meat are good iron sources",
            "Stools may turn black or green while on iron — this is normal",
            "Nausea or stomach upset — take with a small meal if unbearable",
            "Continue iron for 3–6 months even after blood counts improve to replenish stores",
            "Recheck haemoglobin after 4 weeks of treatment",
        ],
    },

    # ── Cardiovascular ───────────────────────────────────────────────────────────
    {
        "icd10_prefix": "I10",
        "condition": "Hypertension",
        "tips": [
            "Take blood pressure medicines every day at the same time — never skip",
            "Reduce salt intake: avoid pickles, papads, processed foods, namkeen, and extra salt at table",
            "Walk 30 minutes every day — exercise lowers blood pressure naturally",
            "Quit smoking and avoid alcohol",
            "Monitor BP at home regularly and bring the record to every visit",
            "Target BP: below 130/80 mmHg (your doctor will set your personal goal)",
            "Manage stress — try yoga, meditation, or deep breathing",
            "Lose excess weight — even 5 kg loss can significantly reduce BP",
            "Do not stop medicines when BP feels normal — it means the medicine is working",
            "Emergency: go to hospital immediately for BP above 180/110 or with headache/chest pain",
        ],
    },
    {
        "icd10_prefix": "I25",
        "condition": "Coronary Artery Disease / Ischaemic Heart Disease",
        "tips": [
            "Take all heart medicines every day without fail — aspirin, statin, beta-blocker",
            "Carry GTN spray or tablet; use if chest pain occurs and call for help",
            "Quit smoking immediately and completely — it is the single biggest risk",
            "Follow a heart-healthy diet: less oil, no trans-fats, more vegetables and fish",
            "Walk daily as advised; avoid sudden strenuous activity",
            "Report any chest pain, breathlessness, or palpitations without delay",
            "Attend all follow-up appointments and cardiac rehabilitation sessions",
            "Know the warning signs of heart attack: chest tightness, left arm pain, jaw pain, sweating",
            "Keep your cholesterol, blood pressure, and blood sugar controlled",
        ],
    },
    {
        "icd10_prefix": "I50",
        "condition": "Heart Failure",
        "tips": [
            "Weigh yourself every morning — report a gain of more than 1 kg in a day or 2 kg in a week",
            "Restrict fluid intake as advised by your doctor (usually 1.5–2 litres/day including food)",
            "Reduce salt intake strictly — avoid all processed, packaged, and restaurant food",
            "Take diuretics (water tablets) in the morning to avoid frequent night urination",
            "Elevate your head and upper body slightly when sleeping if breathless",
            "Never stop heart failure medicines without consulting your doctor",
            "Report increasing breathlessness, leg swelling, or palpitations immediately",
            "Avoid NSAIDs (ibuprofen, diclofenac) — they worsen heart failure",
            "Get annual flu and pneumococcal vaccines",
        ],
    },
    {
        "icd10_prefix": "I48",
        "condition": "Atrial Fibrillation",
        "tips": [
            "Take blood thinners (warfarin or newer anticoagulants) as prescribed every day",
            "If on warfarin, get INR checked regularly — keep it in the range 2–3",
            "Report unusual bleeding, bruising, or blood in urine/stools immediately",
            "Avoid excessive alcohol — it can trigger AF episodes",
            "Keep your heart rate controlled; report if pulse is very fast or irregular",
            "Do not take herbal remedies or supplements without consulting your doctor",
            "Inform any doctor or dentist you are on blood thinners before procedures",
        ],
    },
    {
        "icd10_prefix": "I63",
        "condition": "Stroke / Cerebral Infarction",
        "tips": [
            "Take antiplatelet (aspirin/clopidogrel) or anticoagulant medicines every day without fail",
            "Attend physiotherapy and speech therapy sessions consistently",
            "Control blood pressure, cholesterol, and diabetes strictly",
            "Quit smoking and avoid alcohol completely",
            "FAST signs of another stroke: Face drooping, Arm weakness, Speech difficulty, Time to call emergency",
            "Report any new weakness, numbness, vision changes, or severe headache immediately",
            "Caregiver support: assist with exercises, medicines, and safe environment at home",
        ],
    },
    {
        "icd10_prefix": "I82",
        "condition": "Deep Vein Thrombosis (DVT)",
        "tips": [
            "Take blood thinners for the full prescribed duration — do not stop early",
            "Keep the affected leg elevated when resting",
            "Do ankle pump exercises: flex and extend feet 10 times every hour if sitting for long",
            "Avoid long periods of immobility — walk around every 1–2 hours on long journeys",
            "Wear compression stockings as advised",
            "Inform your doctor before any surgery or invasive procedure",
            "Report sudden breathlessness or chest pain — could be pulmonary embolism (emergency)",
        ],
    },

    # ── Respiratory ──────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "J45",
        "condition": "Bronchial Asthma",
        "tips": [
            "Use your reliever inhaler (blue/salbutamol) when you feel breathless or wheezy",
            "Use your preventer inhaler (brown/budesonide) every day even when you feel fine",
            "Always rinse your mouth and gargle after using steroid inhalers",
            "Learn correct inhaler technique — ask your doctor or nurse to check",
            "Identify and avoid your triggers: dust, pollen, smoke, pets, cold air, strong smells",
            "Keep a peak flow diary if advised",
            "Carry your reliever inhaler at all times",
            "Do not smoke and avoid second-hand smoke",
            "Get flu vaccine every year and pneumococcal vaccine",
            "Go to hospital immediately if reliever inhaler gives no relief",
        ],
    },
    {
        "icd10_prefix": "J44",
        "condition": "COPD (Chronic Obstructive Pulmonary Disease)",
        "tips": [
            "Quit smoking immediately — it is the most important step",
            "Use inhalers correctly and consistently — ask for a technique check",
            "Stay active within your limits — pulmonary rehabilitation is very beneficial",
            "Eat small, frequent meals — large meals can cause breathlessness",
            "Get flu vaccine every year and pneumococcal vaccine every 5 years",
            "Avoid cold air, dusty environments, and indoor smoke (cooking fires)",
            "Report increased breathlessness, change in sputum colour, or fever immediately",
            "Have an action plan ready for exacerbations",
        ],
    },
    {
        "icd10_prefix": "A15",
        "condition": "Pulmonary Tuberculosis",
        "tips": [
            "Take ALL TB medicines every single day for the FULL course (minimum 6 months) — stopping early causes drug resistance",
            "TB medicines are best taken on an empty stomach or with a light meal",
            "Cover your mouth when coughing or sneezing; use a separate room and good ventilation initially",
            "Report yellow eyes or skin, dark urine, or severe stomach pain — possible liver side effect",
            "Report any vision changes if on ethambutol",
            "Avoid alcohol completely during treatment — it seriously damages your liver",
            "Family members should be tested and vaccinated (BCG for children)",
            "Attend all DOTS (Directly Observed Treatment) sessions",
            "You are not contagious after 2 weeks of proper treatment",
            "Balanced diet high in protein helps recovery",
        ],
    },
    {
        "icd10_prefix": "J18",
        "condition": "Pneumonia",
        "tips": [
            "Complete the full antibiotic course even if you feel better sooner",
            "Rest as much as possible — your body needs energy to fight infection",
            "Drink plenty of warm fluids — helps thin mucus",
            "Take paracetamol for fever as prescribed",
            "Return to doctor immediately if breathlessness worsens or fever doesn't improve in 48–72 hours",
            "Get pneumococcal vaccine after recovery to prevent recurrence",
            "Avoid smoking and alcohol during recovery",
        ],
    },

    # ── Gastrointestinal ─────────────────────────────────────────────────────────
    {
        "icd10_prefix": "K21",
        "condition": "GERD / Acid Reflux",
        "tips": [
            "Eat smaller, more frequent meals — avoid eating large meals",
            "Do not lie down within 3 hours of eating",
            "Elevate the head end of your bed by 15–20 cm (use a wedge pillow)",
            "Avoid spicy, oily, and acidic foods; also chocolate, coffee, mint, and carbonated drinks",
            "Lose weight if overweight — it significantly reduces reflux",
            "Avoid tight-fitting clothes, especially around the waist",
            "Quit smoking and avoid alcohol",
            "Take antacid or PPI medicines 30 minutes before meals as prescribed",
        ],
    },
    {
        "icd10_prefix": "K57",
        "condition": "Irritable Bowel Syndrome (IBS)",
        "tips": [
            "Identify and avoid your personal food triggers — keep a food and symptom diary",
            "Eat regular meals at fixed times; do not skip meals",
            "Increase dietary fibre gradually (vegetables, fruits, oats) if constipation-predominant",
            "Avoid gas-producing foods (cabbage, beans, carbonated drinks) if bloating is a problem",
            "Drink 8–10 glasses of water daily",
            "Manage stress — stress is a major IBS trigger; try yoga or mindfulness",
            "Exercise regularly — it improves gut motility",
            "Probiotics may help — ask your doctor",
        ],
    },
    {
        "icd10_prefix": "K80",
        "condition": "Gallstones / Cholelithiasis",
        "tips": [
            "Avoid fatty, fried, and greasy foods — they trigger gallbladder pain",
            "Eat small, low-fat meals throughout the day",
            "Maintain a healthy weight — obesity increases stone risk",
            "Do not skip meals or fast for long periods — triggers bile concentration",
            "Report severe upper right abdominal pain, fever, or yellow skin immediately",
            "Follow up for planned surgery (cholecystectomy) if advised",
        ],
    },
    {
        "icd10_prefix": "K70",
        "condition": "Alcoholic Liver Disease / Cirrhosis",
        "tips": [
            "Stop alcohol completely and permanently — even small amounts will worsen your liver",
            "Eat a high-protein, nutritious diet — liver disease causes muscle wasting",
            "Avoid all NSAIDs (ibuprofen, diclofenac) and paracetamol in excess — dangerous with liver disease",
            "Weigh yourself daily — report sudden weight gain (fluid accumulation)",
            "Salt restriction is important if you have ascites (fluid in abdomen)",
            "Get hepatitis A and B vaccines if not already immune",
            "Attend follow-up appointments; liver cancer screening (ultrasound) every 6 months",
            "Report confusion, unusual behaviour, or sleep reversal — signs of hepatic encephalopathy",
        ],
    },
    {
        "icd10_prefix": "K74",
        "condition": "Liver Cirrhosis",
        "tips": [
            "Stop alcohol completely",
            "Take your medicines (diuretics, lactulose, beta-blockers) consistently",
            "Low-salt diet strictly — reduce to less than 2 grams of sodium per day",
            "Avoid raw or undercooked shellfish and street food — infections are very dangerous",
            "Vaccinate against hepatitis A, hepatitis B, flu, and pneumococcus",
            "Weigh daily; report gain of more than 1 kg/day",
            "Do not take any herbal or over-the-counter medicines without consulting your doctor",
            "Regular surveillance ultrasound and AFP for liver cancer (every 6 months)",
            "Inform your doctor of any blood in vomit or black tarry stools — emergency",
        ],
    },

    # ── Renal ────────────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "N18",
        "condition": "Chronic Kidney Disease (CKD)",
        "tips": [
            "Strictly control blood pressure and blood sugar — the two biggest causes of CKD",
            "Low-protein diet as advised by your nephrologist and dietitian",
            "Restrict potassium-rich foods (bananas, oranges, potatoes, tomatoes) if potassium is high",
            "Restrict phosphorus (dairy, nuts, colas) to protect your bones and heart",
            "Fluid restriction as advised — do not drink more than the prescribed amount",
            "Avoid NSAIDs (ibuprofen, diclofenac, naproxen) completely — they worsen kidney function",
            "Never skip dialysis sessions if on dialysis",
            "Take phosphate binders with meals as prescribed",
            "Get hepatitis B vaccine if not already immune",
            "Inform every doctor, dentist, or pharmacist that you have kidney disease before any treatment",
        ],
    },
    {
        "icd10_prefix": "N20",
        "condition": "Kidney Stones (Urolithiasis)",
        "tips": [
            "Drink at least 3–4 litres of water daily — most important prevention measure",
            "Reduce salt in diet — excess salt increases calcium in urine",
            "Reduce animal protein (meat, fish, eggs) if uric acid stones",
            "Avoid spinach, tomatoes, nuts, and chocolate if oxalate stones",
            "Strain urine during a stone episode and bring the stone for analysis",
            "Take prescribed medications (citrate, allopurinol) consistently",
            "Lemon juice in water helps — citrate inhibits stone formation",
            "Return immediately for severe flank pain, fever, or inability to pass urine",
        ],
    },

    # ── Neurological ─────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "G40",
        "condition": "Epilepsy / Seizures",
        "tips": [
            "Take anti-epileptic medicines every single day at the same time — never miss a dose",
            "Do not drive until seizure-free for the period specified by your doctor and law",
            "Avoid swimming alone, heights, or operating heavy machinery",
            "Get enough sleep — sleep deprivation is a major seizure trigger",
            "Avoid alcohol and recreational drugs",
            "Tell family members what to do during a seizure: time it, turn sideways, keep safe, call ambulance if over 5 minutes",
            "Do not put anything in the mouth during a seizure",
            "Carry a seizure first aid card or medical ID",
            "Report any new side effects: rash, double vision, dizziness, mood changes",
            "Women of childbearing age: discuss contraception and pregnancy planning — some AEDs are teratogenic",
        ],
    },
    {
        "icd10_prefix": "G43",
        "condition": "Migraine",
        "tips": [
            "Identify and avoid your triggers: stress, sleep changes, skipped meals, bright lights, strong smells",
            "Maintain regular sleep and meal times — consistency prevents attacks",
            "Take acute medicines (triptan/NSAID) at the very first sign of migraine — do not wait",
            "Avoid using pain medicines more than 2–3 days a week — overuse causes rebound headache",
            "Stay hydrated — dehydration is a common trigger",
            "Apply cold pack to head or neck during an attack; rest in a dark, quiet room",
            "If prescribed preventive medicine, take it daily even when headache-free",
            "Keep a headache diary to track frequency, triggers, and response to treatment",
        ],
    },
    {
        "icd10_prefix": "G20",
        "condition": "Parkinson's Disease",
        "tips": [
            "Take levodopa medicines at strictly fixed times — timing matters for symptom control",
            "Take levodopa 30 minutes before meals for best absorption (protein in food reduces absorption)",
            "Exercise is very important — walking, cycling, physiotherapy help maintain mobility",
            "Fall prevention: remove rugs, install grab rails, use non-slip footwear",
            "Speech therapy helps with swallowing difficulties and soft voice",
            "Occupational therapy helps adapt home for independence",
            "Constipation is common — increase fibre, water, and exercise",
            "Attend regular neurologist review; medication adjustments are frequent",
            "Support groups and carer education are invaluable",
        ],
    },
    {
        "icd10_prefix": "F00",
        "condition": "Dementia / Alzheimer's Disease",
        "tips": [
            "Keep a consistent daily routine — predictability reduces anxiety",
            "Label rooms, drawers, and photos to aid orientation",
            "Remove fall hazards: loose rugs, poor lighting, clutter",
            "Supervise stove, medications, and driving — safety is the priority",
            "Encourage engagement with familiar activities and social contact",
            "Speak slowly, clearly, and in simple sentences",
            "Carer self-care is essential — seek respite support when needed",
            "Legal and financial planning should be arranged while the person has capacity",
            "Report sudden worsening (delirium) — always investigate for a cause (infection, medication)",
        ],
    },

    # ── Mental Health ────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "F32",
        "condition": "Depression",
        "tips": [
            "Take antidepressant medicines daily — they take 2–4 weeks to show full effect; do not stop early",
            "Do not stop medicines without consulting your doctor — abrupt stopping causes withdrawal",
            "Talk therapy (counselling/CBT) alongside medicines gives the best results",
            "Try to maintain regular sleep, wake times, and meal times",
            "Daily physical activity (even a short walk) significantly improves mood",
            "Reach out to trusted friends or family — isolation worsens depression",
            "Avoid alcohol — it is a depressant and worsens symptoms",
            "If you have thoughts of self-harm, call a helpline (iCall: 9152987821) or go to hospital",
        ],
    },
    {
        "icd10_prefix": "F20",
        "condition": "Schizophrenia",
        "tips": [
            "Take antipsychotic medicines every day — stopping abruptly causes relapse",
            "Attend regular psychiatry follow-ups even when feeling well",
            "Family involvement and education about the illness is essential",
            "Structured daily routine reduces stress and prevents relapse",
            "Avoid cannabis, alcohol, and other substances — they trigger relapses",
            "Report unusual movements (stiffness, tremors) — possible side effects of medicines",
            "Community mental health support and social skill training help significantly",
        ],
    },
    {
        "icd10_prefix": "F41",
        "condition": "Anxiety Disorder",
        "tips": [
            "Practice deep breathing or diaphragmatic breathing during an anxiety attack",
            "Progressive muscle relaxation or mindfulness helps reduce baseline anxiety",
            "Limit caffeine (tea, coffee, energy drinks) — it worsens anxiety",
            "Regular exercise is one of the best anti-anxiety treatments",
            "Cognitive Behavioural Therapy (CBT) is highly effective — ask for a referral",
            "Do not use benzodiazepines (diazepam, alprazolam) for more than 2–4 weeks — risk of dependence",
            "Reduce screen time and news consumption if it increases anxiety",
            "Maintain regular sleep pattern — sleep deprivation greatly worsens anxiety",
        ],
    },

    # ── Infectious Disease (India-specific) ──────────────────────────────────────
    {
        "icd10_prefix": "A90",
        "condition": "Dengue Fever",
        "tips": [
            "Rest completely and drink plenty of fluids — oral rehydration, coconut water, fruit juices",
            "Take only paracetamol for fever — NO aspirin, ibuprofen, or diclofenac (increase bleeding risk)",
            "Return to hospital immediately: severe abdominal pain, persistent vomiting, bleeding from gums or nose, difficulty breathing",
            "Platelet count below 20,000 usually needs hospitalisation — do not wait",
            "Mosquito prevention for family members: repellent, full-sleeve clothes, mosquito nets",
            "Eliminate standing water around home — dengue mosquito breeds in clean stagnant water",
        ],
    },
    {
        "icd10_prefix": "B50",
        "condition": "Malaria",
        "tips": [
            "Take ALL antimalarial medicines for the complete course — incomplete courses cause resistance",
            "Report back immediately if fever worsens or new symptoms develop",
            "Primaquine (for P. vivax/P. ovale): Get G6PD test before taking — it causes haemolysis in G6PD deficiency",
            "Sleep under insecticide-treated mosquito nets",
            "Use mosquito repellent on exposed skin, especially at dusk and dawn",
            "Wear full-sleeve clothing in the evening",
            "Drain, cover, or change standing water around your home weekly",
            "Recheck malaria smear after 48 hours if no improvement",
        ],
    },
    {
        "icd10_prefix": "A01",
        "condition": "Typhoid Fever",
        "tips": [
            "Take all prescribed antibiotic doses for the full course (usually 7–14 days)",
            "Drink only boiled or bottled water — typhoid spreads through contaminated water",
            "Eat freshly cooked, home-prepared food only; avoid street food and raw salads",
            "Rest and eat small, soft, easily digestible meals",
            "Report severe abdominal pain immediately — risk of intestinal perforation",
            "Typhoid vaccine recommended for family members and contacts",
            "Strict hand hygiene — wash hands with soap after toilet and before eating",
        ],
    },
    {
        "icd10_prefix": "B16",
        "condition": "Hepatitis B",
        "tips": [
            "All household contacts and sexual partners should be tested and vaccinated",
            "Do not share razors, toothbrushes, nail clippers, or needles",
            "Use condoms consistently to prevent sexual transmission",
            "Avoid alcohol completely — it accelerates liver damage",
            "Take antiviral medicines (tenofovir/entecavir) consistently if prescribed; never stop without medical advice",
            "Liver cancer screening (ultrasound + AFP) every 6 months if on treatment",
            "Inform healthcare workers and dentists about your Hepatitis B status",
        ],
    },
    {
        "icd10_prefix": "B20",
        "condition": "HIV / AIDS",
        "tips": [
            "Take antiretroviral therapy (ART) medicines every day at exactly the same time — missing doses causes resistance",
            "ART will control the virus and allow you to live a near-normal life",
            "Never stop or change ART without consulting your doctor",
            "Use condoms in every sexual encounter to prevent transmission",
            "Do not share needles, syringes, or blood-contaminated items",
            "Pregnant women: ART prevents transmission to the baby — do not stop",
            "Report any new symptoms: fever, weight loss, skin rashes, oral thrush",
            "Regular CD4 count and viral load monitoring as advised",
            "Maintain good nutrition; avoid raw/undercooked food and unpasteurised dairy",
            "Counselling and support groups help significantly with adherence and mental health",
        ],
    },
    {
        "icd10_prefix": "A06",
        "condition": "Amoebiasis",
        "tips": [
            "Complete the full course of metronidazole and luminal agent (diloxanide)",
            "Drink only boiled or filtered water",
            "Wash hands with soap thoroughly before eating and after using toilet",
            "Avoid raw salads and street food until recovered",
            "Family members with symptoms should also be evaluated",
        ],
    },

    # ── Musculoskeletal ──────────────────────────────────────────────────────────
    {
        "icd10_prefix": "M05",
        "condition": "Rheumatoid Arthritis",
        "tips": [
            "Take disease-modifying medicines (methotrexate, hydroxychloroquine) consistently — they take months to work fully",
            "Never stop DMARD medicines without consulting your rheumatologist",
            "Folic acid supplement reduces methotrexate side effects — take as prescribed",
            "Monthly blood tests (CBC, LFT) needed during methotrexate therapy",
            "Apply warm packs to stiff joints in the morning; cold packs for acute swelling",
            "Gentle range-of-motion exercises daily — physiotherapy is essential",
            "Rest during severe flares; stay active when stable",
            "Protect your joints: use assistive devices, avoid tight gripping",
            "Report fever, cough, or breathlessness on methotrexate immediately — possible infection",
            "Annual eye check if on hydroxychloroquine (rare retinal toxicity)",
        ],
    },
    {
        "icd10_prefix": "M10",
        "condition": "Gout",
        "tips": [
            "Drink 2–3 litres of water daily to help flush uric acid",
            "Avoid red meat, organ meats (liver, kidney), shellfish, and beer — high in purines",
            "Avoid fructose-rich drinks (sweet fizzy drinks, fruit juices)",
            "Take allopurinol daily as prescribed to keep uric acid below 6 mg/dL — continue even when pain-free",
            "Do not start allopurinol during an acute attack — wait 2–4 weeks after the flare settles",
            "Take colchicine or NSAID at the first sign of an attack",
            "Lose weight gradually if overweight — crash dieting triggers gout",
            "Limit alcohol; beer is the worst offender",
        ],
    },
    {
        "icd10_prefix": "M54",
        "condition": "Low Back Pain",
        "tips": [
            "Stay as active as possible — bed rest for more than 1–2 days is harmful",
            "Physiotherapy exercises are the most effective long-term treatment",
            "Maintain correct posture when sitting, standing, and lifting",
            "Lift objects by bending your knees, not your back",
            "A firm mattress that supports the spine is better than a soft one",
            "Apply heat (warm water bottle) or cold pack for pain relief",
            "Maintain a healthy weight — excess weight stresses the spine",
            "Return immediately for leg weakness, bladder or bowel problems — possible emergency",
        ],
    },
    {
        "icd10_prefix": "M17",
        "condition": "Knee Osteoarthritis",
        "tips": [
            "Lose weight — every 1 kg lost reduces knee load by 4 kg",
            "Quadriceps strengthening exercises reduce knee pain significantly",
            "Avoid high-impact activities (running, jumping, climbing stairs repeatedly)",
            "Walking is encouraged — use a walking stick in the opposite hand if needed",
            "Swimming and cycling are excellent low-impact exercises",
            "Apply warm pack before exercise and cold pack after for pain",
            "Knee replacement surgery is an excellent option when quality of life is severely affected",
        ],
    },
    {
        "icd10_prefix": "M80",
        "condition": "Osteoporosis",
        "tips": [
            "Take calcium (1000–1200 mg/day from diet + supplement) and Vitamin D as prescribed",
            "Weight-bearing exercise (walking, dancing) helps maintain bone density",
            "Quit smoking and limit alcohol — both weaken bones",
            "Fall prevention: remove trip hazards, improve lighting, use bathroom rails",
            "Take bisphosphonates on an empty stomach with a full glass of water; stay upright for 30 minutes",
            "DEXA scan to monitor bone density as advised",
            "Report any back pain, height loss, or fracture from minor trauma",
        ],
    },

    # ── Women's Health ───────────────────────────────────────────────────────────
    {
        "icd10_prefix": "O00",
        "condition": "Ectopic Pregnancy",
        "tips": [
            "Attend all follow-up appointments — monitoring hCG until zero is essential",
            "Report immediately: severe abdominal pain, shoulder tip pain, dizziness, or fainting",
            "Wait 3 months before trying to conceive again",
            "Inform your doctor of any previous ectopic before future pregnancies — early scan needed",
            "Emotional support: loss of a pregnancy at any stage needs acknowledgement and counselling",
        ],
    },
    {
        "icd10_prefix": "N91",
        "condition": "Amenorrhoea / Menstrual Irregularity",
        "tips": [
            "Maintain a healthy weight — both underweight and overweight disrupt periods",
            "Manage stress levels — high stress affects hormonal balance",
            "Eat regular balanced meals — extreme dieting or restrictive eating causes amenorrhoea",
            "Rule out pregnancy first with a home test",
            "Keep a menstrual calendar to track cycle patterns",
            "If on hormonal treatment, take at the same time daily",
        ],
    },
    {
        "icd10_prefix": "N80",
        "condition": "Endometriosis",
        "tips": [
            "Hormonal treatment (contraceptive pill, progestins, GnRH analogues) is taken continuously as prescribed",
            "Regular follow-up with your gynaecologist is essential",
            "Heat (warm pack on lower abdomen) helps with period pain",
            "Exercise helps reduce oestrogen levels and pain",
            "Fertility concerns: discuss with your gynaecologist early — treatment options exist",
            "Report increasing pain, bowel or bladder symptoms",
        ],
    },
    {
        "icd10_prefix": "O20",
        "condition": "Threatened Abortion / Subchorionic Haematoma",
        "tips": [
            "Rest — avoid strenuous activity, heavy lifting, and sexual intercourse until advised",
            "Take progesterone as prescribed without missing doses",
            "Report any increase in bleeding, passage of tissue, or severe cramping immediately",
            "Attend all ultrasound follow-up appointments",
            "Emotional support: anxiety is normal — counselling helps",
        ],
    },
    {
        "icd10_prefix": "O10",
        "condition": "Pre-eclampsia / Gestational Hypertension",
        "tips": [
            "Monitor BP at home twice daily and keep a record",
            "Take antihypertensive medicines and aspirin/calcium as prescribed",
            "Report: severe headache, visual blurring, right upper abdominal pain, sudden swelling, or decreased fetal movements",
            "Rest as advised; reduce stress",
            "Attend all antenatal appointments — monitoring is essential",
            "Know the warning signs of eclampsia: fits during pregnancy need emergency treatment",
        ],
    },

    # ── Paediatric ───────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "J06",
        "condition": "Upper Respiratory Tract Infection (URTI) in Children",
        "tips": [
            "Viral colds do not need antibiotics — they will get better in 7–10 days",
            "Paracetamol or ibuprofen for fever and discomfort only — dose based on weight",
            "Encourage plenty of fluids: water, warm soups, breast milk",
            "Honey (for children over 1 year) soothes cough — do not give to infants",
            "Saline nasal drops loosen congestion in infants; gentle bulb suction helps",
            "Return if: fever lasts over 5 days, child is very drowsy, not drinking, breathing is fast or difficult",
            "Do not give cold and cough medicines to children under 6 years",
        ],
    },
    {
        "icd10_prefix": "K52",
        "condition": "Acute Gastroenteritis in Children",
        "tips": [
            "Oral rehydration solution (ORS) is the mainstay treatment — give small sips frequently",
            "Continue breastfeeding — do not stop",
            "Offer age-appropriate foods after rehydration: rice, dal, banana, khichdi",
            "Zinc syrup for 14 days reduces severity and future episodes",
            "Return immediately: child is not drinking, urine is very dark, eyes sunken, very drowsy",
            "Hand hygiene strictly after nappy change and before preparing food",
            "ORS recipe: 1 litre boiled water + 6 teaspoons sugar + half teaspoon salt",
        ],
    },

    # ── Skin ─────────────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "L20",
        "condition": "Atopic Dermatitis (Eczema)",
        "tips": [
            "Moisturise generously twice daily even when skin looks clear — use fragrance-free thick creams",
            "Apply steroid cream to affected areas as prescribed — do not overuse on face or skin folds",
            "Avoid hot baths; use lukewarm water and mild, fragrance-free soap",
            "Identify and avoid triggers: wool clothing, sweating, certain soaps, pet dander",
            "Keep nails short to minimise scratch damage",
            "Wear cotton clothing — avoid synthetic fabrics",
            "Antihistamine at night helps with itch if prescribed",
        ],
    },
    {
        "icd10_prefix": "L40",
        "condition": "Psoriasis",
        "tips": [
            "Moisturise affected areas at least twice a day — reduces scaling and itch",
            "Apply topical medicines (steroid, calcipotriol) as directed — do not stop abruptly",
            "Brief, regular sunlight exposure can help — but avoid sunburn",
            "Stress management is important — psoriasis flares with stress",
            "Avoid smoking and excessive alcohol — both worsen psoriasis",
            "Report joint pains — psoriatic arthritis needs separate treatment",
            "Psoriasis is not contagious — others cannot catch it from you",
        ],
    },
    {
        "icd10_prefix": "B35",
        "condition": "Dermatophytosis (Ringworm / Tinea)",
        "tips": [
            "Apply antifungal cream twice daily to the affected area AND 2 cm around it",
            "Continue for 2 weeks AFTER the rash disappears — stopping early causes recurrence",
            "Keep the affected area clean and dry — fungus thrives in moisture",
            "Do not share towels, clothing, or footwear with family members",
            "Change and wash undergarments and socks daily in hot water",
            "Lose weight if obese — skin folds trap moisture and encourage fungal growth",
            "Do not use over-the-counter steroid-antifungal combination creams for more than 2 weeks",
        ],
    },

    # ── Urology ──────────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "N39",
        "condition": "Urinary Tract Infection (UTI)",
        "tips": [
            "Complete the full antibiotic course even if symptoms resolve early",
            "Drink at least 2.5–3 litres of water daily to flush bacteria",
            "Urinate after sexual intercourse to clear the urethra",
            "Wipe front to back after toilet (women) to prevent bacterial spread",
            "Return if fever develops, back/loin pain, or no improvement in 48 hours — could be kidney infection",
            "Cranberry juice may have mild preventive benefit",
            "Recurrent UTI (more than 3/year): discuss low-dose prophylactic antibiotics with your doctor",
        ],
    },
    {
        "icd10_prefix": "N40",
        "condition": "Benign Prostatic Hyperplasia (BPH)",
        "tips": [
            "Take medicines (alpha-blockers/5-alpha reductase inhibitors) consistently — they take weeks to show full effect",
            "Reduce fluid intake in the evenings to reduce night-time urination",
            "Limit caffeine and alcohol — they irritate the bladder",
            "Do not hold urine for long periods — urinate as soon as you feel the urge",
            "Double voiding: after urinating, wait a minute and try again to empty completely",
            "Report sudden inability to urinate, blood in urine, or severe pain — go to emergency",
            "Annual PSA and prostate check as advised by your doctor",
        ],
    },

    # ── Ophthalmology ────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "H40",
        "condition": "Glaucoma",
        "tips": [
            "Use eye drops exactly as prescribed — glaucoma causes painless, permanent vision loss if untreated",
            "Never miss doses; use a reminder system",
            "Technique: pull lower lid down, instill drop, close eye gently for 1–2 minutes",
            "Wait 5 minutes between different eye drops",
            "Avoid heavy lifting and breath-holding during exertion — raises eye pressure",
            "Attend all follow-up appointments — optic nerve and eye pressure monitoring is essential",
            "Inform your doctor of all other medicines — many affect eye pressure",
        ],
    },
    {
        "icd10_prefix": "H26",
        "condition": "Cataract",
        "tips": [
            "Surgery is the only cure — glasses cannot treat cataracts",
            "Use prescribed eye drops before and after surgery as directed",
            "Avoid rubbing your eyes after surgery",
            "Wear sunglasses outdoors to protect from UV light",
            "Swimming and contact sports should be avoided for at least 4 weeks after surgery",
            "Report sudden increase in pain, redness, or vision change after surgery immediately",
        ],
    },
    {
        "icd10_prefix": "H36",
        "condition": "Diabetic Retinopathy",
        "tips": [
            "Strict blood sugar control is the most important measure to slow progression",
            "Blood pressure control is also crucial",
            "Annual dilated eye examination every year if diabetic",
            "Report any sudden vision loss, floaters, or dark curtain immediately — emergency",
            "Laser treatment or injections are effective — attend follow-ups",
            "Quit smoking — it accelerates retinopathy",
        ],
    },

    # ── ENT ──────────────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "H91",
        "condition": "Sensorineural Hearing Loss",
        "tips": [
            "Avoid loud noise exposure — use ear protection in noisy environments",
            "Hearing aids are very effective — get fitted by an audiologist if advised",
            "Do not put cotton buds, hair pins, or any object in the ear canal",
            "Attend speech therapy if hearing loss affects communication",
            "Report sudden hearing loss immediately — it is a medical emergency",
            "Protect ears when swimming if prone to infection",
        ],
    },

    # ── Oncology ─────────────────────────────────────────────────────────────────
    {
        "icd10_prefix": "C50",
        "condition": "Breast Cancer",
        "tips": [
            "Attend all chemotherapy, radiotherapy, and hormonal therapy sessions — do not skip",
            "Report fever above 38°C during chemotherapy immediately — infection risk is high",
            "Eat a nutritious, high-protein diet to maintain strength during treatment",
            "Gentle exercise (walking, yoga) reduces fatigue and improves mood during treatment",
            "Breast self-examination monthly; report any new lump, nipple discharge, or skin change",
            "Mammogram of the other breast annually as advised",
            "Hormonal therapy (tamoxifen/aromatase inhibitor) is taken for 5–10 years — do not stop without consultation",
            "Report joint pain or hot flushes on aromatase inhibitors",
            "Seek psychological support — depression and anxiety are very common during treatment",
        ],
    },
    {
        "icd10_prefix": "C18",
        "condition": "Colorectal Cancer",
        "tips": [
            "Attend all follow-up colonoscopies and CEA blood tests as scheduled",
            "High-fibre diet (fruits, vegetables, whole grains) is recommended",
            "Maintain a healthy weight and exercise regularly",
            "Avoid red and processed meat",
            "Quit smoking and limit alcohol",
            "Stoma care: if you have a stoma, nurse education and regular stoma clinic review is essential",
            "Report blood in stools, change in bowel habit, or unexplained weight loss",
        ],
    },
    {
        "icd10_prefix": "C61",
        "condition": "Prostate Cancer",
        "tips": [
            "Attend all PSA monitoring and imaging follow-ups as scheduled",
            "Hormone therapy (androgen deprivation): take as prescribed; monitor bone density",
            "Exercise helps reduce fatigue and bone loss from hormone therapy",
            "Calcium and Vitamin D supplements if on long-term hormone therapy",
            "Report bone pain, urinary symptoms, or new symptoms promptly",
            "Active surveillance (watchful waiting): attend all follow-up appointments strictly",
        ],
    },
]
