"""
India-priority curated diseases — ICD-10 coded, specialty-mapped.
Each entry: {icd10, display, specialty, synonyms (pipe-sep)}
ICD-10 codes validated against simple-icd-10 at seed time; invalid dropped.
"""

DISEASES = [
    # ── General Medicine ──────────────────────────────────────────────────────
    {"icd10": "A09", "display": "Gastroenteritis", "specialty": "general_medicine", "synonyms": "stomach flu|diarrhoea|loose motion|diarrhea"},
    {"icd10": "A15", "display": "Pulmonary Tuberculosis", "specialty": "general_medicine", "synonyms": "TB|tuberculosis|Koch's disease|PTB"},
    {"icd10": "A16", "display": "Tuberculosis (non-bacteriologically confirmed)", "specialty": "general_medicine", "synonyms": "TB|tuberculosis"},
    {"icd10": "A90", "display": "Dengue Fever", "specialty": "general_medicine", "synonyms": "dengue|dengue haemorrhagic fever|breakbone fever"},
    {"icd10": "A91", "display": "Dengue Haemorrhagic Fever", "specialty": "general_medicine", "synonyms": "DHF|dengue haemorrhagic"},
    {"icd10": "A95", "display": "Yellow Fever", "specialty": "general_medicine", "synonyms": "yellow fever"},
    {"icd10": "A77", "display": "Spotted Fever (Rickettsia)", "specialty": "general_medicine", "synonyms": "scrub typhus|rickettsial fever|spotted fever"},
    {"icd10": "B50", "display": "Plasmodium falciparum Malaria", "specialty": "general_medicine", "synonyms": "falciparum malaria|cerebral malaria|malaria"},
    {"icd10": "B51", "display": "Plasmodium vivax Malaria", "specialty": "general_medicine", "synonyms": "vivax malaria|malaria"},
    {"icd10": "B54", "display": "Unspecified Malaria", "specialty": "general_medicine", "synonyms": "malaria"},
    {"icd10": "A01", "display": "Typhoid Fever", "specialty": "general_medicine", "synonyms": "typhoid|enteric fever|Salmonella typhi"},
    {"icd10": "A06", "display": "Amoebiasis", "specialty": "general_medicine", "synonyms": "amoebic dysentery|amoeba|entamoeba"},
    {"icd10": "A07", "display": "Giardiasis", "specialty": "general_medicine", "synonyms": "giardia|Giardia lamblia"},
    {"icd10": "B19", "display": "Viral Hepatitis (unspecified)", "specialty": "general_medicine", "synonyms": "hepatitis|jaundice|liver infection"},
    {"icd10": "B15", "display": "Acute Hepatitis A", "specialty": "general_medicine", "synonyms": "hepatitis A|HAV|jaundice"},
    {"icd10": "B16", "display": "Acute Hepatitis B", "specialty": "general_medicine", "synonyms": "hepatitis B|HBV|jaundice"},
    {"icd10": "B17", "display": "Acute Hepatitis C", "specialty": "general_medicine", "synonyms": "hepatitis C|HCV"},
    {"icd10": "A37", "display": "Whooping Cough (Pertussis)", "specialty": "general_medicine", "synonyms": "pertussis|whooping cough|Bordetella"},
    {"icd10": "A36", "display": "Diphtheria", "specialty": "general_medicine", "synonyms": "diphtheria|Corynebacterium"},
    {"icd10": "A33", "display": "Tetanus Neonatorum", "specialty": "general_medicine", "synonyms": "tetanus|lockjaw"},
    {"icd10": "A34", "display": "Obstetric Tetanus", "specialty": "general_medicine", "synonyms": "tetanus|lockjaw"},
    {"icd10": "B05", "display": "Measles", "specialty": "general_medicine", "synonyms": "measles|rubeola|khasra"},
    {"icd10": "B06", "display": "Rubella", "specialty": "general_medicine", "synonyms": "rubella|German measles"},
    {"icd10": "B26", "display": "Mumps", "specialty": "general_medicine", "synonyms": "mumps|parotitis"},
    {"icd10": "B01", "display": "Chickenpox (Varicella)", "specialty": "general_medicine", "synonyms": "chickenpox|varicella|chiken pox"},
    {"icd10": "B02", "display": "Herpes Zoster (Shingles)", "specialty": "general_medicine", "synonyms": "shingles|zoster|herpes zoster"},
    {"icd10": "J06", "display": "Acute Upper Respiratory Infection", "specialty": "general_medicine", "synonyms": "common cold|URI|URTI|cold|coryza"},
    {"icd10": "J11", "display": "Influenza (Flu)", "specialty": "general_medicine", "synonyms": "flu|influenza|viral fever"},
    {"icd10": "J18", "display": "Pneumonia (unspecified)", "specialty": "general_medicine", "synonyms": "pneumonia|lung infection"},
    {"icd10": "R50", "display": "Fever of Unknown Origin", "specialty": "general_medicine", "synonyms": "FUO|pyrexia|fever|unknown fever"},
    {"icd10": "E11", "display": "Type 2 Diabetes Mellitus", "specialty": "general_medicine", "synonyms": "diabetes|T2DM|sugar disease|madhumeha"},
    {"icd10": "E10", "display": "Type 1 Diabetes Mellitus", "specialty": "general_medicine", "synonyms": "juvenile diabetes|T1DM|insulin-dependent diabetes"},
    {"icd10": "I10", "display": "Essential Hypertension", "specialty": "general_medicine", "synonyms": "high blood pressure|HTN|hypertension|BP high"},
    {"icd10": "I25", "display": "Chronic Ischaemic Heart Disease", "specialty": "general_medicine", "synonyms": "coronary artery disease|CAD|ischaemic heart disease|IHD"},
    {"icd10": "I50", "display": "Heart Failure", "specialty": "general_medicine", "synonyms": "cardiac failure|congestive heart failure|CHF"},
    {"icd10": "E78", "display": "Hyperlipidaemia", "specialty": "general_medicine", "synonyms": "high cholesterol|dyslipidaemia|hypercholesterolaemia|lipid disorder"},
    {"icd10": "K29", "display": "Gastritis", "specialty": "general_medicine", "synonyms": "gastritis|stomach inflammation|acidity"},
    {"icd10": "K21", "display": "Gastro-oesophageal Reflux Disease (GERD)", "specialty": "general_medicine", "synonyms": "GERD|acid reflux|heartburn|GORD"},
    {"icd10": "K25", "display": "Gastric Ulcer", "specialty": "general_medicine", "synonyms": "peptic ulcer|stomach ulcer|gastric ulcer"},
    {"icd10": "K26", "display": "Duodenal Ulcer", "specialty": "general_medicine", "synonyms": "duodenal ulcer|peptic ulcer"},
    {"icd10": "M79", "display": "Fibromyalgia / Myalgia NOS", "specialty": "general_medicine", "synonyms": "body pain|muscle pain|myalgia|fibromyalgia"},
    {"icd10": "G43", "display": "Migraine", "specialty": "general_medicine", "synonyms": "migraine|hemicrania|severe headache"},
    {"icd10": "J45", "display": "Asthma", "specialty": "general_medicine", "synonyms": "bronchial asthma|asthma|wheezing|dama"},
    {"icd10": "N39", "display": "Urinary Tract Infection (UTI)", "specialty": "general_medicine", "synonyms": "UTI|urinary infection|cystitis|peshab infection"},
    {"icd10": "L50", "display": "Urticaria (Hives)", "specialty": "general_medicine", "synonyms": "hives|urticaria|allergic rash|pitti"},
    {"icd10": "L20", "display": "Atopic Dermatitis (Eczema)", "specialty": "general_medicine", "synonyms": "eczema|atopic dermatitis|khujli"},
    {"icd10": "J00", "display": "Acute Nasopharyngitis (Common Cold)", "specialty": "general_medicine", "synonyms": "cold|runny nose|common cold|coryza"},
    {"icd10": "J02", "display": "Acute Pharyngitis (Sore Throat)", "specialty": "general_medicine", "synonyms": "sore throat|pharyngitis|throat pain|tonsillitis"},
    {"icd10": "J03", "display": "Acute Tonsillitis", "specialty": "general_medicine", "synonyms": "tonsillitis|tonsil infection"},
    {"icd10": "A09", "display": "Acute Diarrhoea", "specialty": "general_medicine", "synonyms": "loose motion|diarrhoea|diarrhea|watery stool"},
    {"icd10": "K57", "display": "Diverticular Disease of Colon", "specialty": "general_medicine", "synonyms": "diverticulitis|diverticulosis"},
    {"icd10": "R05", "display": "Cough", "specialty": "general_medicine", "synonyms": "chronic cough|dry cough|productive cough|khansi"},
    {"icd10": "E03", "display": "Hypothyroidism", "specialty": "general_medicine", "synonyms": "underactive thyroid|thyroid deficiency|hypothyroid"},
    {"icd10": "E05", "display": "Hyperthyroidism", "specialty": "general_medicine", "synonyms": "overactive thyroid|thyrotoxicosis|hyperthyroid|Graves disease"},
    {"icd10": "E04", "display": "Goitre (Non-toxic)", "specialty": "general_medicine", "synonyms": "goitre|thyroid swelling|thyromegaly"},
    {"icd10": "D50", "display": "Iron Deficiency Anaemia", "specialty": "general_medicine", "synonyms": "anaemia|anemia|iron deficiency|low haemoglobin|khoon ki kami"},
    {"icd10": "D51", "display": "Vitamin B12 Deficiency Anaemia", "specialty": "general_medicine", "synonyms": "B12 deficiency|cobalamin deficiency|megaloblastic anaemia"},
    {"icd10": "D52", "display": "Folate Deficiency Anaemia", "specialty": "general_medicine", "synonyms": "folic acid deficiency|folate deficiency"},
    {"icd10": "E55", "display": "Vitamin D Deficiency", "specialty": "general_medicine", "synonyms": "vitamin D deficiency|D3 deficiency|Vit D low"},
    {"icd10": "E58", "display": "Dietary Calcium Deficiency", "specialty": "general_medicine", "synonyms": "calcium deficiency|hypocalcaemia"},
    {"icd10": "E61", "display": "Zinc Deficiency", "specialty": "general_medicine", "synonyms": "zinc deficiency"},
    {"icd10": "K59", "display": "Constipation", "specialty": "general_medicine", "synonyms": "constipation|hard stool|kabz|inability to pass stool"},
    {"icd10": "K92", "display": "Gastrointestinal Haemorrhage", "specialty": "general_medicine", "synonyms": "GI bleed|blood in stool|haematemesis|melaena"},

    # ── Cardiology ────────────────────────────────────────────────────────────
    {"icd10": "I21", "display": "Acute Myocardial Infarction (Heart Attack)", "specialty": "cardiology", "synonyms": "heart attack|AMI|MI|myocardial infarction|dil ka daura"},
    {"icd10": "I20", "display": "Angina Pectoris", "specialty": "cardiology", "synonyms": "angina|chest pain|stable angina|unstable angina"},
    {"icd10": "I48", "display": "Atrial Fibrillation", "specialty": "cardiology", "synonyms": "AF|AFib|atrial fibrillation|irregular heartbeat"},
    {"icd10": "I49", "display": "Cardiac Arrhythmia", "specialty": "cardiology", "synonyms": "arrhythmia|irregular heartbeat|palpitation|dysrhythmia"},
    {"icd10": "I35", "display": "Aortic Valve Disease", "specialty": "cardiology", "synonyms": "aortic stenosis|aortic regurgitation|valve disease"},
    {"icd10": "I34", "display": "Mitral Valve Disease", "specialty": "cardiology", "synonyms": "mitral stenosis|mitral regurgitation|MVP|mitral valve prolapse"},
    {"icd10": "I42", "display": "Cardiomyopathy", "specialty": "cardiology", "synonyms": "cardiomyopathy|dilated cardiomyopathy|DCM|HCM"},
    {"icd10": "I26", "display": "Pulmonary Embolism", "specialty": "cardiology", "synonyms": "PE|blood clot in lung|pulmonary embolism|DVT-PE"},
    {"icd10": "I71", "display": "Aortic Aneurysm", "specialty": "cardiology", "synonyms": "aortic aneurysm|aortic dissection"},
    {"icd10": "I73", "display": "Peripheral Vascular Disease", "specialty": "cardiology", "synonyms": "PVD|peripheral artery disease|PAD"},
    {"icd10": "I27", "display": "Pulmonary Hypertension", "specialty": "cardiology", "synonyms": "PAH|pulmonary arterial hypertension"},
    {"icd10": "I30", "display": "Pericarditis", "specialty": "cardiology", "synonyms": "pericarditis|pericardial inflammation"},
    {"icd10": "I40", "display": "Myocarditis", "specialty": "cardiology", "synonyms": "myocarditis|heart muscle inflammation"},
    {"icd10": "I50", "display": "Congestive Heart Failure (CHF)", "specialty": "cardiology", "synonyms": "CHF|heart failure|cardiac failure|left heart failure|right heart failure"},

    # ── Endocrinology ─────────────────────────────────────────────────────────
    {"icd10": "E11", "display": "Type 2 Diabetes Mellitus", "specialty": "endocrinology", "synonyms": "T2DM|sugar|diabetes|madhumeha"},
    {"icd10": "E10", "display": "Type 1 Diabetes Mellitus", "specialty": "endocrinology", "synonyms": "T1DM|juvenile diabetes|insulin-dependent"},
    {"icd10": "E13", "display": "Other Specified Diabetes Mellitus", "specialty": "endocrinology", "synonyms": "MODY|maturity-onset diabetes|secondary diabetes"},
    {"icd10": "E16", "display": "Hypoglycaemia", "specialty": "endocrinology", "synonyms": "low blood sugar|hypoglycaemia|hypoglycemia"},
    {"icd10": "E05", "display": "Thyrotoxicosis (Hyperthyroidism)", "specialty": "endocrinology", "synonyms": "hyperthyroidism|Graves disease|thyroid storm"},
    {"icd10": "E03", "display": "Hypothyroidism", "specialty": "endocrinology", "synonyms": "underactive thyroid|Hashimoto thyroiditis|myxoedema"},
    {"icd10": "E06", "display": "Thyroiditis", "specialty": "endocrinology", "synonyms": "Hashimoto thyroiditis|autoimmune thyroid|thyroid inflammation"},
    {"icd10": "E21", "display": "Hyperparathyroidism", "specialty": "endocrinology", "synonyms": "parathyroid|hypercalcaemia|PTH excess"},
    {"icd10": "E22", "display": "Hyperpituitarism", "specialty": "endocrinology", "synonyms": "acromegaly|gigantism|prolactinoma|pituitary adenoma"},
    {"icd10": "E24", "display": "Cushing Syndrome", "specialty": "endocrinology", "synonyms": "hypercortisolism|Cushing disease|cortisol excess"},
    {"icd10": "E27", "display": "Adrenal Insufficiency (Addison Disease)", "specialty": "endocrinology", "synonyms": "Addison disease|adrenal insufficiency|adrenal failure"},
    {"icd10": "E28", "display": "Polycystic Ovary Syndrome (PCOS)", "specialty": "endocrinology", "synonyms": "PCOS|PCOD|polycystic ovaries|hormonal imbalance"},
    {"icd10": "E66", "display": "Obesity", "specialty": "endocrinology", "synonyms": "obesity|morbid obesity|overweight"},
    {"icd10": "E83", "display": "Disorders of Mineral Metabolism", "specialty": "endocrinology", "synonyms": "electrolyte disorder|hyponatremia|hypernatremia|hypokalemia"},

    # ── Nephrology ────────────────────────────────────────────────────────────
    {"icd10": "N18", "display": "Chronic Kidney Disease (CKD)", "specialty": "nephrology", "synonyms": "CKD|chronic renal failure|kidney failure|gursay ki bimari"},
    {"icd10": "N17", "display": "Acute Kidney Injury (AKI)", "specialty": "nephrology", "synonyms": "AKI|acute renal failure|ARF"},
    {"icd10": "N04", "display": "Nephrotic Syndrome", "specialty": "nephrology", "synonyms": "nephrotic syndrome|proteinuria|protein in urine"},
    {"icd10": "N05", "display": "Nephritic Syndrome", "specialty": "nephrology", "synonyms": "nephritic syndrome|glomerulonephritis|kidney inflammation"},
    {"icd10": "N20", "display": "Renal Calculi (Kidney Stones)", "specialty": "nephrology", "synonyms": "kidney stones|renal calculi|urolithiasis|pathri"},
    {"icd10": "N39", "display": "Urinary Tract Infection", "specialty": "nephrology", "synonyms": "UTI|cystitis|urinary infection"},
    {"icd10": "N10", "display": "Acute Pyelonephritis", "specialty": "nephrology", "synonyms": "kidney infection|pyelonephritis|upper UTI"},
    {"icd10": "N11", "display": "Chronic Pyelonephritis", "specialty": "nephrology", "synonyms": "chronic kidney infection|reflux nephropathy"},
    {"icd10": "N01", "display": "Rapidly Progressive Nephritis", "specialty": "nephrology", "synonyms": "RPGN|crescentic glomerulonephritis"},
    {"icd10": "N08", "display": "Glomerular Disorders in Diseases Classified Elsewhere", "specialty": "nephrology", "synonyms": "diabetic nephropathy|lupus nephritis|glomerulonephritis"},
    {"icd10": "N25", "display": "Renal Tubular Acidosis", "specialty": "nephrology", "synonyms": "RTA|tubular acidosis"},
    {"icd10": "N28", "display": "Renovascular Hypertension", "specialty": "nephrology", "synonyms": "renal artery stenosis|renovascular disease"},

    # ── Pulmonology ───────────────────────────────────────────────────────────
    {"icd10": "J45", "display": "Bronchial Asthma", "specialty": "pulmonology", "synonyms": "asthma|bronchial asthma|wheezing|dama|bronchospasm"},
    {"icd10": "J44", "display": "Chronic Obstructive Pulmonary Disease (COPD)", "specialty": "pulmonology", "synonyms": "COPD|emphysema|chronic bronchitis|breathlessness"},
    {"icd10": "J18", "display": "Pneumonia", "specialty": "pulmonology", "synonyms": "pneumonia|lung infection|chest infection"},
    {"icd10": "J15", "display": "Bacterial Pneumonia", "specialty": "pulmonology", "synonyms": "bacterial pneumonia|community-acquired pneumonia|CAP"},
    {"icd10": "J12", "display": "Viral Pneumonia", "specialty": "pulmonology", "synonyms": "viral pneumonia|COVID pneumonia"},
    {"icd10": "J70", "display": "Interstitial Lung Disease (ILD)", "specialty": "pulmonology", "synonyms": "ILD|interstitial lung disease|pulmonary fibrosis|IPF"},
    {"icd10": "J86", "display": "Pyothorax (Empyema)", "specialty": "pulmonology", "synonyms": "empyema|pleural empyema|chest pus"},
    {"icd10": "J90", "display": "Pleural Effusion", "specialty": "pulmonology", "synonyms": "pleural effusion|fluid in chest|hydrothorax"},
    {"icd10": "J93", "display": "Pneumothorax", "specialty": "pulmonology", "synonyms": "pneumothorax|collapsed lung|air in chest"},
    {"icd10": "J98", "display": "Pulmonary Collapse / Atelectasis", "specialty": "pulmonology", "synonyms": "atelectasis|lung collapse"},
    {"icd10": "J84", "display": "Idiopathic Pulmonary Fibrosis (IPF)", "specialty": "pulmonology", "synonyms": "IPF|pulmonary fibrosis|UIP"},
    {"icd10": "J96", "display": "Respiratory Failure", "specialty": "pulmonology", "synonyms": "respiratory failure|ARDS|hypoxia|hypercapnia"},
    {"icd10": "J40", "display": "Chronic Bronchitis", "specialty": "pulmonology", "synonyms": "chronic bronchitis|productive cough|COPD"},
    {"icd10": "A15", "display": "Pulmonary Tuberculosis (PTB)", "specialty": "pulmonology", "synonyms": "TB|pulmonary TB|Koch's disease|cavitary TB"},

    # ── Gastroenterology ──────────────────────────────────────────────────────
    {"icd10": "K70", "display": "Alcoholic Liver Disease", "specialty": "gastroenterology", "synonyms": "alcoholic liver disease|ALD|cirrhosis alcoholic"},
    {"icd10": "K74", "display": "Liver Cirrhosis", "specialty": "gastroenterology", "synonyms": "cirrhosis|liver cirrhosis|chronic liver disease"},
    {"icd10": "K73", "display": "Chronic Hepatitis", "specialty": "gastroenterology", "synonyms": "chronic hepatitis|autoimmune hepatitis|NASH|fatty liver"},
    {"icd10": "K76", "display": "Non-alcoholic Fatty Liver Disease (NAFLD)", "specialty": "gastroenterology", "synonyms": "fatty liver|NAFLD|NASH|steatohepatitis"},
    {"icd10": "K80", "display": "Cholelithiasis (Gallstones)", "specialty": "gastroenterology", "synonyms": "gallstones|cholelithiasis|gallbladder stones|pitt ki pathri"},
    {"icd10": "K81", "display": "Cholecystitis", "specialty": "gastroenterology", "synonyms": "cholecystitis|gallbladder inflammation"},
    {"icd10": "K85", "display": "Acute Pancreatitis", "specialty": "gastroenterology", "synonyms": "pancreatitis|acute pancreatitis|pancreas inflammation"},
    {"icd10": "K86", "display": "Chronic Pancreatitis", "specialty": "gastroenterology", "synonyms": "chronic pancreatitis|exocrine pancreatic insufficiency"},
    {"icd10": "K50", "display": "Crohn Disease", "specialty": "gastroenterology", "synonyms": "Crohn disease|inflammatory bowel disease|IBD"},
    {"icd10": "K51", "display": "Ulcerative Colitis", "specialty": "gastroenterology", "synonyms": "ulcerative colitis|UC|IBD|colitis"},
    {"icd10": "K58", "display": "Irritable Bowel Syndrome (IBS)", "specialty": "gastroenterology", "synonyms": "IBS|irritable bowel|spastic colon|functional bowel"},
    {"icd10": "K92", "display": "Upper GI Bleeding", "specialty": "gastroenterology", "synonyms": "haematemesis|upper GI bleed|blood vomiting|melena"},
    {"icd10": "K57", "display": "Diverticulitis", "specialty": "gastroenterology", "synonyms": "diverticulitis|diverticulosis|colonic diverticular"},
    {"icd10": "K29", "display": "Gastritis", "specialty": "gastroenterology", "synonyms": "gastritis|stomach inflammation|H. pylori gastritis"},
    {"icd10": "K21", "display": "Gastro-oesophageal Reflux Disease (GERD)", "specialty": "gastroenterology", "synonyms": "GERD|GORD|acid reflux|heartburn"},
    {"icd10": "K25", "display": "Peptic Ulcer Disease", "specialty": "gastroenterology", "synonyms": "peptic ulcer|gastric ulcer|duodenal ulcer|PUD"},

    # ── Neurology ─────────────────────────────────────────────────────────────
    {"icd10": "I63", "display": "Ischaemic Stroke (Cerebral Infarction)", "specialty": "neurology", "synonyms": "stroke|CVA|ischaemic stroke|brain attack|lakwa"},
    {"icd10": "I61", "display": "Intracerebral Haemorrhage (Haemorrhagic Stroke)", "specialty": "neurology", "synonyms": "brain bleed|ICH|haemorrhagic stroke"},
    {"icd10": "G20", "display": "Parkinson Disease", "specialty": "neurology", "synonyms": "Parkinson's disease|PD|tremor|parkinsonian"},
    {"icd10": "G30", "display": "Alzheimer Disease", "specialty": "neurology", "synonyms": "Alzheimer's|dementia|memory loss"},
    {"icd10": "G40", "display": "Epilepsy", "specialty": "neurology", "synonyms": "epilepsy|seizure disorder|fits|convulsions|mirgi"},
    {"icd10": "G43", "display": "Migraine", "specialty": "neurology", "synonyms": "migraine|hemiplegic migraine|basilar migraine|aura"},
    {"icd10": "G35", "display": "Multiple Sclerosis (MS)", "specialty": "neurology", "synonyms": "MS|multiple sclerosis|demyelination"},
    {"icd10": "G71", "display": "Muscular Dystrophy", "specialty": "neurology", "synonyms": "muscular dystrophy|DMD|Duchenne|Becker muscular"},
    {"icd10": "G61", "display": "Guillain-Barré Syndrome", "specialty": "neurology", "synonyms": "GBS|Guillain-Barre|ascending paralysis"},
    {"icd10": "G70", "display": "Myasthenia Gravis", "specialty": "neurology", "synonyms": "myasthenia gravis|MG|neuromuscular junction"},
    {"icd10": "G54", "display": "Radiculopathy / Nerve Root Compression", "specialty": "neurology", "synonyms": "radiculopathy|disc prolapse|nerve compression|sciatica"},
    {"icd10": "G51", "display": "Bell's Palsy (Facial Nerve Palsy)", "specialty": "neurology", "synonyms": "Bell's palsy|facial palsy|facial nerve palsy"},
    {"icd10": "G50", "display": "Trigeminal Neuralgia", "specialty": "neurology", "synonyms": "trigeminal neuralgia|tic douloureux|face pain"},
    {"icd10": "G47", "display": "Sleep Disorders (Insomnia)", "specialty": "neurology", "synonyms": "insomnia|sleep disorder|sleep apnoea|narcolepsy"},
    {"icd10": "R55", "display": "Syncope (Fainting)", "specialty": "neurology", "synonyms": "syncope|fainting|blackout|vasovagal|presyncope"},
    {"icd10": "G93", "display": "Encephalopathy", "specialty": "neurology", "synonyms": "encephalopathy|brain dysfunction|hepatic encephalopathy"},
    {"icd10": "A80", "display": "Meningitis / Encephalitis", "specialty": "neurology", "synonyms": "meningitis|encephalitis|brain fever|neck stiffness"},

    # ── Orthopedics ───────────────────────────────────────────────────────────
    {"icd10": "M16", "display": "Osteoarthritis of Hip", "specialty": "orthopedics", "synonyms": "hip OA|hip arthritis|coxarthrosis"},
    {"icd10": "M17", "display": "Osteoarthritis of Knee", "specialty": "orthopedics", "synonyms": "knee OA|knee arthritis|gonarthrosis|ghutna dard"},
    {"icd10": "M47", "display": "Spondylosis (Cervical / Lumbar)", "specialty": "orthopedics", "synonyms": "spondylosis|cervical spondylosis|lumbar spondylosis|spine arthritis"},
    {"icd10": "M51", "display": "Lumbar Disc Herniation", "specialty": "orthopedics", "synonyms": "disc prolapse|PLID|lumbar disc|slipped disc|sciatica"},
    {"icd10": "M50", "display": "Cervical Disc Herniation", "specialty": "orthopedics", "synonyms": "cervical disc|neck disc prolapse|cervical radiculopathy"},
    {"icd10": "M80", "display": "Osteoporosis with Fracture", "specialty": "orthopedics", "synonyms": "osteoporotic fracture|vertebral compression fracture|spine fracture"},
    {"icd10": "M81", "display": "Osteoporosis (without Fracture)", "specialty": "orthopedics", "synonyms": "osteoporosis|low bone density|DEXA"},
    {"icd10": "M75", "display": "Shoulder Periarthritis (Frozen Shoulder)", "specialty": "orthopedics", "synonyms": "frozen shoulder|adhesive capsulitis|shoulder stiffness"},
    {"icd10": "M65", "display": "Tendinitis / Tenosynovitis", "specialty": "orthopedics", "synonyms": "tendinitis|tendonitis|De Quervain|rotator cuff tendinopathy"},
    {"icd10": "M79", "display": "Plantar Fasciitis / Heel Pain", "specialty": "orthopedics", "synonyms": "plantar fasciitis|heel spur|heel pain"},
    {"icd10": "M72", "display": "Carpal Tunnel Syndrome", "specialty": "orthopedics", "synonyms": "CTS|carpal tunnel|median nerve compression"},
    {"icd10": "S72", "display": "Fracture of Femur (Hip Fracture)", "specialty": "orthopedics", "synonyms": "hip fracture|neck of femur fracture|NOF fracture"},

    # ── Gynecology ────────────────────────────────────────────────────────────
    {"icd10": "N80", "display": "Endometriosis", "specialty": "gynecology", "synonyms": "endometriosis|chocolate cyst|adenomyosis"},
    {"icd10": "D25", "display": "Uterine Fibroid (Leiomyoma)", "specialty": "gynecology", "synonyms": "fibroid|uterine myoma|leiomyoma|rasauli"},
    {"icd10": "N92", "display": "Menorrhagia (Heavy Menstrual Bleeding)", "specialty": "gynecology", "synonyms": "heavy periods|menorrhagia|DUB|dysfunctional uterine bleeding"},
    {"icd10": "N91", "display": "Amenorrhoea", "specialty": "gynecology", "synonyms": "absent periods|amenorrhoea|no menstruation|delayed period"},
    {"icd10": "N94", "display": "Dysmenorrhoea (Painful Periods)", "specialty": "gynecology", "synonyms": "painful periods|dysmenorrhoea|menstrual cramps|period pain"},
    {"icd10": "E28", "display": "PCOS / PCOD", "specialty": "gynecology", "synonyms": "PCOS|PCOD|polycystic ovary|hormonal imbalance|cyst in ovary"},
    {"icd10": "N70", "display": "Salpingitis / Pelvic Inflammatory Disease (PID)", "specialty": "gynecology", "synonyms": "PID|pelvic inflammatory disease|fallopian tube infection|salpingitis"},
    {"icd10": "N87", "display": "Cervical Dysplasia (Abnormal Pap Smear)", "specialty": "gynecology", "synonyms": "CIN|cervical dysplasia|abnormal pap smear|pre-cancer cervix"},
    {"icd10": "C53", "display": "Carcinoma of Cervix", "specialty": "gynecology", "synonyms": "cervical cancer|Ca cervix"},
    {"icd10": "N95", "display": "Menopause / Perimenopause Symptoms", "specialty": "gynecology", "synonyms": "menopause|perimenopause|hot flashes|ritu niwritti"},
    {"icd10": "N96", "display": "Recurrent Pregnancy Loss (RPL)", "specialty": "gynecology", "synonyms": "recurrent miscarriage|habitual abortion|RPL"},

    # ── Obstetrics ────────────────────────────────────────────────────────────
    {"icd10": "O10", "display": "Pre-existing Hypertension in Pregnancy", "specialty": "obstetrics", "synonyms": "chronic HTN pregnancy|hypertension pregnancy"},
    {"icd10": "O13", "display": "Gestational Hypertension", "specialty": "obstetrics", "synonyms": "pregnancy-induced hypertension|PIH|gestational HTN"},
    {"icd10": "O14", "display": "Pre-eclampsia", "specialty": "obstetrics", "synonyms": "pre-eclampsia|toxaemia|pregnancy hypertension with proteinuria"},
    {"icd10": "O15", "display": "Eclampsia", "specialty": "obstetrics", "synonyms": "eclampsia|fits in pregnancy|seizure in pregnancy"},
    {"icd10": "O24", "display": "Gestational Diabetes Mellitus (GDM)", "specialty": "obstetrics", "synonyms": "GDM|diabetes in pregnancy|gestational diabetes"},
    {"icd10": "O20", "display": "Threatened Abortion / Bleeding in Early Pregnancy", "specialty": "obstetrics", "synonyms": "threatened abortion|bleeding in pregnancy|miscarriage threat"},
    {"icd10": "O03", "display": "Spontaneous Abortion (Miscarriage)", "specialty": "obstetrics", "synonyms": "miscarriage|spontaneous abortion|pregnancy loss|garbhpat"},
    {"icd10": "O32", "display": "Malpresentation of Fetus", "specialty": "obstetrics", "synonyms": "breech|malpresentation|transverse lie|oblique lie"},
    {"icd10": "O36", "display": "Foetal Growth Restriction (IUGR)", "specialty": "obstetrics", "synonyms": "IUGR|FGR|small for dates|fetal growth restriction"},
    {"icd10": "O42", "display": "Premature Rupture of Membranes (PROM)", "specialty": "obstetrics", "synonyms": "PROM|PPROM|water breaking|amniotic fluid leak"},

    # ── Pediatrics ────────────────────────────────────────────────────────────
    {"icd10": "P07", "display": "Preterm Newborn Complications", "specialty": "pediatrics", "synonyms": "premature baby|preterm|low birth weight|VLBW"},
    {"icd10": "P22", "display": "Respiratory Distress Syndrome (Newborn)", "specialty": "pediatrics", "synonyms": "RDS|neonatal RDS|hyaline membrane disease"},
    {"icd10": "P36", "display": "Neonatal Sepsis", "specialty": "pediatrics", "synonyms": "neonatal sepsis|newborn infection|septicaemia newborn"},
    {"icd10": "P55", "display": "Haemolytic Disease of Newborn", "specialty": "pediatrics", "synonyms": "neonatal jaundice|Rh incompatibility|ABO incompatibility|newborn jaundice"},
    {"icd10": "J06", "display": "Acute URTI in Children", "specialty": "pediatrics", "synonyms": "cold in children|URTI|upper respiratory tract infection child"},
    {"icd10": "J18", "display": "Childhood Pneumonia", "specialty": "pediatrics", "synonyms": "pneumonia child|childhood pneumonia|chest infection child"},
    {"icd10": "A09", "display": "Acute Gastroenteritis in Children", "specialty": "pediatrics", "synonyms": "loose motion child|diarrhoea infant|gastroenteritis child"},
    {"icd10": "E41", "display": "Severe Acute Malnutrition (SAM)", "specialty": "pediatrics", "synonyms": "malnutrition|SAM|kwashiorkor|marasmus|undernutrition"},
    {"icd10": "G40", "display": "Childhood Epilepsy / Febrile Seizures", "specialty": "pediatrics", "synonyms": "fits child|febrile seizures|childhood epilepsy|infantile spasm"},
    {"icd10": "F90", "display": "Attention Deficit Hyperactivity Disorder (ADHD)", "specialty": "pediatrics", "synonyms": "ADHD|attention deficit|hyperactivity|ADD"},
    {"icd10": "F84", "display": "Autism Spectrum Disorder (ASD)", "specialty": "pediatrics", "synonyms": "autism|ASD|autistic spectrum|developmental delay"},
    {"icd10": "M05", "display": "Juvenile Rheumatoid Arthritis (JRA/JIA)", "specialty": "pediatrics", "synonyms": "JIA|JRA|juvenile arthritis|juvenile idiopathic arthritis"},
    {"icd10": "L20", "display": "Infantile Eczema", "specialty": "pediatrics", "synonyms": "infantile eczema|atopic dermatitis child|khujli child"},

    # ── Psychiatry ────────────────────────────────────────────────────────────
    {"icd10": "F32", "display": "Major Depressive Disorder", "specialty": "psychiatry", "synonyms": "depression|MDD|major depression|unipolar depression|udaasi"},
    {"icd10": "F41", "display": "Anxiety Disorders", "specialty": "psychiatry", "synonyms": "anxiety|generalised anxiety|GAD|panic disorder"},
    {"icd10": "F20", "display": "Schizophrenia", "specialty": "psychiatry", "synonyms": "schizophrenia|psychosis|paranoid schizophrenia"},
    {"icd10": "F31", "display": "Bipolar Affective Disorder", "specialty": "psychiatry", "synonyms": "bipolar|manic depression|bipolar disorder|BAD"},
    {"icd10": "F42", "display": "Obsessive-Compulsive Disorder (OCD)", "specialty": "psychiatry", "synonyms": "OCD|obsessive compulsive disorder"},
    {"icd10": "F43", "display": "Post-Traumatic Stress Disorder (PTSD)", "specialty": "psychiatry", "synonyms": "PTSD|trauma|post-traumatic stress"},
    {"icd10": "F50", "display": "Eating Disorders (Anorexia / Bulimia)", "specialty": "psychiatry", "synonyms": "anorexia|bulimia|eating disorder|binge eating"},
    {"icd10": "F10", "display": "Alcohol Use Disorder (AUD)", "specialty": "psychiatry", "synonyms": "alcoholism|alcohol dependence|AUD|alcohol abuse"},
    {"icd10": "F11", "display": "Opioid Use Disorder", "specialty": "psychiatry", "synonyms": "opioid addiction|heroin addiction|morphine dependence"},
    {"icd10": "F17", "display": "Tobacco Use Disorder / Nicotine Dependence", "specialty": "psychiatry", "synonyms": "smoking|nicotine|tobacco dependence|beedi addiction"},
    {"icd10": "F51", "display": "Insomnia / Sleep Disorder", "specialty": "psychiatry", "synonyms": "insomnia|sleep disorder|nind na aana|sleeplessness"},

    # ── Oncology ──────────────────────────────────────────────────────────────
    {"icd10": "C34", "display": "Carcinoma of Lung", "specialty": "oncology", "synonyms": "lung cancer|bronchogenic carcinoma|NSCLC|SCLC"},
    {"icd10": "C50", "display": "Carcinoma of Breast", "specialty": "oncology", "synonyms": "breast cancer|mammary carcinoma"},
    {"icd10": "C53", "display": "Carcinoma of Cervix", "specialty": "oncology", "synonyms": "cervical cancer|Ca cervix"},
    {"icd10": "C20", "display": "Carcinoma of Rectum", "specialty": "oncology", "synonyms": "rectal cancer|colorectal cancer|CRC"},
    {"icd10": "C18", "display": "Carcinoma of Colon", "specialty": "oncology", "synonyms": "colon cancer|colorectal cancer|Ca colon"},
    {"icd10": "C22", "display": "Hepatocellular Carcinoma (HCC)", "specialty": "oncology", "synonyms": "liver cancer|HCC|hepatoma|hepatocellular"},
    {"icd10": "C25", "display": "Carcinoma of Pancreas", "specialty": "oncology", "synonyms": "pancreatic cancer|Ca pancreas"},
    {"icd10": "C61", "display": "Carcinoma of Prostate", "specialty": "oncology", "synonyms": "prostate cancer|Ca prostate|prostatic adenocarcinoma"},
    {"icd10": "C92", "display": "Leukaemia (AML / CML)", "specialty": "oncology", "synonyms": "leukaemia|leukemia|AML|CML|blood cancer"},
    {"icd10": "C83", "display": "Non-Hodgkin Lymphoma", "specialty": "oncology", "synonyms": "NHL|non-Hodgkin lymphoma|lymphoma"},
    {"icd10": "C81", "display": "Hodgkin Lymphoma", "specialty": "oncology", "synonyms": "Hodgkin disease|Hodgkin lymphoma"},
    {"icd10": "C73", "display": "Thyroid Carcinoma", "specialty": "oncology", "synonyms": "thyroid cancer|papillary thyroid|follicular thyroid"},

    # ── Dermatology ───────────────────────────────────────────────────────────
    {"icd10": "L40", "display": "Psoriasis", "specialty": "dermatology", "synonyms": "psoriasis|psoriatic plaque|skin plaques"},
    {"icd10": "L20", "display": "Atopic Dermatitis / Eczema", "specialty": "dermatology", "synonyms": "eczema|atopic dermatitis|atopic eczema|khujli"},
    {"icd10": "L43", "display": "Lichen Planus", "specialty": "dermatology", "synonyms": "lichen planus|LP|lichenoid"},
    {"icd10": "L60", "display": "Nail Disorders / Onychomycosis", "specialty": "dermatology", "synonyms": "nail fungus|onychomycosis|tinea unguium"},
    {"icd10": "B35", "display": "Dermatophytosis (Tinea / Ringworm)", "specialty": "dermatology", "synonyms": "ringworm|tinea|fungal infection|daad khaj"},
    {"icd10": "L50", "display": "Urticaria (Hives)", "specialty": "dermatology", "synonyms": "hives|urticaria|allergic rash|pitti"},
    {"icd10": "L70", "display": "Acne Vulgaris", "specialty": "dermatology", "synonyms": "acne|pimples|acne vulgaris|muahaase"},
    {"icd10": "L63", "display": "Alopecia Areata", "specialty": "dermatology", "synonyms": "hair loss patches|alopecia areata|spot baldness"},
    {"icd10": "L65", "display": "Androgenetic Alopecia (Male Pattern Baldness)", "specialty": "dermatology", "synonyms": "male pattern baldness|hair loss|androgenetic alopecia"},
    {"icd10": "A60", "display": "Genital Herpes", "specialty": "dermatology", "synonyms": "herpes genitalis|HSV-2|genital herpes"},
    {"icd10": "A63", "display": "Condylomata Acuminata (Genital Warts)", "specialty": "dermatology", "synonyms": "genital warts|HPV|condyloma"},
    {"icd10": "L51", "display": "Stevens-Johnson Syndrome / Toxic Epidermal Necrolysis", "specialty": "dermatology", "synonyms": "SJS|TEN|drug reaction|toxic epidermal necrolysis"},
    {"icd10": "M32", "display": "Systemic Lupus Erythematosus (SLE)", "specialty": "dermatology", "synonyms": "SLE|lupus|butterfly rash|lupus erythematosus"},
    {"icd10": "L80", "display": "Vitiligo", "specialty": "dermatology", "synonyms": "vitiligo|leucoderma|white patches|phulbehri"},

    # ── Ophthalmology ─────────────────────────────────────────────────────────
    {"icd10": "H26", "display": "Cataract", "specialty": "ophthalmology", "synonyms": "cataract|cloudy lens|motia|cataract surgery"},
    {"icd10": "H40", "display": "Glaucoma", "specialty": "ophthalmology", "synonyms": "glaucoma|raised IOP|open angle glaucoma|kala motia"},
    {"icd10": "H35", "display": "Retinal Disorders", "specialty": "ophthalmology", "synonyms": "retinal degeneration|macular degeneration|AMD|retinopathy"},
    {"icd10": "E11", "display": "Diabetic Retinopathy", "specialty": "ophthalmology", "synonyms": "diabetic retinopathy|DR|diabetic eye disease"},
    {"icd10": "H10", "display": "Conjunctivitis (Pink Eye)", "specialty": "ophthalmology", "synonyms": "pink eye|conjunctivitis|red eye|eye infection|aankh aana"},
    {"icd10": "H52", "display": "Refractive Errors (Myopia / Hyperopia / Astigmatism)", "specialty": "ophthalmology", "synonyms": "myopia|hyperopia|astigmatism|refractive error|power in eye"},
    {"icd10": "H04", "display": "Lacrimal Disorders (Dry Eye / Dacryocystitis)", "specialty": "ophthalmology", "synonyms": "dry eye|dacryocystitis|lacrimal duct obstruction|watering eye"},
    {"icd10": "H11", "display": "Pterygium", "specialty": "ophthalmology", "synonyms": "pterygium|surfer's eye|eye growth"},
    {"icd10": "H02", "display": "Entropion / Ectropion", "specialty": "ophthalmology", "synonyms": "entropion|ectropion|eyelid turned in|eyelid turned out"},
    {"icd10": "H00", "display": "Hordeolum (Stye)", "specialty": "ophthalmology", "synonyms": "stye|hordeolum|eye boil|anjni"},

    # ── Dental ────────────────────────────────────────────────────────────────
    {"icd10": "K02", "display": "Dental Caries (Tooth Decay)", "specialty": "dental", "synonyms": "tooth decay|dental caries|cavity|daant mein kida"},
    {"icd10": "K05", "display": "Gingivitis and Periodontal Disease", "specialty": "dental", "synonyms": "gum disease|gingivitis|periodontitis|pyorrhea"},
    {"icd10": "K08", "display": "Tooth Loss / Edentulous", "specialty": "dental", "synonyms": "tooth loss|edentulous|missing teeth"},
    {"icd10": "K10", "display": "Temporomandibular Joint Disorders (TMJ)", "specialty": "dental", "synonyms": "TMJ|jaw pain|temporomandibular|jaw clicking"},
    {"icd10": "K12", "display": "Stomatitis / Mouth Ulcer", "specialty": "dental", "synonyms": "mouth ulcer|aphthous ulcer|stomatitis|canker sore|munh ka chhala"},
    {"icd10": "K09", "display": "Dental Abscess / Periapical Abscess", "specialty": "dental", "synonyms": "dental abscess|tooth abscess|root abscess|daant mein pus"},

    # ── ENT ───────────────────────────────────────────────────────────────────
    {"icd10": "J30", "display": "Allergic Rhinitis", "specialty": "ent", "synonyms": "hay fever|allergic rhinitis|nasal allergy|running nose allergy"},
    {"icd10": "J31", "display": "Chronic Rhinitis / Sinusitis", "specialty": "ent", "synonyms": "sinusitis|chronic rhinitis|sinus infection|nasal congestion"},
    {"icd10": "J32", "display": "Nasal Polyps / Chronic Sinusitis", "specialty": "ent", "synonyms": "nasal polyp|CRS|chronic sinusitis|polyp nose"},
    {"icd10": "H91", "display": "Sensorineural Hearing Loss", "specialty": "ent", "synonyms": "hearing loss|SNHL|deafness|sensorineural"},
    {"icd10": "H65", "display": "Otitis Media (Ear Infection)", "specialty": "ent", "synonyms": "ear infection|otitis media|middle ear infection|CSOM"},
    {"icd10": "H81", "display": "Vertigo (Vestibular Disorders)", "specialty": "ent", "synonyms": "BPPV|Meniere disease|vertigo|dizziness|chakkar"},
    {"icd10": "J36", "display": "Peritonsillar Abscess", "specialty": "ent", "synonyms": "quinsy|peritonsillar abscess|tonsil abscess"},
    {"icd10": "J38", "display": "Vocal Cord Disorders / Dysphonia", "specialty": "ent", "synonyms": "hoarseness|vocal cord polyp|dysphonia|voice change"},

    # ── Urology ───────────────────────────────────────────────────────────────
    {"icd10": "N40", "display": "Benign Prostatic Hyperplasia (BPH)", "specialty": "urology", "synonyms": "BPH|prostate enlargement|prostatism|urinary obstruction|prostate"},
    {"icd10": "N20", "display": "Urinary Calculi (Kidney / Ureteric Stones)", "specialty": "urology", "synonyms": "kidney stones|urinary calculi|urolithiasis|pathri|ureteric stone"},
    {"icd10": "N39", "display": "Urinary Tract Infection (UTI)", "specialty": "urology", "synonyms": "UTI|cystitis|urinary infection|peshab mein jalan"},
    {"icd10": "C61", "display": "Carcinoma of Prostate", "specialty": "urology", "synonyms": "prostate cancer|Ca prostate|PSA raised"},
    {"icd10": "C67", "display": "Carcinoma of Urinary Bladder", "specialty": "urology", "synonyms": "bladder cancer|Ca bladder|transitional cell carcinoma"},
    {"icd10": "N45", "display": "Orchitis / Epididymo-orchitis", "specialty": "urology", "synonyms": "orchitis|epididymo-orchitis|testicular infection|testis swelling"},
    {"icd10": "N46", "display": "Male Infertility", "specialty": "urology", "synonyms": "male infertility|azoospermia|oligospermia|low sperm"},
    {"icd10": "N48", "display": "Erectile Dysfunction", "specialty": "urology", "synonyms": "ED|erectile dysfunction|impotence|sexual dysfunction"},

    # ── Rheumatology ──────────────────────────────────────────────────────────
    {"icd10": "M05", "display": "Rheumatoid Arthritis (RA)", "specialty": "rheumatology", "synonyms": "RA|rheumatoid arthritis|autoimmune arthritis|joint inflammation"},
    {"icd10": "M10", "display": "Gout", "specialty": "rheumatology", "synonyms": "gout|gouty arthritis|uric acid arthritis|hyperuricaemia"},
    {"icd10": "M32", "display": "Systemic Lupus Erythematosus (SLE)", "specialty": "rheumatology", "synonyms": "SLE|lupus|autoimmune|butterfly rash"},
    {"icd10": "M34", "display": "Systemic Sclerosis (Scleroderma)", "specialty": "rheumatology", "synonyms": "scleroderma|systemic sclerosis|SSc"},
    {"icd10": "M35", "display": "Sjögren Syndrome", "specialty": "rheumatology", "synonyms": "Sjogren syndrome|dry eyes dry mouth|sicca syndrome"},
    {"icd10": "M06", "display": "Seronegative Arthritis", "specialty": "rheumatology", "synonyms": "seronegative RA|undifferentiated arthritis"},
    {"icd10": "M45", "display": "Ankylosing Spondylitis", "specialty": "rheumatology", "synonyms": "ankylosing spondylitis|AS|axial spondyloarthropathy|bamboo spine"},
    {"icd10": "M33", "display": "Dermatomyositis / Polymyositis", "specialty": "rheumatology", "synonyms": "myositis|dermatomyositis|polymyositis|inflammatory muscle"},
    {"icd10": "M79", "display": "Fibromyalgia Syndrome", "specialty": "rheumatology", "synonyms": "fibromyalgia|widespread pain|FMS|tender points"},

    # ── Hematology ────────────────────────────────────────────────────────────
    {"icd10": "D57", "display": "Sickle Cell Disease", "specialty": "hematology", "synonyms": "sickle cell|SCD|sickle cell anaemia|HbSS"},
    {"icd10": "D56", "display": "Thalassaemia", "specialty": "hematology", "synonyms": "thalassaemia|beta thalassaemia|thalassemia|HbH|hemoglobin disorder"},
    {"icd10": "D59", "display": "Autoimmune Haemolytic Anaemia (AIHA)", "specialty": "hematology", "synonyms": "AIHA|haemolytic anaemia|immune haemolysis"},
    {"icd10": "D69", "display": "Immune Thrombocytopenic Purpura (ITP)", "specialty": "hematology", "synonyms": "ITP|thrombocytopenia|low platelets|platelet disorder"},
    {"icd10": "D65", "display": "Disseminated Intravascular Coagulation (DIC)", "specialty": "hematology", "synonyms": "DIC|consumption coagulopathy|clotting disorder"},
    {"icd10": "C91", "display": "Lymphocytic Leukaemia (ALL / CLL)", "specialty": "hematology", "synonyms": "ALL|CLL|lymphocytic leukaemia|blood cancer"},
    {"icd10": "D66", "display": "Haemophilia", "specialty": "hematology", "synonyms": "haemophilia|bleeding disorder|factor VIII deficiency|factor IX"},
    {"icd10": "D68", "display": "Coagulation Defects / Thrombophilia", "specialty": "hematology", "synonyms": "thrombophilia|Factor V Leiden|protein C deficiency|DVT risk"},

    # ── Infectious Disease ────────────────────────────────────────────────────
    {"icd10": "B20", "display": "HIV / AIDS", "specialty": "infectious_disease", "synonyms": "HIV|AIDS|HIV infection|antiretroviral therapy|ART"},
    {"icd10": "A15", "display": "Tuberculosis (TB)", "specialty": "infectious_disease", "synonyms": "TB|tuberculosis|pulmonary TB|extrapulmonary TB|Koch's"},
    {"icd10": "A75", "display": "Typhus Fever / Rickettsial Disease", "specialty": "infectious_disease", "synonyms": "typhus|scrub typhus|rickettsial|spotted fever"},
    {"icd10": "A96", "display": "Leptospirosis", "specialty": "infectious_disease", "synonyms": "leptospirosis|Weil disease|rat fever|lepto"},
    {"icd10": "B55", "display": "Leishmaniasis (Kala-Azar)", "specialty": "infectious_disease", "synonyms": "kala-azar|visceral leishmaniasis|VL|sandfly fever"},
    {"icd10": "B73", "display": "Onchocerciasis / Filariasis", "specialty": "infectious_disease", "synonyms": "filariasis|lymphatic filariasis|elephantiasis|hathipaon"},
    {"icd10": "A97", "display": "Chikungunya", "specialty": "infectious_disease", "synonyms": "chikungunya|chickunguniya|CHIKV|joint fever"},
    {"icd10": "B34", "display": "COVID-19 (SARS-CoV-2 Infection)", "specialty": "infectious_disease", "synonyms": "COVID|COVID-19|coronavirus|SARS-CoV-2"},
    {"icd10": "A50", "display": "Syphilis", "specialty": "infectious_disease", "synonyms": "syphilis|Treponema pallidum|STI syphilis"},
    {"icd10": "A54", "display": "Gonorrhoea", "specialty": "infectious_disease", "synonyms": "gonorrhoea|gonorrhea|gonococcal infection|Neisseria gonorrhoeae"},

    # ── Surgery ───────────────────────────────────────────────────────────────
    {"icd10": "K40", "display": "Inguinal Hernia", "specialty": "surgery", "synonyms": "inguinal hernia|groin hernia|hernia|haddi utarna"},
    {"icd10": "K41", "display": "Femoral Hernia", "specialty": "surgery", "synonyms": "femoral hernia|hernia"},
    {"icd10": "K42", "display": "Umbilical Hernia", "specialty": "surgery", "synonyms": "umbilical hernia|navel hernia|nabhi hernia"},
    {"icd10": "K35", "display": "Acute Appendicitis", "specialty": "surgery", "synonyms": "appendicitis|appendix|appendix pain|periumbilical pain"},
    {"icd10": "L08", "display": "Wound Infection / Abscess", "specialty": "surgery", "synonyms": "wound infection|abscess|cellulitis|surgical site infection"},
    {"icd10": "K64", "display": "Haemorrhoids (Piles)", "specialty": "surgery", "synonyms": "piles|haemorrhoids|hemorrhoids|anal bleeding|bawaseer"},
    {"icd10": "K60", "display": "Fissure-in-Ano", "specialty": "surgery", "synonyms": "anal fissure|fissure in ano|anal pain|rectal fissure"},
    {"icd10": "K61", "display": "Anorectal Abscess / Fistula", "specialty": "surgery", "synonyms": "anorectal fistula|anal fistula|bhagandar|perianal abscess"},
    {"icd10": "T14", "display": "Injury / Trauma (unspecified)", "specialty": "surgery", "synonyms": "trauma|injury|accident|laceration|contusion|chot"},
]
