"""
Safe dose limits for common drugs — used by the CDS engine for max-dose alerts.
Each entry: {generic, route, population, max_single_mg, max_daily_mg, unit, note}
population: adult | pediatric | elderly
"""

DOSE_RANGES = [
    # ── Analgesics ────────────────────────────────────────────────────────────
    {"generic": "Paracetamol", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 4000, "unit": "mg",
     "note": "Max 2g/day in liver disease or alcohol use; 65mg/kg/day absolute max"},
    {"generic": "Paracetamol", "route": "IV", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 4000, "unit": "mg",
     "note": "Reduce to 500mg/dose in patients <50kg; infuse over 15 min"},
    {"generic": "Paracetamol", "route": "oral", "population": "pediatric",
     "max_single_mg": 15, "max_daily_mg": 60, "unit": "mg/kg",
     "note": "15 mg/kg/dose every 4-6 hours; max 4 doses/day"},
    {"generic": "Ibuprofen", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 2400, "unit": "mg",
     "note": "Take with food; avoid in peptic ulcer, renal impairment, CABG"},
    {"generic": "Ibuprofen", "route": "oral", "population": "pediatric",
     "max_single_mg": 10, "max_daily_mg": 40, "unit": "mg/kg",
     "note": "10 mg/kg/dose every 6-8 hours; not for infants under 3 months"},
    {"generic": "Diclofenac", "route": "oral", "population": "adult",
     "max_single_mg": 75, "max_daily_mg": 150, "unit": "mg",
     "note": "Divide into 2-3 doses; take with food; use with PPI"},
    {"generic": "Diclofenac", "route": "IM", "population": "adult",
     "max_single_mg": 75, "max_daily_mg": 150, "unit": "mg",
     "note": "IM only for acute pain; max 2 days IM; rotate sites"},
    {"generic": "Aspirin", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 4000, "unit": "mg",
     "note": "Antiplatelet dose 75-150mg/day; antipyretic/anti-inflammatory dose higher; avoid in children (<16y) — Reye syndrome risk"},
    {"generic": "Tramadol", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 400, "unit": "mg",
     "note": "Reduce to 200mg/day in elderly or renal impairment; seizure risk at high doses"},
    {"generic": "Tramadol", "route": "IV", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 400, "unit": "mg",
     "note": "Infuse IV slowly over at least 15 min; reduce dose in renal/hepatic impairment"},
    {"generic": "Morphine", "route": "IV", "population": "adult",
     "max_single_mg": 15, "max_daily_mg": 120, "unit": "mg",
     "note": "Titrate to effect in pain; higher doses used in palliative care under specialist supervision"},
    {"generic": "Ketorolac", "route": "IM", "population": "adult",
     "max_single_mg": 30, "max_daily_mg": 120, "unit": "mg",
     "note": "Max 5 days use; reduce to 15mg/dose in elderly or renal impairment"},
    {"generic": "Mefenamic Acid", "route": "oral", "population": "adult",
     "max_single_mg": 500, "max_daily_mg": 1500, "unit": "mg",
     "note": "Take with food; not for more than 7 days; avoid in renal impairment"},

    # ── Antibiotics ───────────────────────────────────────────────────────────
    {"generic": "Amoxicillin", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 3000, "unit": "mg",
     "note": "3g/day for most infections; up to 6g/day IV in severe infection"},
    {"generic": "Amoxicillin-Clavulanate", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 3000, "unit": "mg",
     "note": "Based on amoxicillin component; 625mg TDS or 1000mg BD (875/125mg)"},
    {"generic": "Azithromycin", "route": "oral", "population": "adult",
     "max_single_mg": 500, "max_daily_mg": 500, "unit": "mg",
     "note": "Once daily dosing; 500mg day 1, 250mg days 2-5 for community infections"},
    {"generic": "Ciprofloxacin", "route": "oral", "population": "adult",
     "max_single_mg": 750, "max_daily_mg": 1500, "unit": "mg",
     "note": "750mg BD for severe infections; avoid with antacids (chelation)"},
    {"generic": "Levofloxacin", "route": "oral", "population": "adult",
     "max_single_mg": 750, "max_daily_mg": 750, "unit": "mg",
     "note": "Once daily dosing; 500mg/day for mild infections; 750mg for CAP, complicated UTI"},
    {"generic": "Doxycycline", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 200, "unit": "mg",
     "note": "Loading dose 200mg day 1; then 100mg/day; take with food; avoid in pregnancy"},
    {"generic": "Metronidazole", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 2400, "unit": "mg",
     "note": "400-800mg TDS for anaerobic infections; 2g single dose for BV/trichomoniasis"},
    {"generic": "Ceftriaxone", "route": "IV", "population": "adult",
     "max_single_mg": 2000, "max_daily_mg": 4000, "unit": "mg",
     "note": "1-2g once daily for most infections; up to 4g/day in meningitis"},
    {"generic": "Cefuroxime", "route": "oral", "population": "adult",
     "max_single_mg": 500, "max_daily_mg": 1000, "unit": "mg",
     "note": "Take with food; 250-500mg BD"},
    {"generic": "Vancomycin", "route": "IV", "population": "adult",
     "max_single_mg": 2000, "max_daily_mg": 4000, "unit": "mg",
     "note": "15-20 mg/kg every 8-12 hours; infuse over 60+ minutes; monitor troughs; dose in renal impairment"},

    # ── Antidiabetics ─────────────────────────────────────────────────────────
    {"generic": "Metformin", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 2000, "unit": "mg",
     "note": "Start 500mg BD with meals; max 2500mg/day by BNF; reduce in eGFR 30-45; hold if eGFR <30"},
    {"generic": "Glibenclamide", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 15, "unit": "mg",
     "note": "High hypoglycaemia risk; avoid in elderly; take with first bite of meal"},
    {"generic": "Glimepiride", "route": "oral", "population": "adult",
     "max_single_mg": 4, "max_daily_mg": 8, "unit": "mg",
     "note": "Start 1-2mg once daily with breakfast; titrate cautiously"},
    {"generic": "Gliclazide", "route": "oral", "population": "adult",
     "max_single_mg": 120, "max_daily_mg": 240, "unit": "mg",
     "note": "MR formulation: 30-120mg once daily with breakfast; preferred in elderly"},
    {"generic": "Sitagliptin", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 100, "unit": "mg",
     "note": "Once daily; reduce to 50mg in moderate renal impairment (eGFR 30-45); 25mg if eGFR <30"},

    # ── Antihypertensives ─────────────────────────────────────────────────────
    {"generic": "Amlodipine", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 10, "unit": "mg",
     "note": "Start 5mg once daily; max 10mg/day; lower doses in elderly or hepatic impairment"},
    {"generic": "Enalapril", "route": "oral", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 40, "unit": "mg",
     "note": "Start 5mg once daily; max 40mg/day (BD dosing); reduce in renal impairment"},
    {"generic": "Ramipril", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 10, "unit": "mg",
     "note": "Start 2.5mg once daily; max 10mg/day; first dose may cause hypotension"},
    {"generic": "Losartan", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 100, "unit": "mg",
     "note": "Start 50mg once daily; max 100mg/day; 25mg in volume-depleted patients"},
    {"generic": "Atenolol", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 100, "unit": "mg",
     "note": "25-100mg once daily; reduce in renal impairment; do not stop abruptly"},
    {"generic": "Metoprolol", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 400, "unit": "mg",
     "note": "Tartrate: 50-200mg BD; succinate (XL): 25-200mg once daily"},
    {"generic": "Furosemide", "route": "oral", "population": "adult",
     "max_single_mg": 80, "max_daily_mg": 600, "unit": "mg",
     "note": "Heart failure: 20-80mg once/twice daily; resistant oedema: up to 600mg/day"},
    {"generic": "Furosemide", "route": "IV", "population": "adult",
     "max_single_mg": 250, "max_daily_mg": 1000, "unit": "mg",
     "note": "Infuse at max 4mg/min; large doses as infusion; monitor electrolytes"},
    {"generic": "Hydrochlorothiazide", "route": "oral", "population": "adult",
     "max_single_mg": 50, "max_daily_mg": 50, "unit": "mg",
     "note": "12.5-25mg once daily for hypertension; 50mg for oedema"},

    # ── Cardiac ───────────────────────────────────────────────────────────────
    {"generic": "Digoxin", "route": "oral", "population": "adult",
     "max_single_mg": 0.25, "max_daily_mg": 0.25, "unit": "mg",
     "note": "Therapeutic range 0.5-2 ng/mL; reduce in elderly and renal impairment; 125mcg in most patients"},
    {"generic": "Amiodarone", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 400, "unit": "mg",
     "note": "Loading: 200mg TDS for 1 week, then BD for 1 week; maintenance: 100-200mg/day"},
    {"generic": "Warfarin", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 10, "unit": "mg",
     "note": "Dose highly variable; titrate to INR 2-3 (or 2.5-3.5 for mechanical valves); weekly INR monitoring initially"},

    # ── GI ────────────────────────────────────────────────────────────────────
    {"generic": "Omeprazole", "route": "oral", "population": "adult",
     "max_single_mg": 40, "max_daily_mg": 80, "unit": "mg",
     "note": "Standard dose 20mg once daily; 40mg for GERD; H.pylori eradication 20mg BD"},
    {"generic": "Pantoprazole", "route": "oral", "population": "adult",
     "max_single_mg": 40, "max_daily_mg": 80, "unit": "mg",
     "note": "20-40mg once daily; 40mg BD for Zollinger-Ellison"},
    {"generic": "Ondansetron", "route": "oral", "population": "adult",
     "max_single_mg": 8, "max_daily_mg": 24, "unit": "mg",
     "note": "4-8mg up to 3 times daily; reduce dose in moderate/severe hepatic impairment"},
    {"generic": "Metoclopramide", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 30, "unit": "mg",
     "note": "10mg TDS; max 5 days duration (tardive dyskinesia risk); avoid in young women"},

    # ── Respiratory ───────────────────────────────────────────────────────────
    {"generic": "Salbutamol (Albuterol)", "route": "inhaled", "population": "adult",
     "max_single_mg": 0.8, "max_daily_mg": 3.2, "unit": "mg",
     "note": "200mcg (2 puffs) per dose MDI; max 8 puffs/day; nebulised 2.5-5mg per dose"},
    {"generic": "Theophylline", "route": "oral", "population": "adult",
     "max_single_mg": 450, "max_daily_mg": 900, "unit": "mg",
     "note": "Narrow therapeutic index (10-20 mcg/mL); monitor levels; reduce in liver disease, heart failure, elderly"},

    # ── Corticosteroids ───────────────────────────────────────────────────────
    {"generic": "Prednisolone", "route": "oral", "population": "adult",
     "max_single_mg": 60, "max_daily_mg": 60, "unit": "mg",
     "note": "Acute severe inflammation: 40-60mg once daily; taper gradually; higher doses in transplant under specialist"},
    {"generic": "Dexamethasone", "route": "IV", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 40, "unit": "mg",
     "note": "Cerebral oedema: 16mg loading, then 4mg every 6h; septic shock: 6mg/day; meningitis: 0.15mg/kg every 6h for 4 days"},

    # ── Neurological ──────────────────────────────────────────────────────────
    {"generic": "Diazepam", "route": "IV", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 80, "unit": "mg",
     "note": "Status epilepticus: 5-10mg IV; repeat after 10 min if needed; have resuscitation ready"},
    {"generic": "Phenytoin", "route": "IV", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 1500, "unit": "mg",
     "note": "Loading dose: 15-20 mg/kg IV at max 50 mg/min; ECG monitoring required"},
    {"generic": "Carbamazepine", "route": "oral", "population": "adult",
     "max_single_mg": 600, "max_daily_mg": 1600, "unit": "mg",
     "note": "Start 100-200mg BD; increase by 200mg/week; max 1600mg/day in refractory epilepsy"},
    {"generic": "Valproate (Sodium Valproate)", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 2500, "unit": "mg",
     "note": "Start 400mg/day; usual therapeutic dose 1000-2000mg/day; teratogenic - avoid in women of childbearing age"},

    # ── Lithium ───────────────────────────────────────────────────────────────
    {"generic": "Lithium Carbonate", "route": "oral", "population": "adult",
     "max_single_mg": 400, "max_daily_mg": 1200, "unit": "mg",
     "note": "Serum level 0.4-1.0 mmol/L (acute mania 0.8-1.0); narrow therapeutic index; check at 5 days, then monthly"},

    # ── Anticoagulants ────────────────────────────────────────────────────────
    {"generic": "Rivaroxaban", "route": "oral", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 20, "unit": "mg",
     "note": "AF/VTE: 20mg once daily with evening meal; DVT treatment phase: 15mg BD for 21 days; avoid if eGFR <15"},
    {"generic": "Apixaban", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 20, "unit": "mg",
     "note": "DVT treatment: 10mg BD for 7 days, then 5mg BD; AF: 5mg BD (2.5mg BD if ≥2 of: age ≥80, weight ≤60kg, Cr ≥1.5mg/dL)"},
    {"generic": "Clopidogrel", "route": "oral", "population": "adult",
     "max_single_mg": 300, "max_daily_mg": 300, "unit": "mg",
     "note": "Loading: 300mg (ACS: 600mg); maintenance: 75mg once daily"},

    # ── Statins ───────────────────────────────────────────────────────────────
    {"generic": "Atorvastatin", "route": "oral", "population": "adult",
     "max_single_mg": 80, "max_daily_mg": 80, "unit": "mg",
     "note": "Start 10-20mg once daily; high-intensity: 40-80mg; hepatic impairment: avoid; check LFT baseline",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "X"},
    {"generic": "Simvastatin", "route": "oral", "population": "adult",
     "max_single_mg": 40, "max_daily_mg": 40, "unit": "mg",
     "note": "Take in evening; 40mg max with most drugs; 20mg max with amlodipine; avoid grapefruit",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "X"},
    {"generic": "Rosuvastatin", "route": "oral", "population": "adult",
     "max_single_mg": 40, "max_daily_mg": 40, "unit": "mg",
     "note": "Start 10mg once daily; Asian patients start 5mg; max 20mg in severe renal impairment",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "X"},

    # ── Antidepressants / Psychiatric ─────────────────────────────────────────
    {"generic": "Sertraline", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 200, "unit": "mg",
     "note": "Start 25-50mg once daily; increase by 50mg at ≥1-week intervals; max 200mg/day",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Fluoxetine", "route": "oral", "population": "adult",
     "max_single_mg": 60, "max_daily_mg": 60, "unit": "mg",
     "note": "Start 20mg once daily; usual dose 20-40mg; max 60mg for bulimia; long half-life — weekly dosing possible",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Escitalopram", "route": "oral", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 20, "unit": "mg",
     "note": "10mg once daily; max 10mg in elderly or hepatic impairment; max 20mg in others",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Amitriptyline", "route": "oral", "population": "adult",
     "max_single_mg": 150, "max_daily_mg": 150, "unit": "mg",
     "note": "Depression: 75-150mg at night; neuropathic pain: 10-75mg; anticholinergic effects; avoid in cardiac disease",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Haloperidol", "route": "oral", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 20, "unit": "mg",
     "note": "Start 0.5-5mg BD/TDS; maintenance 1-10mg/day; reduce in elderly; monitor QTc; EPSE risk",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Clozapine", "route": "oral", "population": "adult",
     "max_single_mg": 450, "max_daily_mg": 900, "unit": "mg",
     "note": "Specialist initiation only; start 12.5mg, titrate slowly; mandatory WBC monitoring; seizure risk at >600mg",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "B"},
    {"generic": "Olanzapine", "route": "oral", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 20, "unit": "mg",
     "note": "Start 5-10mg once daily; usual 10-15mg; max 20mg; metabolic monitoring required",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},

    # ── Anxiolytics / Sleep ───────────────────────────────────────────────────
    {"generic": "Diazepam", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 30, "unit": "mg",
     "note": "Anxiety: 2-10mg TDS-QID; muscle relaxant: 5-10mg TDS; limit to 2-4 weeks; dependence risk",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "D"},
    {"generic": "Lorazepam", "route": "oral", "population": "adult",
     "max_single_mg": 4, "max_daily_mg": 10, "unit": "mg",
     "note": "1-2mg BD-TDS; IV for status epilepticus 4mg; avoid long-term use",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "D"},
    {"generic": "Midazolam", "route": "IV", "population": "adult",
     "max_single_mg": 5, "max_daily_mg": 30, "unit": "mg",
     "note": "Procedural sedation: 1-2.5mg IV titrated; reduce dose in elderly; have flumazenil ready",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "D"},

    # ── Thyroid ───────────────────────────────────────────────────────────────
    {"generic": "Levothyroxine", "route": "oral", "population": "adult",
     "max_single_mg": 0.3, "max_daily_mg": 0.3, "unit": "mg",
     "note": "Start 50mcg once daily (25mcg in elderly/cardiac); increase by 25mcg every 4-6 weeks; take on empty stomach",
     "renal_adjustment": False, "hepatic_adjustment": False, "pregnancy_category": "A"},
    {"generic": "Carbimazole", "route": "oral", "population": "adult",
     "max_single_mg": 40, "max_daily_mg": 40, "unit": "mg",
     "note": "Initial: 20-40mg/day; titrate to euthyroid; monitor FBC — agranulocytosis risk",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "D"},

    # ── Anticoagulants (additional) ───────────────────────────────────────────
    {"generic": "Enoxaparin", "route": "SC", "population": "adult",
     "max_single_mg": 120, "max_daily_mg": 240, "unit": "mg",
     "note": "DVT prophylaxis: 40mg SC once daily; treatment: 1mg/kg BD or 1.5mg/kg once daily; reduce in eGFR <30",
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "B"},
    {"generic": "Heparin", "route": "IV", "population": "adult",
     "max_single_mg": None, "max_daily_mg": None, "unit": "units",
     "note": "Therapeutic: 5000u bolus, then infuse 1000-2000 u/hr adjusted to APTT 1.5-2.5x control; lab-guided dosing",
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "C"},

    # ── Antifungals ───────────────────────────────────────────────────────────
    {"generic": "Fluconazole", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 800, "unit": "mg",
     "note": "Candidiasis: 150mg single dose; 200-400mg/day for systemic infection; 800mg loading for cryptococcal meningitis",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "D"},
    {"generic": "Itraconazole", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 400, "unit": "mg",
     "note": "Take with food (capsules) or without food (oral solution); 200mg BD for serious infections",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},

    # ── Antivirals ────────────────────────────────────────────────────────────
    {"generic": "Acyclovir", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 4000, "unit": "mg",
     "note": "Herpes simplex: 200-400mg 5x/day; Zoster: 800mg 5x/day for 7 days; reduce in renal impairment",
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "B"},
    {"generic": "Acyclovir", "route": "IV", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 30, "unit": "mg/kg",
     "note": "5-10mg/kg every 8h; infuse over 1 hour; ensure adequate hydration; adjust in renal impairment",
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "B",
     "pediatric_dose_mg_kg_min": 5, "pediatric_dose_mg_kg_max": 10},

    # ── Urinary ───────────────────────────────────────────────────────────────
    {"generic": "Tamsulosin", "route": "oral", "population": "adult",
     "max_single_mg": 0.4, "max_daily_mg": 0.8, "unit": "mg",
     "note": "0.4mg once daily after breakfast; max 0.8mg/day; postural hypotension risk; avoid first-dose effect",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "B"},
    {"generic": "Finasteride", "route": "oral", "population": "adult",
     "max_single_mg": 5, "max_daily_mg": 5, "unit": "mg",
     "note": "5mg once daily for BPH; 1mg for androgenic alopecia; PSA halved — double measured PSA for screening",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "X"},

    # ── Iron / Haematinics ────────────────────────────────────────────────────
    {"generic": "Ferrous Sulphate", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 600, "unit": "mg",
     "note": "200mg elemental iron equivalent per tablet; take on empty stomach; GI side-effects common",
     "renal_adjustment": False, "hepatic_adjustment": False, "pregnancy_category": "A"},
    {"generic": "Iron Sucrose", "route": "IV", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 500, "unit": "mg",
     "note": "200mg per infusion; max 500mg if well tolerated; infuse over 15-30 min; monitor for hypersensitivity",
     "renal_adjustment": False, "hepatic_adjustment": False, "pregnancy_category": "B"},
    {"generic": "Folic Acid", "route": "oral", "population": "adult",
     "max_single_mg": 5, "max_daily_mg": 15, "unit": "mg",
     "note": "Prophylaxis: 400mcg-5mg/day; treatment of deficiency: 5mg OD; pregnancy: 5mg in high-risk, 400mcg routine",
     "renal_adjustment": False, "hepatic_adjustment": False, "pregnancy_category": "A"},

    # ── Gout / Rheumatology ───────────────────────────────────────────────────
    {"generic": "Allopurinol", "route": "oral", "population": "adult",
     "max_single_mg": 300, "max_daily_mg": 900, "unit": "mg",
     "note": "Start 100mg once daily; titrate to target urate <360 µmol/L; reduce in renal impairment; not during acute attack",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Colchicine", "route": "oral", "population": "adult",
     "max_single_mg": 1, "max_daily_mg": 2.5, "unit": "mg",
     "note": "Acute gout: 500mcg 2-4 times daily (not loading-dose regimen in India); GI toxicity; narrow therapeutic index",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Hydroxychloroquine", "route": "oral", "population": "adult",
     "max_single_mg": 400, "max_daily_mg": 400, "unit": "mg",
     "note": "Max 5mg/kg/day (lean body weight); retinal toxicity with long-term use; annual ophthalmology review",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Methotrexate", "route": "oral", "population": "adult",
     "max_single_mg": 25, "max_daily_mg": 25, "unit": "mg",
     "note": "WEEKLY dosing for RA/psoriasis (not daily — fatal error risk); folate supplementation required; LFT/FBC monitoring",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "X"},

    # ── Immunosuppressants ────────────────────────────────────────────────────
    {"generic": "Prednisolone", "route": "oral", "population": "pediatric",
     "max_single_mg": 2, "max_daily_mg": 60, "unit": "mg/kg",
     "note": "1-2mg/kg/day (max 40-60mg); taper over weeks; monitor growth; adrenal suppression risk",
     "pediatric_dose_mg_kg_min": 1, "pediatric_dose_mg_kg_max": 2,
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},

    # ── Antiemetics ───────────────────────────────────────────────────────────
    {"generic": "Domperidone", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 30, "unit": "mg",
     "note": "10mg up to TDS; max 7 days routine use; not to exceed 30mg/day; risk of cardiac arrhythmia at higher doses",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Granisetron", "route": "IV", "population": "adult",
     "max_single_mg": 3, "max_daily_mg": 9, "unit": "mg",
     "note": "1mg IV before chemotherapy (or 3mg as single dose); infuse over 5 min",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "B"},

    # ── Muscle Relaxants ──────────────────────────────────────────────────────
    {"generic": "Baclofen", "route": "oral", "population": "adult",
     "max_single_mg": 25, "max_daily_mg": 80, "unit": "mg",
     "note": "Start 5mg TDS; increase by 15mg every 3 days; max 80mg/day; abrupt withdrawal may cause seizures",
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "C"},
    {"generic": "Tizanidine", "route": "oral", "population": "adult",
     "max_single_mg": 8, "max_daily_mg": 36, "unit": "mg",
     "note": "Start 2mg; titrate to 8mg TDS; max 36mg/day; hepatotoxicity risk — LFT monitoring; reduce in renal impairment",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "C"},

    # ── Paediatric weight-based dosing ────────────────────────────────────────
    {"generic": "Amoxicillin", "route": "oral", "population": "pediatric",
     "max_single_mg": 30, "max_daily_mg": 90, "unit": "mg/kg",
     "note": "25-45mg/kg/day divided TDS; for severe infection up to 90mg/kg/day; max single dose 500mg",
     "pediatric_dose_mg_kg_min": 25, "pediatric_dose_mg_kg_max": 90,
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "B"},
    {"generic": "Ceftriaxone", "route": "IV", "population": "pediatric",
     "max_single_mg": 50, "max_daily_mg": 100, "unit": "mg/kg",
     "note": "50mg/kg once daily (max 2g); meningitis: 100mg/kg/day (max 4g); neonates: 20-50mg/kg once daily",
     "pediatric_dose_mg_kg_min": 50, "pediatric_dose_mg_kg_max": 100,
     "renal_adjustment": False, "hepatic_adjustment": False, "pregnancy_category": "B"},
    {"generic": "Azithromycin", "route": "oral", "population": "pediatric",
     "max_single_mg": 10, "max_daily_mg": 10, "unit": "mg/kg",
     "note": "10mg/kg day 1 (max 500mg), then 5mg/kg days 2-5; or 30mg/kg single dose",
     "pediatric_dose_mg_kg_min": 5, "pediatric_dose_mg_kg_max": 10,
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "B"},
    {"generic": "Metronidazole", "route": "oral", "population": "pediatric",
     "max_single_mg": 15, "max_daily_mg": 40, "unit": "mg/kg",
     "note": "7.5mg/kg every 8h (anaerobic); amoebiasis: 35-50mg/kg/day divided TDS for 5-10 days",
     "pediatric_dose_mg_kg_min": 7.5, "pediatric_dose_mg_kg_max": 15,
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "B"},
    {"generic": "Ondansetron", "route": "IV", "population": "pediatric",
     "max_single_mg": 0.15, "max_daily_mg": 0.45, "unit": "mg/kg",
     "note": "0.1-0.15mg/kg every 8h (max 4mg/dose); infuse over 15 min; QTc monitoring",
     "pediatric_dose_mg_kg_min": 0.1, "pediatric_dose_mg_kg_max": 0.15,
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "B"},
    {"generic": "Salbutamol (Albuterol)", "route": "inhaled", "population": "pediatric",
     "max_single_mg": 0.15, "max_daily_mg": 0.6, "unit": "mg/kg",
     "note": "Nebulised: 0.15mg/kg (min 2.5mg, max 5mg) every 20 min for acute asthma; MDI: 100-200mcg per dose",
     "pediatric_dose_mg_kg_min": 0.05, "pediatric_dose_mg_kg_max": 0.15,
     "renal_adjustment": False, "hepatic_adjustment": False, "pregnancy_category": "C"},
    {"generic": "Diazepam", "route": "IV", "population": "pediatric",
     "max_single_mg": 0.3, "max_daily_mg": 0.75, "unit": "mg/kg",
     "note": "Status epilepticus: 0.2-0.3mg/kg IV (max 10mg); may repeat once after 5 min",
     "pediatric_dose_mg_kg_min": 0.2, "pediatric_dose_mg_kg_max": 0.3,
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "D"},
    {"generic": "Morphine", "route": "IV", "population": "pediatric",
     "max_single_mg": 0.1, "max_daily_mg": 0.4, "unit": "mg/kg",
     "note": "0.05-0.1mg/kg/dose every 2-4h; neonates: 0.025-0.05mg/kg; have naloxone available",
     "pediatric_dose_mg_kg_min": 0.05, "pediatric_dose_mg_kg_max": 0.1,
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Vancomycin", "route": "IV", "population": "pediatric",
     "max_single_mg": 15, "max_daily_mg": 60, "unit": "mg/kg",
     "note": "15mg/kg every 6h (neonates every 8-24h depending on gestational age); AUC-guided monitoring preferred",
     "pediatric_dose_mg_kg_min": 10, "pediatric_dose_mg_kg_max": 15,
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "C"},
    {"generic": "Phenytoin", "route": "IV", "population": "pediatric",
     "max_single_mg": 20, "max_daily_mg": 20, "unit": "mg/kg",
     "note": "Loading: 15-20mg/kg IV at max 1mg/kg/min; maintenance 5-8mg/kg/day divided BD",
     "pediatric_dose_mg_kg_min": 15, "pediatric_dose_mg_kg_max": 20,
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "D"},

    # ── Elderly-specific dose adjustments ─────────────────────────────────────
    {"generic": "Metformin", "route": "oral", "population": "elderly",
     "max_single_mg": 500, "max_daily_mg": 1500, "unit": "mg",
     "note": "Max 1500mg/day in elderly; monitor eGFR every 6 months; hold if eGFR <45",
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "B"},
    {"generic": "Digoxin", "route": "oral", "population": "elderly",
     "max_single_mg": 0.125, "max_daily_mg": 0.125, "unit": "mg",
     "note": "62.5-125mcg/day in elderly; reduced renal clearance; target lower serum level 0.5-0.9 ng/mL",
     "renal_adjustment": True, "hepatic_adjustment": False, "pregnancy_category": "C"},
    {"generic": "Tramadol", "route": "oral", "population": "elderly",
     "max_single_mg": 50, "max_daily_mg": 200, "unit": "mg",
     "note": "50mg BD-TDS max in elderly; increased risk of confusion, falls, serotonin syndrome",
     "renal_adjustment": True, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Haloperidol", "route": "oral", "population": "elderly",
     "max_single_mg": 2, "max_daily_mg": 5, "unit": "mg",
     "note": "0.5-1mg once/twice daily max in elderly; increased stroke and mortality risk in dementia patients",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "C"},
    {"generic": "Ondansetron", "route": "IV", "population": "elderly",
     "max_single_mg": 8, "max_daily_mg": 16, "unit": "mg",
     "note": "Max single dose 8mg in elderly; infuse 8mg over 15 min; QTc monitoring",
     "renal_adjustment": False, "hepatic_adjustment": True, "pregnancy_category": "B"},
]
