"""
Safe dose limits for common drugs — used by the CDS engine for max-dose alerts.
Each entry: {generic, route, population, max_single_mg, max_daily_mg, unit, note}
population: adult | pediatric | elderly
"""

DOSE_RANGES = [
    # ── Analgesics ────────────────────────────────────────────────────────────
    {"generic": "Paracetamol", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 4000, "unit": "mg",
     "note": "Max 2g/day in liver disease or alcohol use; 65mg/kg/day absolute max"},
    {"generic": "Paracetamol", "route": "IV", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 4000, "unit": "mg",
     "note": "Reduce to 500mg/dose in patients <50kg; infuse over 15 min"},
    {"generic": "Paracetamol", "route": "oral", "population": "pediatric",
     "max_single_mg": 15, "max_daily_mg": 60, "unit": "mg/kg",
     "note": "15 mg/kg/dose every 4-6 hours; max 4 doses/day"},
    {"generic": "Ibuprofen", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 2400, "unit": "mg",
     "note": "Take with food; avoid in peptic ulcer, renal impairment, CABG"},
    {"generic": "Ibuprofen", "route": "oral", "population": "pediatric",
     "max_single_mg": 10, "max_daily_mg": 40, "unit": "mg/kg",
     "note": "10 mg/kg/dose every 6-8 hours; not for infants under 3 months"},
    {"generic": "Diclofenac", "route": "oral", "population": "adult",
     "max_single_mg": 75, "max_daily_mg": 150, "unit": "mg",
     "note": "Divide into 2-3 doses; take with food; use with PPI"},
    {"generic": "Diclofenac", "route": "IM", "population": "adult",
     "max_single_mg": 75, "max_daily_mg": 150, "unit": "mg",
     "note": "IM only for acute pain; max 2 days IM; rotate sites"},
    {"generic": "Aspirin", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 4000, "unit": "mg",
     "note": "Antiplatelet dose 75-150mg/day; antipyretic/anti-inflammatory dose higher; avoid in children (<16y) — Reye syndrome risk"},
    {"generic": "Tramadol", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 400, "unit": "mg",
     "note": "Reduce to 200mg/day in elderly or renal impairment; seizure risk at high doses"},
    {"generic": "Tramadol", "route": "IV", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 400, "unit": "mg",
     "note": "Infuse IV slowly over at least 15 min; reduce dose in renal/hepatic impairment"},
    {"generic": "Morphine", "route": "IV", "population": "adult",
     "max_single_mg": 15, "max_daily_mg": 120, "unit": "mg",
     "note": "Titrate to effect in pain; higher doses used in palliative care under specialist supervision"},
    {"generic": "Ketorolac", "route": "IM", "population": "adult",
     "max_single_mg": 30, "max_daily_mg": 120, "unit": "mg",
     "note": "Max 5 days use; reduce to 15mg/dose in elderly or renal impairment"},
    {"generic": "Mefenamic Acid", "route": "oral", "population": "adult",
     "max_single_mg": 500, "max_daily_mg": 1500, "unit": "mg",
     "note": "Take with food; not for more than 7 days; avoid in renal impairment"},

    # ── Antibiotics ───────────────────────────────────────────────────────────
    {"generic": "Amoxicillin", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 3000, "unit": "mg",
     "note": "3g/day for most infections; up to 6g/day IV in severe infection"},
    {"generic": "Amoxicillin-Clavulanate", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 3000, "unit": "mg",
     "note": "Based on amoxicillin component; 625mg TDS or 1000mg BD (875/125mg)"},
    {"generic": "Azithromycin", "route": "oral", "population": "adult",
     "max_single_mg": 500, "max_daily_mg": 500, "unit": "mg",
     "note": "Once daily dosing; 500mg day 1, 250mg days 2-5 for community infections"},
    {"generic": "Ciprofloxacin", "route": "oral", "population": "adult",
     "max_single_mg": 750, "max_daily_mg": 1500, "unit": "mg",
     "note": "750mg BD for severe infections; avoid with antacids (chelation)"},
    {"generic": "Levofloxacin", "route": "oral", "population": "adult",
     "max_single_mg": 750, "max_daily_mg": 750, "unit": "mg",
     "note": "Once daily dosing; 500mg/day for mild infections; 750mg for CAP, complicated UTI"},
    {"generic": "Doxycycline", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 200, "unit": "mg",
     "note": "Loading dose 200mg day 1; then 100mg/day; take with food; avoid in pregnancy"},
    {"generic": "Metronidazole", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 2400, "unit": "mg",
     "note": "400-800mg TDS for anaerobic infections; 2g single dose for BV/trichomoniasis"},
    {"generic": "Ceftriaxone", "route": "IV", "population": "adult",
     "max_single_mg": 2000, "max_daily_mg": 4000, "unit": "mg",
     "note": "1-2g once daily for most infections; up to 4g/day in meningitis"},
    {"generic": "Cefuroxime", "route": "oral", "population": "adult",
     "max_single_mg": 500, "max_daily_mg": 1000, "unit": "mg",
     "note": "Take with food; 250-500mg BD"},
    {"generic": "Vancomycin", "route": "IV", "population": "adult",
     "max_single_mg": 2000, "max_daily_mg": 4000, "unit": "mg",
     "note": "15-20 mg/kg every 8-12 hours; infuse over 60+ minutes; monitor troughs; dose in renal impairment"},

    # ── Antidiabetics ─────────────────────────────────────────────────────────
    {"generic": "Metformin", "route": "oral", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 2000, "unit": "mg",
     "note": "Start 500mg BD with meals; max 2500mg/day by BNF; reduce in eGFR 30-45; hold if eGFR <30"},
    {"generic": "Glibenclamide", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 15, "unit": "mg",
     "note": "High hypoglycaemia risk; avoid in elderly; take with first bite of meal"},
    {"generic": "Glimepiride", "route": "oral", "population": "adult",
     "max_single_mg": 4, "max_daily_mg": 8, "unit": "mg",
     "note": "Start 1-2mg once daily with breakfast; titrate cautiously"},
    {"generic": "Gliclazide", "route": "oral", "population": "adult",
     "max_single_mg": 120, "max_daily_mg": 240, "unit": "mg",
     "note": "MR formulation: 30-120mg once daily with breakfast; preferred in elderly"},
    {"generic": "Sitagliptin", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 100, "unit": "mg",
     "note": "Once daily; reduce to 50mg in moderate renal impairment (eGFR 30-45); 25mg if eGFR <30"},

    # ── Antihypertensives ─────────────────────────────────────────────────────
    {"generic": "Amlodipine", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 10, "unit": "mg",
     "note": "Start 5mg once daily; max 10mg/day; lower doses in elderly or hepatic impairment"},
    {"generic": "Enalapril", "route": "oral", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 40, "unit": "mg",
     "note": "Start 5mg once daily; max 40mg/day (BD dosing); reduce in renal impairment"},
    {"generic": "Ramipril", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 10, "unit": "mg",
     "note": "Start 2.5mg once daily; max 10mg/day; first dose may cause hypotension"},
    {"generic": "Losartan", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 100, "unit": "mg",
     "note": "Start 50mg once daily; max 100mg/day; 25mg in volume-depleted patients"},
    {"generic": "Atenolol", "route": "oral", "population": "adult",
     "max_single_mg": 100, "max_daily_mg": 100, "unit": "mg",
     "note": "25-100mg once daily; reduce in renal impairment; do not stop abruptly"},
    {"generic": "Metoprolol", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 400, "unit": "mg",
     "note": "Tartrate: 50-200mg BD; succinate (XL): 25-200mg once daily"},
    {"generic": "Furosemide", "route": "oral", "population": "adult",
     "max_single_mg": 80, "max_daily_mg": 600, "unit": "mg",
     "note": "Heart failure: 20-80mg once/twice daily; resistant oedema: up to 600mg/day"},
    {"generic": "Furosemide", "route": "IV", "population": "adult",
     "max_single_mg": 250, "max_daily_mg": 1000, "unit": "mg",
     "note": "Infuse at max 4mg/min; large doses as infusion; monitor electrolytes"},
    {"generic": "Hydrochlorothiazide", "route": "oral", "population": "adult",
     "max_single_mg": 50, "max_daily_mg": 50, "unit": "mg",
     "note": "12.5-25mg once daily for hypertension; 50mg for oedema"},

    # ── Cardiac ───────────────────────────────────────────────────────────────
    {"generic": "Digoxin", "route": "oral", "population": "adult",
     "max_single_mg": 0.25, "max_daily_mg": 0.25, "unit": "mg",
     "note": "Therapeutic range 0.5-2 ng/mL; reduce in elderly and renal impairment; 125mcg in most patients"},
    {"generic": "Amiodarone", "route": "oral", "population": "adult",
     "max_single_mg": 200, "max_daily_mg": 400, "unit": "mg",
     "note": "Loading: 200mg TDS for 1 week, then BD for 1 week; maintenance: 100-200mg/day"},
    {"generic": "Warfarin", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 10, "unit": "mg",
     "note": "Dose highly variable; titrate to INR 2-3 (or 2.5-3.5 for mechanical valves); weekly INR monitoring initially"},

    # ── GI ────────────────────────────────────────────────────────────────────
    {"generic": "Omeprazole", "route": "oral", "population": "adult",
     "max_single_mg": 40, "max_daily_mg": 80, "unit": "mg",
     "note": "Standard dose 20mg once daily; 40mg for GERD; H.pylori eradication 20mg BD"},
    {"generic": "Pantoprazole", "route": "oral", "population": "adult",
     "max_single_mg": 40, "max_daily_mg": 80, "unit": "mg",
     "note": "20-40mg once daily; 40mg BD for Zollinger-Ellison"},
    {"generic": "Ondansetron", "route": "oral", "population": "adult",
     "max_single_mg": 8, "max_daily_mg": 24, "unit": "mg",
     "note": "4-8mg up to 3 times daily; reduce dose in moderate/severe hepatic impairment"},
    {"generic": "Metoclopramide", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 30, "unit": "mg",
     "note": "10mg TDS; max 5 days duration (tardive dyskinesia risk); avoid in young women"},

    # ── Respiratory ───────────────────────────────────────────────────────────
    {"generic": "Salbutamol (Albuterol)", "route": "inhaled", "population": "adult",
     "max_single_mg": 0.8, "max_daily_mg": 3.2, "unit": "mg",
     "note": "200mcg (2 puffs) per dose MDI; max 8 puffs/day; nebulised 2.5-5mg per dose"},
    {"generic": "Theophylline", "route": "oral", "population": "adult",
     "max_single_mg": 450, "max_daily_mg": 900, "unit": "mg",
     "note": "Narrow therapeutic index (10-20 mcg/mL); monitor levels; reduce in liver disease, heart failure, elderly"},

    # ── Corticosteroids ───────────────────────────────────────────────────────
    {"generic": "Prednisolone", "route": "oral", "population": "adult",
     "max_single_mg": 60, "max_daily_mg": 60, "unit": "mg",
     "note": "Acute severe inflammation: 40-60mg once daily; taper gradually; higher doses in transplant under specialist"},
    {"generic": "Dexamethasone", "route": "IV", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 40, "unit": "mg",
     "note": "Cerebral oedema: 16mg loading, then 4mg every 6h; septic shock: 6mg/day; meningitis: 0.15mg/kg every 6h for 4 days"},

    # ── Neurological ──────────────────────────────────────────────────────────
    {"generic": "Diazepam", "route": "IV", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 80, "unit": "mg",
     "note": "Status epilepticus: 5-10mg IV; repeat after 10 min if needed; have resuscitation ready"},
    {"generic": "Phenytoin", "route": "IV", "population": "adult",
     "max_single_mg": 1000, "max_daily_mg": 1500, "unit": "mg",
     "note": "Loading dose: 15-20 mg/kg IV at max 50 mg/min; ECG monitoring required"},
    {"generic": "Carbamazepine", "route": "oral", "population": "adult",
     "max_single_mg": 600, "max_daily_mg": 1600, "unit": "mg",
     "note": "Start 100-200mg BD; increase by 200mg/week; max 1600mg/day in refractory epilepsy"},
    {"generic": "Valproate (Sodium Valproate)", "route": "oral", "population": "adult",
     "max_single_mg": 800, "max_daily_mg": 2500, "unit": "mg",
     "note": "Start 400mg/day; usual therapeutic dose 1000-2000mg/day; teratogenic - avoid in women of childbearing age"},

    # ── Lithium ───────────────────────────────────────────────────────────────
    {"generic": "Lithium Carbonate", "route": "oral", "population": "adult",
     "max_single_mg": 400, "max_daily_mg": 1200, "unit": "mg",
     "note": "Serum level 0.4-1.0 mmol/L (acute mania 0.8-1.0); narrow therapeutic index; check at 5 days, then monthly"},

    # ── Anticoagulants ────────────────────────────────────────────────────────
    {"generic": "Rivaroxaban", "route": "oral", "population": "adult",
     "max_single_mg": 20, "max_daily_mg": 20, "unit": "mg",
     "note": "AF/VTE: 20mg once daily with evening meal; DVT treatment phase: 15mg BD for 21 days; avoid if eGFR <15"},
    {"generic": "Apixaban", "route": "oral", "population": "adult",
     "max_single_mg": 10, "max_daily_mg": 20, "unit": "mg",
     "note": "DVT treatment: 10mg BD for 7 days, then 5mg BD; AF: 5mg BD (2.5mg BD if ≥2 of: age ≥80, weight ≤60kg, Cr ≥1.5mg/dL)"},
    {"generic": "Clopidogrel", "route": "oral", "population": "adult",
     "max_single_mg": 300, "max_daily_mg": 300, "unit": "mg",
     "note": "Loading: 300mg (ACS: 600mg); maintenance: 75mg once daily"},
]
