"""
Clinical examination findings — signs, findings, and descriptors.
Used for physical examination documentation and search suggestions.
Format: {display, specialty, synonyms}
"""

EXAM_FINDINGS = [
    # ── Vital sign abnormalities ──────────────────────────────────────────────
    {"display": "Tachycardia", "specialty": "general_medicine", "synonyms": "tachycardia|fast heart rate|HR elevated|pulse fast"},
    {"display": "Bradycardia", "specialty": "general_medicine", "synonyms": "bradycardia|slow heart rate|low pulse|HR low"},
    {"display": "Hypertension (acute)", "specialty": "general_medicine", "synonyms": "high BP|elevated blood pressure|hypertensive"},
    {"display": "Hypotension", "specialty": "general_medicine", "synonyms": "low BP|hypotension|low blood pressure"},
    {"display": "Tachypnoea", "specialty": "general_medicine", "synonyms": "tachypnoea|tachypnea|fast breathing|rapid respiration|RR elevated"},
    {"display": "Bradypnoea", "specialty": "general_medicine", "synonyms": "bradypnoea|slow breathing|RR low"},
    {"display": "Hypoxia / Low SpO2", "specialty": "pulmonology", "synonyms": "hypoxia|desaturation|low oxygen|SpO2 low|oxygen saturation low"},
    {"display": "Fever (Pyrexia)", "specialty": "general_medicine", "synonyms": "fever|pyrexia|elevated temperature|febrile|high temperature"},
    {"display": "Hypothermia", "specialty": "general_medicine", "synonyms": "hypothermia|low temperature|cold"},

    # ── General appearance ────────────────────────────────────────────────────
    {"display": "Pallor", "specialty": "general_medicine", "synonyms": "pallor|pale|anaemic appearance|paleness"},
    {"display": "Icterus (Jaundice)", "specialty": "general_medicine", "synonyms": "icterus|jaundice|yellow skin|yellow eyes|scleral icterus"},
    {"display": "Cyanosis (Central)", "specialty": "general_medicine", "synonyms": "central cyanosis|blue lips|blue tongue|cyanosed"},
    {"display": "Cyanosis (Peripheral)", "specialty": "general_medicine", "synonyms": "peripheral cyanosis|blue fingers|acrocyanosis"},
    {"display": "Oedema (Pedal)", "specialty": "general_medicine", "synonyms": "pedal oedema|leg swelling|ankle swelling|foot swelling|pitting oedema"},
    {"display": "Generalised Oedema", "specialty": "general_medicine", "synonyms": "anasarca|generalised oedema|body swelling|generalised swelling"},
    {"display": "Lymphadenopathy", "specialty": "general_medicine", "synonyms": "lymphadenopathy|enlarged lymph nodes|swollen glands|lymph node swelling"},
    {"display": "Clubbing (Finger clubbing)", "specialty": "general_medicine", "synonyms": "clubbing|finger clubbing|drumstick fingers"},
    {"display": "Koilonychia", "specialty": "general_medicine", "synonyms": "koilonychia|spoon nails|spooning of nails"},
    {"display": "Leukonychia", "specialty": "general_medicine", "synonyms": "leukonychia|white nails|pale nails"},
    {"display": "Asterixis (Flapping tremor)", "specialty": "neurology", "synonyms": "asterixis|flapping tremor|liver flap|metabolic flap"},
    {"display": "Wasting / Muscle atrophy", "specialty": "general_medicine", "synonyms": "wasting|muscle atrophy|cachexia|muscle loss|emaciation"},
    {"display": "Dehydration signs", "specialty": "general_medicine", "synonyms": "dehydration|dry skin|sunken eyes|dry mucosa|skin turgor reduced"},

    # ── Cardiovascular findings ───────────────────────────────────────────────
    {"display": "Murmur (Systolic)", "specialty": "cardiology", "synonyms": "systolic murmur|ejection systolic|pansystolic|heart murmur"},
    {"display": "Murmur (Diastolic)", "specialty": "cardiology", "synonyms": "diastolic murmur|mid-diastolic|heart murmur diastolic"},
    {"display": "S3 Gallop (Third heart sound)", "specialty": "cardiology", "synonyms": "S3 gallop|third heart sound|ventricular gallop"},
    {"display": "S4 Gallop (Fourth heart sound)", "specialty": "cardiology", "synonyms": "S4 gallop|fourth heart sound|atrial gallop"},
    {"display": "Jugular Venous Distension (JVD)", "specialty": "cardiology", "synonyms": "JVD|JVP raised|jugular venous distension|elevated JVP"},
    {"display": "Apex beat displaced", "specialty": "cardiology", "synonyms": "displaced apex|apex shifted|cardiomegaly sign"},
    {"display": "Heave (Parasternal / Apical)", "specialty": "cardiology", "synonyms": "heave|parasternal heave|RV heave|LV heave"},
    {"display": "Thrill (Palpable murmur)", "specialty": "cardiology", "synonyms": "thrill|palpable thrill|cardiac thrill"},
    {"display": "Pulsus paradoxus", "specialty": "cardiology", "synonyms": "pulsus paradoxus|paradoxical pulse|BP variation breathing"},
    {"display": "Weak / Thready pulse", "specialty": "cardiology", "synonyms": "thready pulse|weak pulse|low volume pulse"},
    {"display": "Bounding pulse", "specialty": "cardiology", "synonyms": "bounding pulse|collapsing pulse|water-hammer pulse"},
    {"display": "Irregularly irregular pulse (Atrial fibrillation)", "specialty": "cardiology", "synonyms": "irregular pulse|irregularly irregular|AF pulse|fibrillation pulse"},
    {"display": "Absent peripheral pulses", "specialty": "cardiology", "synonyms": "absent pulse|peripheral vascular disease|no pulse limb"},

    # ── Respiratory findings ──────────────────────────────────────────────────
    {"display": "Wheeze", "specialty": "pulmonology", "synonyms": "wheeze|wheezing|expiratory wheeze|bronchospasm sound"},
    {"display": "Crackles / Crepitations", "specialty": "pulmonology", "synonyms": "crackles|crepitations|rales|fine crackles|coarse crackles"},
    {"display": "Rhonchi", "specialty": "pulmonology", "synonyms": "rhonchi|low-pitched wheeze|bronchial secretions sound"},
    {"display": "Reduced air entry", "specialty": "pulmonology", "synonyms": "reduced air entry|decreased breath sounds|poor air entry"},
    {"display": "Absent breath sounds", "specialty": "pulmonology", "synonyms": "absent breath sounds|no air entry|stony dull"},
    {"display": "Bronchial breathing", "specialty": "pulmonology", "synonyms": "bronchial breathing|tubular breathing|consolidation sound"},
    {"display": "Dullness on percussion (chest)", "specialty": "pulmonology", "synonyms": "dull percussion chest|stony dull|pleural effusion sign"},
    {"display": "Resonant / Hyper-resonant (chest)", "specialty": "pulmonology", "synonyms": "hyper-resonant|resonant chest|pneumothorax sign|hyperinflation"},
    {"display": "Stridor", "specialty": "ent", "synonyms": "stridor|high-pitched breathing|upper airway obstruction sound"},
    {"display": "Use of accessory muscles", "specialty": "pulmonology", "synonyms": "accessory muscle use|intercostal recession|subcostal recession|laboured breathing"},
    {"display": "Pleural friction rub", "specialty": "pulmonology", "synonyms": "pleural rub|friction rub|pleurisy sound"},
    {"display": "Tracheal deviation", "specialty": "pulmonology", "synonyms": "tracheal deviation|trachea shifted|tracheal shift"},

    # ── Abdominal findings ────────────────────────────────────────────────────
    {"display": "Tenderness (RUQ)", "specialty": "gastroenterology", "synonyms": "RUQ tenderness|right upper quadrant pain|gallbladder tenderness"},
    {"display": "Murphy's Sign (positive)", "specialty": "gastroenterology", "synonyms": "Murphy's sign|positive Murphy|cholecystitis sign|gallbladder sign"},
    {"display": "Tenderness (RLQ / McBurney)", "specialty": "gastroenterology", "synonyms": "McBurney tenderness|RLQ tenderness|appendix tenderness|right iliac fossa"},
    {"display": "Rebound Tenderness", "specialty": "gastroenterology", "synonyms": "rebound tenderness|Blumberg sign|peritoneal sign|rebound pain"},
    {"display": "Guarding (Abdominal)", "specialty": "gastroenterology", "synonyms": "guarding|abdominal guarding|muscle guarding|rigidity"},
    {"display": "Rigidity (Board-like abdomen)", "specialty": "gastroenterology", "synonyms": "rigidity|board-like abdomen|generalised rigidity|peritonitis sign"},
    {"display": "Hepatomegaly", "specialty": "gastroenterology", "synonyms": "hepatomegaly|enlarged liver|liver enlarged|palpable liver"},
    {"display": "Splenomegaly", "specialty": "gastroenterology", "synonyms": "splenomegaly|enlarged spleen|spleen enlarged|palpable spleen"},
    {"display": "Ascites", "specialty": "gastroenterology", "synonyms": "ascites|fluid abdomen|ascitic|shifting dullness|fluid thrill"},
    {"display": "Shifting Dullness (Ascites)", "specialty": "gastroenterology", "synonyms": "shifting dullness|ascites sign"},
    {"display": "Fluid Thrill", "specialty": "gastroenterology", "synonyms": "fluid thrill|tense ascites sign|fluid wave"},
    {"display": "Palpable mass (abdomen)", "specialty": "gastroenterology", "synonyms": "abdominal mass|palpable lump abdomen|intraabdominal mass"},
    {"display": "Bowel sounds absent", "specialty": "gastroenterology", "synonyms": "absent bowel sounds|ileus|silent abdomen"},
    {"display": "Bowel sounds hyperactive", "specialty": "gastroenterology", "synonyms": "hyperactive bowel sounds|tinkling bowel|obstruction sounds"},
    {"display": "Hernial orifices (Reducible / Irreducible)", "specialty": "surgery", "synonyms": "hernia|reducible hernia|irreducible hernia|inguinal hernia examination"},
    {"display": "Rovsing's Sign (positive)", "specialty": "gastroenterology", "synonyms": "Rovsing sign|appendicitis sign"},
    {"display": "Psoas Sign (positive)", "specialty": "gastroenterology", "synonyms": "psoas sign|retrocaecal appendix sign"},
    {"display": "Obturator Sign", "specialty": "gastroenterology", "synonyms": "obturator sign|pelvic appendix sign"},
    {"display": "Courvoisier's Sign", "specialty": "gastroenterology", "synonyms": "Courvoisier sign|palpable gallbladder jaundice|pancreatic carcinoma sign"},

    # ── Neurological findings ─────────────────────────────────────────────────
    {"display": "GCS score reduced", "specialty": "neurology", "synonyms": "low GCS|reduced consciousness|GCS low|altered sensorium"},
    {"display": "Hemiplegia", "specialty": "neurology", "synonyms": "hemiplegia|one-sided paralysis|unilateral paralysis"},
    {"display": "Hemiparesis", "specialty": "neurology", "synonyms": "hemiparesis|one-sided weakness|unilateral weakness"},
    {"display": "Paraplegia", "specialty": "neurology", "synonyms": "paraplegia|both legs paralysis|lower limb paralysis"},
    {"display": "Monoplegia", "specialty": "neurology", "synonyms": "monoplegia|single limb paralysis"},
    {"display": "Upper motor neuron signs", "specialty": "neurology", "synonyms": "UMN signs|spasticity|hyperreflexia|Babinski positive|extensor plantar"},
    {"display": "Lower motor neuron signs", "specialty": "neurology", "synonyms": "LMN signs|flaccidity|hyporeflexia|areflexia|fasciculations"},
    {"display": "Babinski Sign (positive)", "specialty": "neurology", "synonyms": "Babinski positive|extensor plantar|upgoing plantar|UMN sign"},
    {"display": "Clonus", "specialty": "neurology", "synonyms": "clonus|ankle clonus|sustained clonus|UMN sign"},
    {"display": "Kernig's Sign (positive)", "specialty": "neurology", "synonyms": "Kernig sign|meningeal sign|meningitis sign"},
    {"display": "Brudzinski's Sign (positive)", "specialty": "neurology", "synonyms": "Brudzinski sign|meningeal sign|neck stiffness sign"},
    {"display": "Neck stiffness (Meningism)", "specialty": "neurology", "synonyms": "neck stiffness|nuchal rigidity|meningism|meningeal irritation"},
    {"display": "Romberg's Sign (positive)", "specialty": "neurology", "synonyms": "Romberg positive|sensory ataxia|postural instability"},
    {"display": "Ataxia (Gait)", "specialty": "neurology", "synonyms": "ataxia|cerebellar gait|unsteady gait|staggering"},
    {"display": "Dysarthria", "specialty": "neurology", "synonyms": "dysarthria|slurred speech|speech difficulty|thick speech"},
    {"display": "Aphasia", "specialty": "neurology", "synonyms": "aphasia|speech loss|expressive aphasia|receptive aphasia|Broca Wernicke"},
    {"display": "Nystagmus", "specialty": "neurology", "synonyms": "nystagmus|eye jerking|involuntary eye movement"},
    {"display": "Papilloedema", "specialty": "neurology", "synonyms": "papilloedema|disc swelling|raised ICP sign|optic disc oedema"},
    {"display": "Sensory loss (dermatomal)", "specialty": "neurology", "synonyms": "dermatomal sensory loss|numbness dermatomal|hypoaesthesia"},
    {"display": "Tremor (Resting)", "specialty": "neurology", "synonyms": "resting tremor|pill-rolling tremor|Parkinson tremor"},
    {"display": "Tremor (Intention)", "specialty": "neurology", "synonyms": "intention tremor|cerebellar tremor|action tremor"},
    {"display": "Cogwheel rigidity", "specialty": "neurology", "synonyms": "cogwheel rigidity|lead-pipe rigidity|Parkinson rigidity"},
    {"display": "Power reduced (graded)", "specialty": "neurology", "synonyms": "power reduced|MRC grade|muscle weakness graded|power 0-5"},
    {"display": "Cranial nerve palsy", "specialty": "neurology", "synonyms": "CN palsy|cranial nerve palsy|facial palsy|oculomotor palsy"},

    # ── Musculoskeletal findings ───────────────────────────────────────────────
    {"display": "Joint swelling", "specialty": "orthopedics", "synonyms": "joint swelling|effusion|joint enlarged|synovitis"},
    {"display": "Joint tenderness", "specialty": "orthopedics", "synonyms": "joint tenderness|tender joint|joint painful on palpation"},
    {"display": "Reduced range of motion (ROM)", "specialty": "orthopedics", "synonyms": "reduced ROM|limited movement|restricted range|stiffness"},
    {"display": "Crepitus (joint)", "specialty": "orthopedics", "synonyms": "crepitus|joint crepitus|grating sensation|crackling joint"},
    {"display": "Ligament laxity (positive stress test)", "specialty": "orthopedics", "synonyms": "ligament laxity|positive stress test|ACL laxity|collateral laxity"},
    {"display": "Positive anterior drawer test", "specialty": "orthopedics", "synonyms": "anterior drawer|ACL test|knee instability anterior"},
    {"display": "Positive Lachman test", "specialty": "orthopedics", "synonyms": "Lachman test|ACL Lachman|knee ACL examination"},
    {"display": "Positive McMurray test (Meniscus)", "specialty": "orthopedics", "synonyms": "McMurray test|meniscal test|McMurray positive"},
    {"display": "Positive Finkelstein test (De Quervain)", "specialty": "orthopedics", "synonyms": "Finkelstein test|De Quervain test|wrist tendon test"},
    {"display": "Positive SLRT (Straight leg raise test)", "specialty": "orthopedics", "synonyms": "SLRT|straight leg raise|SLR positive|Lasegue sign|disc prolapse test"},
    {"display": "Wasting (muscle group specific)", "specialty": "orthopedics", "synonyms": "muscle wasting|atrophy specific muscle|quadriceps wasting|thenar wasting"},
    {"display": "Deformity (varus / valgus)", "specialty": "orthopedics", "synonyms": "varus deformity|valgus deformity|bow leg|knock knee|malalignment"},
    {"display": "Shortening of limb", "specialty": "orthopedics", "synonyms": "limb shortening|leg length discrepancy|short limb|LLD"},
    {"display": "Bony tenderness", "specialty": "orthopedics", "synonyms": "bony tenderness|bone tender|point tenderness bone|fracture tenderness"},
    {"display": "Abnormal mobility at fracture site", "specialty": "orthopedics", "synonyms": "fracture mobility|false movement|crepitus fracture|abnormal movement"},

    # ── Endocrine / metabolic signs ───────────────────────────────────────────
    {"display": "Goitre", "specialty": "endocrinology", "synonyms": "goitre|goiter|enlarged thyroid|thyroid swelling|neck swelling midline"},
    {"display": "Exophthalmos (Proptosis)", "specialty": "endocrinology", "synonyms": "exophthalmos|proptosis|bulging eyes|thyroid eye disease|Graves eye"},
    {"display": "Gynaecomastia", "specialty": "endocrinology", "synonyms": "gynaecomastia|gynecomastia|breast tissue male|male breast enlargement"},
    {"display": "Cushingoid features", "specialty": "endocrinology", "synonyms": "Cushingoid|moon face|buffalo hump|centripetal obesity|striae"},
    {"display": "Acromegaly features", "specialty": "endocrinology", "synonyms": "acromegaly|large hands|jaw prognathism|coarse features"},

    # ── Skin findings ─────────────────────────────────────────────────────────
    {"display": "Rash (maculopapular)", "specialty": "dermatology", "synonyms": "maculopapular rash|drug rash|viral rash|skin eruption"},
    {"display": "Petechiae", "specialty": "hematology", "synonyms": "petechiae|pin-point haemorrhages|petechial rash|tiny red spots"},
    {"display": "Purpura", "specialty": "hematology", "synonyms": "purpura|non-blanching rash|bruising small|ITP skin"},
    {"display": "Ecchymosis", "specialty": "general_medicine", "synonyms": "ecchymosis|bruise|bruising|haematoma skin"},
    {"display": "Erythema", "specialty": "dermatology", "synonyms": "erythema|redness|skin erythema|erythematous"},
    {"display": "Urticaria (skin findings)", "specialty": "dermatology", "synonyms": "urticaria|hives|wheals|allergic skin|nettle rash"},
    {"display": "Spider naevi", "specialty": "gastroenterology", "synonyms": "spider naevi|spider angioma|liver palm|liver disease skin"},
    {"display": "Palmer erythema", "specialty": "gastroenterology", "synonyms": "palmar erythema|red palms|liver disease sign"},
    {"display": "Dupuytren's contracture", "specialty": "orthopedics", "synonyms": "Dupuytren's|palmar fibromatosis|ring finger contracture"},
    {"display": "Ulcer (skin)", "specialty": "dermatology", "synonyms": "skin ulcer|wound ulcer|chronic ulcer|trophic ulcer|diabetic ulcer"},
    {"display": "Pressure sore / Decubitus ulcer", "specialty": "general_medicine", "synonyms": "bedsore|pressure sore|decubitus|pressure ulcer|pressure injury"},

    # ── HEENT findings ────────────────────────────────────────────────────────
    {"display": "Anaemia of conjunctiva (Conjunctival pallor)", "specialty": "general_medicine", "synonyms": "conjunctival pallor|pale conjunctiva|anaemia sign eyes"},
    {"display": "Fundus changes (Papilloedema / Hypertensive / Diabetic)", "specialty": "ophthalmology", "synonyms": "fundus changes|retinopathy|hypertensive retinopathy|diabetic retinopathy"},
    {"display": "Tonsillar enlargement (Grading)", "specialty": "ent", "synonyms": "tonsil enlargement|tonsil size grading|tonsillar hypertrophy"},
    {"display": "Pharyngeal congestion", "specialty": "ent", "synonyms": "pharyngeal congestion|throat redness|pharyngitis finding|posterior pharyngeal wall"},
    {"display": "Ear drum (Tympanic membrane) perforation", "specialty": "ent", "synonyms": "TM perforation|ear drum hole|tympanic membrane perforation|CSOM finding"},
    {"display": "Cervical lymphadenopathy", "specialty": "ent", "synonyms": "neck nodes|cervical nodes|tonsillar nodes|submandibular nodes"},

    # ── Renal / Urological ────────────────────────────────────────────────────
    {"display": "Renal angle tenderness (CVA tenderness)", "specialty": "nephrology", "synonyms": "renal angle tenderness|CVA tenderness|loin tenderness|costovertebral angle"},
    {"display": "Ballotable kidney", "specialty": "nephrology", "synonyms": "ballotable kidney|palpable kidney|ballot kidney|enlarged kidney"},
    {"display": "Suprapubic tenderness", "specialty": "urology", "synonyms": "suprapubic tenderness|bladder tenderness|lower abdomen midline tender"},

    # ── Gynaecological / Obstetric ────────────────────────────────────────────
    {"display": "Uterus size (weeks equivalent)", "specialty": "obstetrics/gynecology", "synonyms": "uterus size|uterine size|weeks size|gravid uterus|fundal height"},
    {"display": "Fetal heart sounds (FHS)", "specialty": "obstetrics/gynecology", "synonyms": "FHS|fetal heart sounds|baby heartbeat|fetal heart rate"},
    {"display": "Cervical os (open/closed)", "specialty": "obstetrics/gynecology", "synonyms": "cervical os|os open|os closed|cervical dilation"},
    {"display": "Adnexal mass / tenderness", "specialty": "obstetrics/gynecology", "synonyms": "adnexal mass|ovarian mass|adnexal tenderness|parametrial tenderness"},
    {"display": "Cervical motion tenderness (CMT)", "specialty": "obstetrics/gynecology", "synonyms": "CMT|cervical excitation|cervical motion tenderness|PID sign"},
]
