"""
Comprehensive India-priority imaging study catalogue.
Covers X-Ray, Ultrasound, CT, MRI, Nuclear Medicine, Fluoroscopy,
and Interventional Radiology.

Each entry: {name, modality, body_part, category, turnaround_hours, preparation}
"""

IMAGING_STUDIES = [

    # ═══════════════════════════════════════════════════════
    # X-RAY (CR / DX)
    # ═══════════════════════════════════════════════════════
    {"name": "X-Ray Chest PA View", "modality": "CR", "body_part": "Chest", "category": "X-Ray", "turnaround_hours": 1, "preparation": ""},
    {"name": "X-Ray Chest AP View", "modality": "CR", "body_part": "Chest", "category": "X-Ray", "turnaround_hours": 1, "preparation": ""},
    {"name": "X-Ray Chest Lateral View", "modality": "CR", "body_part": "Chest", "category": "X-Ray", "turnaround_hours": 1, "preparation": ""},
    {"name": "X-Ray Abdomen Erect", "modality": "CR", "body_part": "Abdomen", "category": "X-Ray", "turnaround_hours": 1, "preparation": ""},
    {"name": "X-Ray Abdomen Supine", "modality": "CR", "body_part": "Abdomen", "category": "X-Ray", "turnaround_hours": 1, "preparation": ""},
    {"name": "X-Ray KUB (Kidney-Ureter-Bladder)", "modality": "CR", "body_part": "Abdomen", "category": "X-Ray", "turnaround_hours": 1, "preparation": ""},
    {"name": "X-Ray Skull AP & Lateral", "modality": "CR", "body_part": "Skull", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Cervical Spine AP & Lateral", "modality": "CR", "body_part": "Cervical Spine", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Cervical Spine Oblique Views", "modality": "CR", "body_part": "Cervical Spine", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Dorsal Spine AP & Lateral", "modality": "CR", "body_part": "Thoracic Spine", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Lumbar Spine AP & Lateral", "modality": "CR", "body_part": "Lumbar Spine", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Lumbar Spine Flexion-Extension Views", "modality": "CR", "body_part": "Lumbar Spine", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Sacrum & Coccyx", "modality": "CR", "body_part": "Sacrococcyx", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Pelvis AP", "modality": "CR", "body_part": "Pelvis", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Hip Joint AP & Lateral", "modality": "CR", "body_part": "Hip", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Shoulder AP & Lateral", "modality": "CR", "body_part": "Shoulder", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Elbow AP & Lateral", "modality": "CR", "body_part": "Elbow", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Wrist AP & Lateral", "modality": "CR", "body_part": "Wrist", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Hand AP & Oblique", "modality": "CR", "body_part": "Hand", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Knee AP & Lateral", "modality": "CR", "body_part": "Knee", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Ankle AP & Lateral", "modality": "CR", "body_part": "Ankle", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Foot AP, Lateral & Oblique", "modality": "CR", "body_part": "Foot", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Femur AP & Lateral", "modality": "CR", "body_part": "Femur", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Tibia-Fibula AP & Lateral", "modality": "CR", "body_part": "Tibia/Fibula", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Humerus AP & Lateral", "modality": "CR", "body_part": "Humerus", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Forearm AP & Lateral", "modality": "CR", "body_part": "Forearm", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Paranasal Sinuses (PNS) — Waters View", "modality": "CR", "body_part": "Sinuses", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Mastoid Bones — Schuller's View", "modality": "CR", "body_part": "Mastoid", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Mandible AP & Oblique", "modality": "CR", "body_part": "Mandible", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray OPG (Orthopantomogram)", "modality": "CR", "body_part": "Jaw", "category": "X-Ray Dental", "turnaround_hours": 1, "preparation": "Remove dentures/metal"},
    {"name": "X-Ray Scapula AP & Lateral", "modality": "CR", "body_part": "Scapula", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Clavicle AP", "modality": "CR", "body_part": "Clavicle", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Ribs — Oblique Views", "modality": "CR", "body_part": "Ribs", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Sternum Lateral", "modality": "CR", "body_part": "Sternum", "category": "X-Ray", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Both Hips Comparison (Developmental Dysplasia)", "modality": "CR", "body_part": "Hips", "category": "X-Ray Paediatric", "turnaround_hours": 2, "preparation": ""},
    {"name": "X-Ray Bone Age (Left Hand & Wrist)", "modality": "CR", "body_part": "Hand/Wrist", "category": "X-Ray Paediatric", "turnaround_hours": 4, "preparation": ""},
    {"name": "X-Ray Scoliosis — Full Spine (Long Film)", "modality": "CR", "body_part": "Full Spine", "category": "X-Ray", "turnaround_hours": 4, "preparation": "Standing erect"},

    # ═══════════════════════════════════════════════════════
    # ULTRASOUND (US)
    # ═══════════════════════════════════════════════════════
    {"name": "USG Abdomen — Upper", "modality": "US", "body_part": "Upper Abdomen", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Fasting 4–6 hours; full bladder"},
    {"name": "USG Abdomen — Whole", "modality": "US", "body_part": "Abdomen", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Fasting 4–6 hours; full bladder"},
    {"name": "USG Abdomen & Pelvis", "modality": "US", "body_part": "Abdomen & Pelvis", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Fasting 4–6 hours; full bladder"},
    {"name": "USG Pelvis (Transabdominal)", "modality": "US", "body_part": "Pelvis", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Full bladder"},
    {"name": "USG Pelvis (Transvaginal — TVS)", "modality": "US", "body_part": "Pelvis", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Bladder partially full"},
    {"name": "USG KUB (Kidneys-Ureters-Bladder)", "modality": "US", "body_part": "KUB", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Full bladder"},
    {"name": "USG Liver (Hepatic)", "modality": "US", "body_part": "Liver", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Fasting 4 hours"},
    {"name": "USG Gall Bladder (Cholelithiasis)", "modality": "US", "body_part": "Gall Bladder", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Fasting 6 hours"},
    {"name": "USG Thyroid & Neck", "modality": "US", "body_part": "Thyroid/Neck", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Breast — Bilateral", "modality": "US", "body_part": "Breast", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Breast — Right", "modality": "US", "body_part": "Right Breast", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Breast — Left", "modality": "US", "body_part": "Left Breast", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Scrotum & Testes", "modality": "US", "body_part": "Scrotum", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Prostate (Transabdominal)", "modality": "US", "body_part": "Prostate", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Full bladder"},
    {"name": "USG Prostate (TRUS — Transrectal)", "modality": "US", "body_part": "Prostate", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "Bowel preparation"},
    {"name": "USG Neonatal Head (Cranial)", "modality": "US", "body_part": "Neonatal Brain", "category": "Ultrasound Paediatric", "turnaround_hours": 4, "preparation": "None (fontanelle window)"},
    {"name": "USG Hips — Both (Developmental Dysplasia)", "modality": "US", "body_part": "Hips", "category": "Ultrasound Paediatric", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Abdomen Paediatric", "modality": "US", "body_part": "Paediatric Abdomen", "category": "Ultrasound Paediatric", "turnaround_hours": 4, "preparation": "Age-appropriate fasting"},
    {"name": "USG Soft Tissue (Localised)", "modality": "US", "body_part": "Soft Tissue", "category": "Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Obstetric — 1st Trimester (Dating Scan)", "modality": "US", "body_part": "Gravid Uterus", "category": "Obstetric Ultrasound", "turnaround_hours": 4, "preparation": "Full bladder"},
    {"name": "USG Obstetric — NT Scan (11–14 weeks)", "modality": "US", "body_part": "Gravid Uterus", "category": "Obstetric Ultrasound", "turnaround_hours": 4, "preparation": "Full bladder"},
    {"name": "USG Obstetric — Anomaly Scan (18–20 weeks)", "modality": "US", "body_part": "Gravid Uterus", "category": "Obstetric Ultrasound", "turnaround_hours": 4, "preparation": "Moderate bladder"},
    {"name": "USG Obstetric — 3rd Trimester Growth Scan", "modality": "US", "body_part": "Gravid Uterus", "category": "Obstetric Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "USG Obstetric — Cervical Length", "modality": "US", "body_part": "Cervix", "category": "Obstetric Ultrasound", "turnaround_hours": 4, "preparation": "Moderately full bladder"},
    {"name": "USG Doppler — Fetal Biophysical Profile (BPP)", "modality": "US", "body_part": "Fetus", "category": "Obstetric Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "Colour Doppler — Umbilical Artery", "modality": "US", "body_part": "Umbilical Cord", "category": "Doppler Ultrasound", "turnaround_hours": 4, "preparation": "None"},
    {"name": "Colour Doppler — Carotid & Vertebral Arteries", "modality": "US", "body_part": "Carotid Arteries", "category": "Doppler Ultrasound", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Colour Doppler — Portal Venous System", "modality": "US", "body_part": "Portal Vein", "category": "Doppler Ultrasound", "turnaround_hours": 6, "preparation": "Fasting"},
    {"name": "Colour Doppler — Renal Arteries", "modality": "US", "body_part": "Renal Arteries", "category": "Doppler Ultrasound", "turnaround_hours": 6, "preparation": "Fasting"},
    {"name": "Colour Doppler — Lower Limb Venous (DVT Screen)", "modality": "US", "body_part": "Lower Limb Veins", "category": "Doppler Ultrasound", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Colour Doppler — Lower Limb Arterial", "modality": "US", "body_part": "Lower Limb Arteries", "category": "Doppler Ultrasound", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Colour Doppler — Upper Limb Venous", "modality": "US", "body_part": "Upper Limb Veins", "category": "Doppler Ultrasound", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Colour Doppler — Testicular (Torsion Screen)", "modality": "US", "body_part": "Testes", "category": "Doppler Ultrasound", "turnaround_hours": 4, "preparation": "Emergency"},
    {"name": "Echocardiography (2D Echo)", "modality": "US", "body_part": "Heart", "category": "Cardiac Ultrasound", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Colour Doppler Echo (Including LVEF)", "modality": "US", "body_part": "Heart", "category": "Cardiac Ultrasound", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Transoesophageal Echo (TOE)", "modality": "US", "body_part": "Heart", "category": "Cardiac Ultrasound", "turnaround_hours": 6, "preparation": "Fasting 4 hours; sedation"},
    {"name": "USG-Guided FNAC / Biopsy", "modality": "US", "body_part": "Variable", "category": "Interventional Ultrasound", "turnaround_hours": 48, "preparation": "Coagulation profile; informed consent"},
    {"name": "USG-Guided Aspiration / Drainage", "modality": "US", "body_part": "Variable", "category": "Interventional Ultrasound", "turnaround_hours": 4, "preparation": "Informed consent"},
    {"name": "USG-Guided Pleural Aspiration", "modality": "US", "body_part": "Pleural Space", "category": "Interventional Ultrasound", "turnaround_hours": 4, "preparation": "Coagulation profile"},
    {"name": "USG-Guided Ascitic Tap (Paracentesis)", "modality": "US", "body_part": "Abdomen", "category": "Interventional Ultrasound", "turnaround_hours": 4, "preparation": "Coagulation profile"},

    # ═══════════════════════════════════════════════════════
    # CT SCAN
    # ═══════════════════════════════════════════════════════
    {"name": "CT Brain (NCCT Head)", "modality": "CT", "body_part": "Brain", "category": "CT Scan", "turnaround_hours": 4, "preparation": "None (emergency: immediate)"},
    {"name": "CT Brain with Contrast", "modality": "CT", "body_part": "Brain", "category": "CT Scan", "turnaround_hours": 4, "preparation": "Serum creatinine; no food 2–4h"},
    {"name": "CT Brain Perfusion", "modality": "CT", "body_part": "Brain", "category": "CT Scan", "turnaround_hours": 4, "preparation": "Emergency — acute stroke protocol"},
    {"name": "CT Angiography — Cerebral (CTA Brain)", "modality": "CT", "body_part": "Cerebral Arteries", "category": "CT Angiography", "turnaround_hours": 6, "preparation": "IV access; serum creatinine"},
    {"name": "CT Angiography — Carotid & Neck", "modality": "CT", "body_part": "Carotid/Neck", "category": "CT Angiography", "turnaround_hours": 6, "preparation": "IV access; serum creatinine"},
    {"name": "CT Chest (NCCT)", "modality": "CT", "body_part": "Chest", "category": "CT Scan", "turnaround_hours": 4, "preparation": "Breath hold instructions"},
    {"name": "CT Chest with Contrast", "modality": "CT", "body_part": "Chest", "category": "CT Scan", "turnaround_hours": 6, "preparation": "Serum creatinine; fasting 4h"},
    {"name": "CT Pulmonary Angiography (CTPA)", "modality": "CT", "body_part": "Pulmonary Arteries", "category": "CT Angiography", "turnaround_hours": 4, "preparation": "Emergency / urgent; IV access; creatinine"},
    {"name": "HRCT Chest (High-Resolution)", "modality": "CT", "body_part": "Chest", "category": "CT Scan", "turnaround_hours": 6, "preparation": "Breath hold instructions"},
    {"name": "CT Abdomen NCCT", "modality": "CT", "body_part": "Abdomen", "category": "CT Scan", "turnaround_hours": 6, "preparation": "Fasting 4 hours"},
    {"name": "CT Abdomen with Contrast (Triple Phase)", "modality": "CT", "body_part": "Abdomen", "category": "CT Scan", "turnaround_hours": 6, "preparation": "Fasting 4h; IV access; serum creatinine"},
    {"name": "CT Abdomen & Pelvis with Contrast", "modality": "CT", "body_part": "Abdomen & Pelvis", "category": "CT Scan", "turnaround_hours": 6, "preparation": "Fasting 4h; oral contrast; serum creatinine"},
    {"name": "CT Liver (Hepatic Protocol — 3 Phase)", "modality": "CT", "body_part": "Liver", "category": "CT Scan", "turnaround_hours": 6, "preparation": "Fasting 4h; serum creatinine"},
    {"name": "CT KUB (Kidney-Ureter-Bladder — Urolithiasis)", "modality": "CT", "body_part": "KUB", "category": "CT Scan", "turnaround_hours": 4, "preparation": "Full bladder preferred; no contrast needed"},
    {"name": "CT Urography (CTU)", "modality": "CT", "body_part": "KUB", "category": "CT Scan", "turnaround_hours": 6, "preparation": "IV contrast; serum creatinine"},
    {"name": "CT Angiography — Aorta (Whole Aorta)", "modality": "CT", "body_part": "Aorta", "category": "CT Angiography", "turnaround_hours": 6, "preparation": "IV access; serum creatinine"},
    {"name": "CT Angiography — Coronary (CTCA)", "modality": "CT", "body_part": "Coronary Arteries", "category": "CT Angiography", "turnaround_hours": 6, "preparation": "HR <60 bpm (beta-blocker); fasting; creatinine"},
    {"name": "CT Spine — Cervical", "modality": "CT", "body_part": "Cervical Spine", "category": "CT Scan", "turnaround_hours": 6, "preparation": "None"},
    {"name": "CT Spine — Lumbar", "modality": "CT", "body_part": "Lumbar Spine", "category": "CT Scan", "turnaround_hours": 6, "preparation": "None"},
    {"name": "CT Paranasal Sinuses (CT PNS)", "modality": "CT", "body_part": "Sinuses", "category": "CT Scan", "turnaround_hours": 6, "preparation": "None"},
    {"name": "CT Temporal Bones (Cochlear / Mastoid)", "modality": "CT", "body_part": "Temporal Bone", "category": "CT Scan", "turnaround_hours": 6, "preparation": "None"},
    {"name": "CT Orbit & Facial Bones", "modality": "CT", "body_part": "Orbits/Face", "category": "CT Scan", "turnaround_hours": 6, "preparation": "None"},
    {"name": "CT Neck with Contrast", "modality": "CT", "body_part": "Neck", "category": "CT Scan", "turnaround_hours": 6, "preparation": "IV access; serum creatinine"},
    {"name": "CT Pelvis", "modality": "CT", "body_part": "Pelvis", "category": "CT Scan", "turnaround_hours": 6, "preparation": "Full bladder; oral contrast"},
    {"name": "CT Colonoscopy (Virtual Colonoscopy)", "modality": "CT", "body_part": "Colon", "category": "CT Scan", "turnaround_hours": 8, "preparation": "Full bowel prep; low-residue diet"},
    {"name": "CT Guided Biopsy", "modality": "CT", "body_part": "Variable", "category": "CT Interventional", "turnaround_hours": 24, "preparation": "Coagulation profile; informed consent; NPO"},
    {"name": "CT Guided Drainage", "modality": "CT", "body_part": "Variable", "category": "CT Interventional", "turnaround_hours": 6, "preparation": "Coagulation profile; informed consent"},
    {"name": "CT Trauma Protocol (Head-Neck-Thorax-Abdomen-Pelvis)", "modality": "CT", "body_part": "Whole Body", "category": "CT Scan", "turnaround_hours": 2, "preparation": "Emergency protocol"},
    {"name": "CT Enterography (Small Bowel)", "modality": "CT", "body_part": "Small Bowel", "category": "CT Scan", "turnaround_hours": 8, "preparation": "Oral contrast (neutral); fasting"},
    {"name": "CT 3D Reconstruction — Musculoskeletal", "modality": "CT", "body_part": "Bone/Joint", "category": "CT Scan", "turnaround_hours": 8, "preparation": "Plain CT first"},

    # ═══════════════════════════════════════════════════════
    # MRI
    # ═══════════════════════════════════════════════════════
    {"name": "MRI Brain (Plain)", "modality": "MR", "body_part": "Brain", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening; remove metal"},
    {"name": "MRI Brain with Contrast", "modality": "MR", "body_part": "Brain", "category": "MRI", "turnaround_hours": 8, "preparation": "eGFR check; IV access"},
    {"name": "MRI Brain — DWI (Stroke Protocol)", "modality": "MR", "body_part": "Brain", "category": "MRI", "turnaround_hours": 4, "preparation": "Urgent protocol"},
    {"name": "MRI Brain — Epilepsy Protocol", "modality": "MR", "body_part": "Brain", "category": "MRI", "turnaround_hours": 8, "preparation": "None; sedation if needed"},
    {"name": "MRI Brain — Spectroscopy (MRS)", "modality": "MR", "body_part": "Brain", "category": "MRI", "turnaround_hours": 8, "preparation": "None"},
    {"name": "MRA — Brain (Magnetic Resonance Angiography)", "modality": "MR", "body_part": "Cerebral Arteries", "category": "MRI Angiography", "turnaround_hours": 8, "preparation": "None (TOF technique) or eGFR"},
    {"name": "MRV — Brain (Cerebral Venography)", "modality": "MR", "body_part": "Cerebral Veins", "category": "MRI Angiography", "turnaround_hours": 8, "preparation": "None"},
    {"name": "MRI Spine — Cervical (Plain & Contrast)", "modality": "MR", "body_part": "Cervical Spine", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening"},
    {"name": "MRI Spine — Dorsal (Thoracic)", "modality": "MR", "body_part": "Thoracic Spine", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening"},
    {"name": "MRI Spine — Lumbar (Plain)", "modality": "MR", "body_part": "Lumbar Spine", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening"},
    {"name": "MRI Spine — Whole Spine Screening", "modality": "MR", "body_part": "Full Spine", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening"},
    {"name": "MRI Knee — Plain", "modality": "MR", "body_part": "Knee", "category": "MRI Musculoskeletal", "turnaround_hours": 8, "preparation": "None"},
    {"name": "MRI Shoulder — Plain", "modality": "MR", "body_part": "Shoulder", "category": "MRI Musculoskeletal", "turnaround_hours": 8, "preparation": "None"},
    {"name": "MRI Hip Joint — Bilateral", "modality": "MR", "body_part": "Hip", "category": "MRI Musculoskeletal", "turnaround_hours": 8, "preparation": "None"},
    {"name": "MRI Ankle & Foot", "modality": "MR", "body_part": "Ankle/Foot", "category": "MRI Musculoskeletal", "turnaround_hours": 8, "preparation": "None"},
    {"name": "MRI Wrist — Plain", "modality": "MR", "body_part": "Wrist", "category": "MRI Musculoskeletal", "turnaround_hours": 8, "preparation": "None"},
    {"name": "MRI Abdomen with MRCP", "modality": "MR", "body_part": "Abdomen/Biliary", "category": "MRI", "turnaround_hours": 8, "preparation": "Fasting 6 hours"},
    {"name": "MRCP (Magnetic Resonance Cholangiopancreatography)", "modality": "MR", "body_part": "Biliary Tree", "category": "MRI", "turnaround_hours": 8, "preparation": "Fasting 6 hours"},
    {"name": "MRI Abdomen — Liver Protocol (with Contrast)", "modality": "MR", "body_part": "Liver", "category": "MRI", "turnaround_hours": 8, "preparation": "Fasting 4h; eGFR"},
    {"name": "MRI Pelvis — Female (Uterus/Ovaries)", "modality": "MR", "body_part": "Female Pelvis", "category": "MRI", "turnaround_hours": 8, "preparation": "Bladder full; tampon if needed"},
    {"name": "MRI Pelvis — Male (Prostate — mpMRI)", "modality": "MR", "body_part": "Prostate", "category": "MRI", "turnaround_hours": 8, "preparation": "Endorectal coil or surface coil; bowel prep"},
    {"name": "MRI Neck — Soft Tissue", "modality": "MR", "body_part": "Neck", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening"},
    {"name": "MRI Temporal Bones (IAM)", "modality": "MR", "body_part": "Temporal Bone/IAM", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening; hearing aids out"},
    {"name": "MRI Orbit — Both", "modality": "MR", "body_part": "Orbits", "category": "MRI", "turnaround_hours": 8, "preparation": "No metallic intraocular foreign body"},
    {"name": "MRI Whole Body (Cancer Staging)", "modality": "MR", "body_part": "Whole Body", "category": "MRI", "turnaround_hours": 12, "preparation": "Fasting; implant screening"},
    {"name": "Cardiac MRI (Cine + LGE)", "modality": "MR", "body_part": "Heart", "category": "Cardiac MRI", "turnaround_hours": 8, "preparation": "HR control; ECG gating; eGFR"},
    {"name": "MRI Fetal (Fetal MRI)", "modality": "MR", "body_part": "Fetus", "category": "MRI", "turnaround_hours": 8, "preparation": "After 18 weeks; no contrast"},
    {"name": "MRI Breast — Bilateral (with Contrast)", "modality": "MR", "body_part": "Breast", "category": "MRI", "turnaround_hours": 8, "preparation": "Day 7–14 of cycle; eGFR; prone position"},
    {"name": "MR Urography (MRU)", "modality": "MR", "body_part": "Urinary Tract", "category": "MRI", "turnaround_hours": 8, "preparation": "Fasting; IV contrast; diuretic"},
    {"name": "MRI Small Bowel (MR Enterography)", "modality": "MR", "body_part": "Small Bowel", "category": "MRI", "turnaround_hours": 8, "preparation": "Oral contrast; fasting 4h; IV Buscopan"},
    {"name": "MRI Brachial Plexus", "modality": "MR", "body_part": "Brachial Plexus", "category": "MRI", "turnaround_hours": 8, "preparation": "Implant screening"},
    {"name": "DATSCAN / Dopamine Transporter MRI", "modality": "MR", "body_part": "Brain (Basal Ganglia)", "category": "MRI", "turnaround_hours": 8, "preparation": "Stop certain medications"},

    # ═══════════════════════════════════════════════════════
    # NUCLEAR MEDICINE / PET-CT
    # ═══════════════════════════════════════════════════════
    {"name": "Bone Scan (Tc-99m MDP)", "modality": "NM", "body_part": "Whole Body Skeleton", "category": "Nuclear Medicine", "turnaround_hours": 24, "preparation": "Hydration; 3h delay after injection"},
    {"name": "Thyroid Scan & Uptake (Tc-99m)", "modality": "NM", "body_part": "Thyroid", "category": "Nuclear Medicine", "turnaround_hours": 6, "preparation": "Stop antithyroid drugs; no iodine contrast"},
    {"name": "Thyroid I-131 Therapy (Ablation)", "modality": "NM", "body_part": "Thyroid", "category": "Nuclear Medicine", "turnaround_hours": 24, "preparation": "Low-iodine diet; stop levothyroxine 4 weeks"},
    {"name": "Parathyroid Sestamibi Scan (MIBI)", "modality": "NM", "body_part": "Parathyroid", "category": "Nuclear Medicine", "turnaround_hours": 8, "preparation": "None"},
    {"name": "Renal DTPA Scan (Split Function)", "modality": "NM", "body_part": "Kidneys", "category": "Nuclear Medicine", "turnaround_hours": 6, "preparation": "Hydration; Captopril if renovascular"},
    {"name": "Renal DMSA Scan (Cortical Scintigraphy)", "modality": "NM", "body_part": "Kidneys", "category": "Nuclear Medicine", "turnaround_hours": 8, "preparation": "Hydration"},
    {"name": "Ventilation-Perfusion (V/Q) Scan", "modality": "NM", "body_part": "Lungs", "category": "Nuclear Medicine", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Myocardial Perfusion Imaging — Stress & Rest (MPI)", "modality": "NM", "body_part": "Heart", "category": "Nuclear Medicine", "turnaround_hours": 8, "preparation": "Fasting 4h; stop caffeine 24h; stress protocol"},
    {"name": "Hepatobiliary Scan (HIDA Scan)", "modality": "NM", "body_part": "Liver/Biliary", "category": "Nuclear Medicine", "turnaround_hours": 6, "preparation": "Fasting 4 hours"},
    {"name": "GI Bleed Scan (RBC Labelling)", "modality": "NM", "body_part": "GI Tract", "category": "Nuclear Medicine", "turnaround_hours": 6, "preparation": "Active bleeding suspected"},
    {"name": "Meckel Scan (Tc-99m Pertechnetate)", "modality": "NM", "body_part": "Abdomen", "category": "Nuclear Medicine", "turnaround_hours": 6, "preparation": "None"},
    {"name": "Sentinel Lymph Node Biopsy (SLNB)", "modality": "NM", "body_part": "Lymph Nodes", "category": "Nuclear Medicine", "turnaround_hours": 6, "preparation": "Coordination with surgery"},
    {"name": "PET-CT — F18-FDG (Whole Body Oncology)", "modality": "PT", "body_part": "Whole Body", "category": "PET-CT", "turnaround_hours": 8, "preparation": "Fasting 6h; blood glucose <150 mg/dL; no strenuous exercise"},
    {"name": "PET-CT — F18-FDG (Lymphoma Staging)", "modality": "PT", "body_part": "Whole Body", "category": "PET-CT", "turnaround_hours": 8, "preparation": "Fasting 6h; glucose check"},
    {"name": "PET-CT — F18-FDG (Post-Treatment Response)", "modality": "PT", "body_part": "Whole Body", "category": "PET-CT", "turnaround_hours": 8, "preparation": "Fasting 6h; glucose check"},
    {"name": "PET-CT — F18 PSMA (Prostate Cancer)", "modality": "PT", "body_part": "Prostate/Whole Body", "category": "PET-CT", "turnaround_hours": 8, "preparation": "Fasting 4h; hydration"},
    {"name": "PET-CT — Ga-68 DOTATATE (Neuroendocrine Tumours)", "modality": "PT", "body_part": "Whole Body", "category": "PET-CT", "turnaround_hours": 8, "preparation": "Stop somatostatin analogs 4 weeks prior"},
    {"name": "PET Brain — F18 FDG (Dementia/Epilepsy)", "modality": "PT", "body_part": "Brain", "category": "PET-CT", "turnaround_hours": 8, "preparation": "Fasting 6h; dark/quiet room 30 min before"},

    # ═══════════════════════════════════════════════════════
    # FLUOROSCOPY / SPECIAL PROCEDURES
    # ═══════════════════════════════════════════════════════
    {"name": "Barium Swallow (Oesophagography)", "modality": "RF", "body_part": "Oesophagus", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "Fasting 6 hours"},
    {"name": "Barium Meal (Upper GI Series)", "modality": "RF", "body_part": "Stomach/Duodenum", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "Fasting 6 hours"},
    {"name": "Barium Follow-Through (Small Bowel)", "modality": "RF", "body_part": "Small Bowel", "category": "Fluoroscopy", "turnaround_hours": 6, "preparation": "Fasting 6 hours; low-residue diet"},
    {"name": "Barium Enema (Double Contrast)", "modality": "RF", "body_part": "Large Bowel", "category": "Fluoroscopy", "turnaround_hours": 6, "preparation": "Full bowel prep"},
    {"name": "IVU (Intravenous Urography)", "modality": "RF", "body_part": "KUB", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "Creatinine check; fasting; laxative"},
    {"name": "MCU / VCUG (Micturating Cystourethrogram)", "modality": "RF", "body_part": "Bladder/Urethra", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "Urine culture clear; catheter placement"},
    {"name": "HSG (Hysterosalpingography)", "modality": "RF", "body_part": "Uterus/Fallopian Tubes", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "Day 7–10 of cycle; exclude pregnancy"},
    {"name": "Myelogram (Lumbar / Cervical)", "modality": "RF", "body_part": "Spinal Canal", "category": "Fluoroscopy", "turnaround_hours": 6, "preparation": "Stop anticoagulants; informed consent"},
    {"name": "ERCP (Endoscopic Retrograde Cholangiopancreatography)", "modality": "RF", "body_part": "Biliary/Pancreatic Duct", "category": "Fluoroscopy", "turnaround_hours": 6, "preparation": "Fasting 8h; anaesthesia consent"},
    {"name": "Sialogram (Parotid / Submandibular)", "modality": "RF", "body_part": "Salivary Glands", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "Lemon stimulation before"},
    {"name": "Fistulogram / Sinogram", "modality": "RF", "body_part": "Fistula/Sinus", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "No preparation"},
    {"name": "Cholangiography (Percutaneous — PTC)", "modality": "RF", "body_part": "Biliary Tree", "category": "Fluoroscopy", "turnaround_hours": 6, "preparation": "Coagulation profile; antibiotics"},
    {"name": "Arthroscopy / Arthrogram (Fluoroscopic)", "modality": "RF", "body_part": "Joint", "category": "Fluoroscopy", "turnaround_hours": 4, "preparation": "Informed consent"},

    # ═══════════════════════════════════════════════════════
    # MAMMOGRAPHY
    # ═══════════════════════════════════════════════════════
    {"name": "Mammography — Bilateral Screening", "modality": "MG", "body_part": "Breast", "category": "Mammography", "turnaround_hours": 24, "preparation": "Avoid deodorant/talc; mid-cycle timing"},
    {"name": "Mammography — Diagnostic (Unilateral)", "modality": "MG", "body_part": "Breast", "category": "Mammography", "turnaround_hours": 24, "preparation": "Symptomatic side; clinical correlation"},
    {"name": "Tomosynthesis (3D Mammography)", "modality": "MG", "body_part": "Breast", "category": "Mammography", "turnaround_hours": 24, "preparation": "Same as standard mammography"},

    # ═══════════════════════════════════════════════════════
    # INTERVENTIONAL RADIOLOGY
    # ═══════════════════════════════════════════════════════
    {"name": "Coronary Angiography (DSA)", "modality": "XA", "body_part": "Coronary Arteries", "category": "Interventional Radiology", "turnaround_hours": 4, "preparation": "Fasting 6h; creatinine; consent; cath lab"},
    {"name": "Percutaneous Coronary Intervention (PCI/Angioplasty)", "modality": "XA", "body_part": "Coronary Arteries", "category": "Interventional Radiology", "turnaround_hours": 4, "preparation": "Pre-loaded antiplatelet; fasting; consent"},
    {"name": "Peripheral Angiography (Lower Limb)", "modality": "XA", "body_part": "Lower Limb Arteries", "category": "Interventional Radiology", "turnaround_hours": 6, "preparation": "Creatinine; consent; access site prep"},
    {"name": "Aortic Stent Graft (EVAR / TEVAR)", "modality": "XA", "body_part": "Aorta", "category": "Interventional Radiology", "turnaround_hours": 8, "preparation": "Complex planning; general anaesthesia"},
    {"name": "Carotid Stenting (CAS)", "modality": "XA", "body_part": "Carotid Artery", "category": "Interventional Radiology", "turnaround_hours": 8, "preparation": "Antiplatelet preloading; neuromonitoring"},
    {"name": "TACE (Transarterial Chemoembolisation — HCC)", "modality": "XA", "body_part": "Hepatic Arteries", "category": "Interventional Radiology", "turnaround_hours": 8, "preparation": "LFT; AFP; cross-sectional imaging; consent"},
    {"name": "UFE (Uterine Fibroid Embolisation)", "modality": "XA", "body_part": "Uterine Arteries", "category": "Interventional Radiology", "turnaround_hours": 8, "preparation": "MRI fibroid mapping; consent; admission"},
    {"name": "IVC Filter Placement", "modality": "XA", "body_part": "Inferior Vena Cava", "category": "Interventional Radiology", "turnaround_hours": 4, "preparation": "Coagulation; DVT imaging"},
    {"name": "Central Venous Port (Port-a-Cath) Insertion", "modality": "XA", "body_part": "Central Vein", "category": "Interventional Radiology", "turnaround_hours": 4, "preparation": "Coagulation; consent; site selection"},
    {"name": "Nephrostomy (PCN) Insertion", "modality": "XA", "body_part": "Kidney", "category": "Interventional Radiology", "turnaround_hours": 4, "preparation": "Urine culture; coagulation; antibiotics"},
    {"name": "Biliary Drainage (PTBD)", "modality": "XA", "body_part": "Biliary Tree", "category": "Interventional Radiology", "turnaround_hours": 6, "preparation": "LFT; coagulation; antibiotics; consent"},
    {"name": "Vertebroplasty / Kyphoplasty", "modality": "XA", "body_part": "Vertebral Body", "category": "Interventional Radiology", "turnaround_hours": 6, "preparation": "MRI bone oedema confirmation; consent"},
    {"name": "Radiofrequency Ablation (RFA) — Liver Tumour", "modality": "XA", "body_part": "Liver", "category": "Interventional Radiology", "turnaround_hours": 8, "preparation": "CT/MRI localisation; coagulation; consent"},
    {"name": "Microwave Ablation (MWA) — Lung/Liver", "modality": "XA", "body_part": "Lung/Liver", "category": "Interventional Radiology", "turnaround_hours": 8, "preparation": "CT guidance; coagulation; consent; anaesthesia"},
    {"name": "TIPS (Transjugular Intrahepatic Portosystemic Shunt)", "modality": "XA", "body_part": "Portal-Hepatic Veins", "category": "Interventional Radiology", "turnaround_hours": 8, "preparation": "LFT; EEG/ammonia; Echo; consent"},
]
