"""
Key drug-drug interactions relevant to Indian clinical practice.
Each entry: {drug_a, drug_b, severity, effect, management}
severity: contraindicated | serious | moderate | minor
"""

INTERACTIONS = [
    # ── Contraindicated Combinations ──────────────────────────────────────────
    {"drug_a": "Warfarin", "drug_b": "Aspirin", "severity": "contraindicated",
     "effect": "Greatly increased bleeding risk; dual anticoagulant + antiplatelet effect",
     "management": "Avoid combination; if needed under specialist care, monitor INR closely and watch for bleeding"},
    {"drug_a": "MAO Inhibitors", "drug_b": "Tramadol", "severity": "contraindicated",
     "effect": "Risk of serotonin syndrome — hyperthermia, rigidity, seizures",
     "management": "Do not use together; allow 14-day washout after MAOI"},
    {"drug_a": "MAO Inhibitors", "drug_b": "Fluoxetine", "severity": "contraindicated",
     "effect": "Serotonin syndrome; potentially fatal",
     "management": "Allow 14-day washout from MAOI; 5 weeks washout after fluoxetine"},
    {"drug_a": "MAO Inhibitors", "drug_b": "Sertraline", "severity": "contraindicated",
     "effect": "Serotonin syndrome",
     "management": "14-day washout required between MAOI and sertraline"},
    {"drug_a": "Sildenafil", "drug_b": "Isosorbide Mononitrate", "severity": "contraindicated",
     "effect": "Severe hypotension — nitrates + PDE-5 inhibitor cause profound BP drop",
     "management": "Absolutely contraindicated; do not co-prescribe"},
    {"drug_a": "Sildenafil", "drug_b": "Nitroglycerin (GTN)", "severity": "contraindicated",
     "effect": "Severe, potentially fatal hypotension",
     "management": "Absolutely contraindicated"},
    {"drug_a": "Methotrexate", "drug_b": "Aspirin", "severity": "contraindicated",
     "effect": "NSAIDs reduce methotrexate renal clearance → severe toxicity (bone marrow suppression, mucositis)",
     "management": "Avoid NSAIDs with weekly methotrexate; if unavoidable, use paracetamol, reduce methotrexate dose, monitor FBC"},
    {"drug_a": "Methotrexate", "drug_b": "Cotrimoxazole (Trimethoprim-Sulfamethoxazole)", "severity": "contraindicated",
     "effect": "Both are folate antagonists; profound myelosuppression",
     "management": "Contraindicated together; use alternative antibiotic"},
    {"drug_a": "Warfarin", "drug_b": "Rifampicin", "severity": "contraindicated",
     "effect": "Rifampicin is a potent CYP450 inducer; warfarin levels drop dramatically → loss of anticoagulation",
     "management": "Avoid; if TB treatment needed, switch to heparin or DOAC with specialist review"},

    # ── Serious Interactions ──────────────────────────────────────────────────
    {"drug_a": "Amiodarone", "drug_b": "Warfarin", "severity": "serious",
     "effect": "Amiodarone inhibits CYP2C9; warfarin levels rise → bleeding risk",
     "management": "Reduce warfarin dose by 30-50% when starting amiodarone; monitor INR frequently"},
    {"drug_a": "Amiodarone", "drug_b": "Digoxin", "severity": "serious",
     "effect": "Amiodarone increases digoxin levels by ~70%; risk of digoxin toxicity",
     "management": "Reduce digoxin dose by 50% when adding amiodarone; monitor digoxin levels"},
    {"drug_a": "Amiodarone", "drug_b": "Atorvastatin", "severity": "serious",
     "effect": "Amiodarone inhibits CYP3A4; statin levels rise → myopathy/rhabdomyolysis risk",
     "management": "Limit atorvastatin to 40mg/day when used with amiodarone; monitor CK"},
    {"drug_a": "Clopidogrel", "drug_b": "Omeprazole", "severity": "serious",
     "effect": "Omeprazole inhibits CYP2C19 reducing clopidogrel activation; reduced antiplatelet effect",
     "management": "Prefer pantoprazole or rabeprazole as PPI with clopidogrel"},
    {"drug_a": "Warfarin", "drug_b": "Metronidazole", "severity": "serious",
     "effect": "Metronidazole inhibits warfarin metabolism; INR rises → bleeding",
     "management": "Reduce warfarin dose by ~30%; monitor INR every 2-3 days during course"},
    {"drug_a": "Digoxin", "drug_b": "Furosemide", "severity": "serious",
     "effect": "Furosemide causes hypokalaemia → increased digoxin toxicity at normal digoxin levels",
     "management": "Monitor electrolytes; supplement potassium; monitor digoxin levels"},
    {"drug_a": "Metformin", "drug_b": "Furosemide", "severity": "serious",
     "effect": "Furosemide can impair renal function → metformin accumulation → lactic acidosis",
     "management": "Monitor renal function; hold metformin if eGFR falls below 30"},
    {"drug_a": "Lithium Carbonate", "drug_b": "Ibuprofen", "severity": "serious",
     "effect": "NSAIDs reduce renal lithium excretion → lithium toxicity (tremors, confusion, cardiac)",
     "management": "Avoid NSAIDs with lithium; use paracetamol; monitor lithium levels"},
    {"drug_a": "Lithium Carbonate", "drug_b": "Enalapril", "severity": "serious",
     "effect": "ACE inhibitors reduce lithium renal clearance → lithium toxicity",
     "management": "Monitor lithium levels closely when adding/stopping ACE inhibitor; consider dose reduction"},
    {"drug_a": "Ciprofloxacin", "drug_b": "Theophylline", "severity": "serious",
     "effect": "Ciprofloxacin inhibits CYP1A2; theophylline levels rise → theophylline toxicity",
     "management": "Reduce theophylline dose by ~50%; monitor theophylline levels"},
    {"drug_a": "Ciprofloxacin", "drug_b": "Warfarin", "severity": "serious",
     "effect": "Quinolones can enhance warfarin effect; INR may rise",
     "management": "Monitor INR closely during and after ciprofloxacin course"},
    {"drug_a": "Carbamazepine", "drug_b": "Valproate (Sodium Valproate)", "severity": "serious",
     "effect": "Pharmacokinetic interaction; carbamazepine reduces valproate levels; valproate inhibits carbamazepine metabolism",
     "management": "Monitor drug levels; adjust doses accordingly; watch for toxicity"},
    {"drug_a": "Phenytoin", "drug_b": "Valproate (Sodium Valproate)", "severity": "serious",
     "effect": "Valproate inhibits phenytoin metabolism; phenytoin may displace valproate from protein binding",
     "management": "Monitor phenytoin and valproate levels; complex interaction requiring specialist management"},
    {"drug_a": "Methotrexate", "drug_b": "Ibuprofen", "severity": "serious",
     "effect": "NSAIDs reduce methotrexate clearance → toxicity risk",
     "management": "Avoid NSAIDs with methotrexate; use paracetamol; monitor FBC and LFTs"},
    {"drug_a": "Atorvastatin", "drug_b": "Itraconazole", "severity": "serious",
     "effect": "Itraconazole inhibits CYP3A4; atorvastatin levels increase dramatically → myopathy/rhabdomyolysis",
     "management": "Avoid combination or suspend statin during antifungal course"},
    {"drug_a": "Simvastatin", "drug_b": "Itraconazole", "severity": "serious",
     "effect": "Itraconazole markedly increases simvastatin levels → severe myopathy risk",
     "management": "Contraindicated; switch to pravastatin or rosuvastatin (less CYP3A4 dependent)"},
    {"drug_a": "Tacrolimus", "drug_b": "Itraconazole", "severity": "serious",
     "effect": "CYP3A4 inhibition; tacrolimus levels rise several-fold → nephrotoxicity",
     "management": "Monitor tacrolimus levels closely; significant dose reduction usually needed"},
    {"drug_a": "Cyclosporine", "drug_b": "Itraconazole", "severity": "serious",
     "effect": "Itraconazole inhibits CYP3A4; cyclosporine levels rise → nephrotoxicity",
     "management": "Reduce cyclosporine dose; frequent level monitoring"},
    {"drug_a": "Enalapril", "drug_b": "Spironolactone", "severity": "serious",
     "effect": "Both raise potassium; hyperkalaemia risk especially in renal impairment",
     "management": "Monitor electrolytes frequently; avoid in severe renal impairment"},
    {"drug_a": "Ramipril", "drug_b": "Spironolactone", "severity": "serious",
     "effect": "Hyperkalaemia risk",
     "management": "Monitor K+ and renal function closely"},
    {"drug_a": "Amoxicillin-Clavulanate", "drug_b": "Warfarin", "severity": "serious",
     "effect": "Gut flora disruption reduces Vitamin K production → raised INR",
     "management": "Monitor INR during and 1 week after antibiotics"},
    {"drug_a": "Rifampicin", "drug_b": "Oral Contraceptives", "severity": "serious",
     "effect": "Rifampicin markedly induces CYP enzymes → OCP failure → unintended pregnancy",
     "management": "Use barrier contraception or injectable/IUD; continue for 1 month after rifampicin stops"},
    {"drug_a": "Carbamazepine", "drug_b": "Oral Contraceptives", "severity": "serious",
     "effect": "CYP3A4 induction reduces OCP efficacy",
     "management": "Use barrier contraception; consider progesterone-only injectable"},
    {"drug_a": "Dexamethasone", "drug_b": "Ibuprofen", "severity": "serious",
     "effect": "Additive GI ulceration and bleeding risk",
     "management": "Co-prescribe PPI; avoid combination if possible"},
    {"drug_a": "Prednisolone", "drug_b": "Ibuprofen", "severity": "serious",
     "effect": "Increased risk of GI haemorrhage",
     "management": "Add PPI gastroprotection; prefer paracetamol for analgesia"},

    # ── Moderate Interactions ─────────────────────────────────────────────────
    {"drug_a": "Amlodipine", "drug_b": "Atorvastatin", "severity": "moderate",
     "effect": "Amlodipine mildly inhibits CYP3A4; small increase in atorvastatin levels",
     "management": "Generally safe; max atorvastatin 40mg when combined; monitor for myalgia"},
    {"drug_a": "Ciprofloxacin", "drug_b": "Antacids", "severity": "moderate",
     "effect": "Antacids (Mg/Al/Ca) chelate ciprofloxacin; reduced absorption by up to 90%",
     "management": "Take ciprofloxacin 2 hours before or 6 hours after antacids"},
    {"drug_a": "Levothyroxine", "drug_b": "Ferrous Sulphate", "severity": "moderate",
     "effect": "Iron forms insoluble complex with levothyroxine → reduced thyroid hormone absorption",
     "management": "Separate doses by at least 4 hours"},
    {"drug_a": "Levothyroxine", "drug_b": "Calcium Carbonate + Vitamin D3", "severity": "moderate",
     "effect": "Calcium impairs levothyroxine absorption",
     "management": "Take levothyroxine 4 hours before calcium supplement"},
    {"drug_a": "Metformin", "drug_b": "Hydrochlorothiazide", "severity": "moderate",
     "effect": "Thiazides can worsen glycaemic control and cause hyponatraemia",
     "management": "Monitor glucose and electrolytes; adjust metformin dose as needed"},
    {"drug_a": "Allopurinol", "drug_b": "Azathioprine", "severity": "moderate",
     "effect": "Allopurinol inhibits xanthine oxidase; azathioprine metabolites accumulate → severe myelosuppression",
     "management": "Reduce azathioprine to 25-33% of dose; monitor FBC closely"},
    {"drug_a": "Allopurinol", "drug_b": "Cotrimoxazole (Trimethoprim-Sulfamethoxazole)", "severity": "moderate",
     "effect": "Additive risk of skin reactions and haematological toxicity",
     "management": "Use with caution; watch for rash, FBC monitoring"},
    {"drug_a": "Doxycycline", "drug_b": "Ferrous Sulphate", "severity": "moderate",
     "effect": "Iron chelates doxycycline; reduced antibiotic absorption",
     "management": "Separate doses by at least 3 hours"},
    {"drug_a": "Ciprofloxacin", "drug_b": "Metronidazole", "severity": "moderate",
     "effect": "QTc prolongation risk (additive); possible cardiac arrhythmia",
     "management": "Monitor ECG if both needed; avoid in patients with cardiac risk factors"},
    {"drug_a": "Ondansetron", "drug_b": "Metronidazole", "severity": "moderate",
     "effect": "Both prolong QTc interval; risk of Torsades de Pointes",
     "management": "Avoid combination or limit duration; ECG monitoring"},
    {"drug_a": "Sertraline", "drug_b": "Tramadol", "severity": "moderate",
     "effect": "Serotonin syndrome risk (SSRIs + tramadol) and lowered seizure threshold",
     "management": "Use alternative analgesic; if unavoidable, use lowest tramadol dose and monitor"},
    {"drug_a": "Fluoxetine", "drug_b": "Tramadol", "severity": "moderate",
     "effect": "Fluoxetine inhibits CYP2D6 reducing tramadol activation; also serotonin syndrome risk",
     "management": "Avoid; use alternative analgesic"},
    {"drug_a": "Valproate (Sodium Valproate)", "drug_b": "Lamotrigine", "severity": "moderate",
     "effect": "Valproate significantly increases lamotrigine levels → toxicity",
     "management": "Halve lamotrigine starting dose and titration when adding valproate"},
    {"drug_a": "Colchicine", "drug_b": "Atorvastatin", "severity": "moderate",
     "effect": "Both carry myopathy risk; CYP3A4 interaction increases colchicine exposure",
     "management": "Use lowest effective doses; monitor for muscle symptoms"},
    {"drug_a": "Losartan", "drug_b": "Potassium Supplements", "severity": "moderate",
     "effect": "ARBs raise potassium; supplemental potassium increases hyperkalaemia risk",
     "management": "Monitor serum K+ regularly; avoid supplements unless documented deficiency"},
    {"drug_a": "Metoprolol", "drug_b": "Verapamil", "severity": "moderate",
     "effect": "Additive bradycardia and heart block; negative chronotropic and dromotropic effects",
     "management": "Avoid combination; monitor ECG and heart rate if essential"},
    {"drug_a": "Ceftriaxone", "drug_b": "Calcium (IV)", "severity": "moderate",
     "effect": "Ceftriaxone precipitates with IV calcium solutions → particulate formation in lungs/kidneys (especially neonates)",
     "management": "Never administer simultaneously in same line; flush thoroughly between drugs"},
    {"drug_a": "Aspirin", "drug_b": "Ibuprofen", "severity": "moderate",
     "effect": "Ibuprofen antagonises aspirin's antiplatelet effect on COX-1",
     "management": "Separate doses: take aspirin at least 30 min before ibuprofen; consider celecoxib instead"},
    {"drug_a": "Hydroxychloroquine", "drug_b": "Metoprolol", "severity": "moderate",
     "effect": "QTc prolongation (additive risk)",
     "management": "Baseline ECG before starting; monitor QTc regularly"},
    {"drug_a": "Azithromycin", "drug_b": "Amiodarone", "severity": "moderate",
     "effect": "Additive QTc prolongation; risk of life-threatening arrhythmia",
     "management": "Avoid combination; use alternative antibiotic"},

    # ── Minor Interactions ────────────────────────────────────────────────────
    {"drug_a": "Paracetamol", "drug_b": "Warfarin", "severity": "minor",
     "effect": "Regular high-dose paracetamol (>2g/day) can mildly raise INR",
     "management": "Use minimum effective paracetamol dose; monitor INR if prolonged use"},
    {"drug_a": "Omeprazole", "drug_b": "Levothyroxine", "severity": "minor",
     "effect": "PPIs may reduce levothyroxine absorption (gastric pH effect)",
     "management": "Take levothyroxine 30-60 minutes before breakfast/PPI; monitor TSH"},
    {"drug_a": "Cetirizine", "drug_b": "Diazepam", "severity": "minor",
     "effect": "Additive sedation",
     "management": "Warn patient about drowsiness; avoid driving or operating machinery"},
    {"drug_a": "Metformin", "drug_b": "Prednisolone", "severity": "minor",
     "effect": "Corticosteroids raise blood glucose; metformin efficacy reduced",
     "management": "Increase blood glucose monitoring; may need insulin during steroid course"},
    {"drug_a": "Enalapril", "drug_b": "Furosemide", "severity": "minor",
     "effect": "First-dose hypotension risk; ACE inhibitor + diuretic can cause profound BP drop",
     "management": "Start ACE inhibitor with low dose; give first dose at bedtime; ensure patient is not volume-depleted"},
]
