"""
Comprehensive India-priority lab test catalogue.
Reference ranges sourced from:
  - ICMR TERIIP national reference interval study
  - Apollo Hospitals multicentric Indian population study (PMC4062657)
  - AIIMS Delhi Department of Laboratory Medicine guidelines
  - Indian Journal of Medical Research standard reference values
  - WHO/IFCC guidelines adapted for Indian population

Each entry: {name, code, category, specialty, unit, normal_range, turnaround_hours}
normal_range format: "M: <range> / F: <range>" for gender-split, or single range.
"""

LAB_TESTS = [

    # ═══════════════════════════════════════════════════════
    # HAEMATOLOGY
    # ═══════════════════════════════════════════════════════

    # CBC Components
    {"name": "Haemoglobin", "code": "HGB", "category": "CBC", "specialty": "Haematology",
     "unit": "g/dL", "normal_range": "M: 13.0–17.0 / F: 12.0–15.5", "turnaround_hours": 2},
    {"name": "Total WBC Count", "code": "WBC", "category": "CBC", "specialty": "Haematology",
     "unit": "cells/µL", "normal_range": "4000–11000", "turnaround_hours": 2},
    {"name": "RBC Count", "code": "RBC", "category": "CBC", "specialty": "Haematology",
     "unit": "million/µL", "normal_range": "M: 4.5–5.5 / F: 3.8–4.8", "turnaround_hours": 2},
    {"name": "Haematocrit (PCV)", "code": "HCT", "category": "CBC", "specialty": "Haematology",
     "unit": "%", "normal_range": "M: 40–50 / F: 36–46", "turnaround_hours": 2},
    {"name": "MCV", "code": "MCV", "category": "CBC", "specialty": "Haematology",
     "unit": "fL", "normal_range": "80–100", "turnaround_hours": 2},
    {"name": "MCH", "code": "MCH", "category": "CBC", "specialty": "Haematology",
     "unit": "pg", "normal_range": "27–33", "turnaround_hours": 2},
    {"name": "MCHC", "code": "MCHC", "category": "CBC", "specialty": "Haematology",
     "unit": "g/dL", "normal_range": "31.5–36.0", "turnaround_hours": 2},
    {"name": "Platelet Count", "code": "PLT", "category": "CBC", "specialty": "Haematology",
     "unit": "lakh/µL", "normal_range": "1.5–4.5", "turnaround_hours": 2},
    {"name": "RDW-CV", "code": "RDW", "category": "CBC", "specialty": "Haematology",
     "unit": "%", "normal_range": "11.5–14.5", "turnaround_hours": 2},
    {"name": "MPV", "code": "MPV", "category": "CBC", "specialty": "Haematology",
     "unit": "fL", "normal_range": "7.5–12.5", "turnaround_hours": 2},
    {"name": "PDW", "code": "PDW", "category": "CBC", "specialty": "Haematology",
     "unit": "fL", "normal_range": "9.0–17.0", "turnaround_hours": 2},

    # Differential WBC
    {"name": "Neutrophils %", "code": "NEU%", "category": "Differential Count", "specialty": "Haematology",
     "unit": "%", "normal_range": "40–70", "turnaround_hours": 2},
    {"name": "Lymphocytes %", "code": "LYM%", "category": "Differential Count", "specialty": "Haematology",
     "unit": "%", "normal_range": "20–40", "turnaround_hours": 2},
    {"name": "Monocytes %", "code": "MON%", "category": "Differential Count", "specialty": "Haematology",
     "unit": "%", "normal_range": "2–8", "turnaround_hours": 2},
    {"name": "Eosinophils %", "code": "EOS%", "category": "Differential Count", "specialty": "Haematology",
     "unit": "%", "normal_range": "1–6", "turnaround_hours": 2},
    {"name": "Basophils %", "code": "BAS%", "category": "Differential Count", "specialty": "Haematology",
     "unit": "%", "normal_range": "0–1", "turnaround_hours": 2},
    {"name": "Absolute Neutrophil Count", "code": "ANC", "category": "Differential Count", "specialty": "Haematology",
     "unit": "cells/µL", "normal_range": "1800–7500", "turnaround_hours": 2},
    {"name": "Absolute Lymphocyte Count", "code": "ALC", "category": "Differential Count", "specialty": "Haematology",
     "unit": "cells/µL", "normal_range": "1000–4800", "turnaround_hours": 2},
    {"name": "Absolute Eosinophil Count", "code": "AEC", "category": "Differential Count", "specialty": "Haematology",
     "unit": "cells/µL", "normal_range": "20–500", "turnaround_hours": 2},

    # Special Haematology
    {"name": "ESR (Erythrocyte Sedimentation Rate)", "code": "ESR", "category": "Haematology", "specialty": "Haematology",
     "unit": "mm/hr", "normal_range": "M: 0–15 / F: 0–20", "turnaround_hours": 2},
    {"name": "Peripheral Blood Smear", "code": "PBS", "category": "Haematology", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Normal morphology", "turnaround_hours": 4},
    {"name": "Reticulocyte Count", "code": "RETIC", "category": "Haematology", "specialty": "Haematology",
     "unit": "%", "normal_range": "0.5–2.5", "turnaround_hours": 4},
    {"name": "Absolute Reticulocyte Count", "code": "ARC", "category": "Haematology", "specialty": "Haematology",
     "unit": "cells/µL", "normal_range": "25000–75000", "turnaround_hours": 4},
    {"name": "Immature Reticulocyte Fraction", "code": "IRF", "category": "Haematology", "specialty": "Haematology",
     "unit": "%", "normal_range": "2–14", "turnaround_hours": 4},
    {"name": "Haemoglobin Electrophoresis", "code": "HGBEP", "category": "Haemoglobinopathy", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "HbA >95%; HbA2 <3.5%; HbF <2%", "turnaround_hours": 24},
    {"name": "HbA2 Quantitation", "code": "HBA2", "category": "Haemoglobinopathy", "specialty": "Haematology",
     "unit": "%", "normal_range": "<3.5", "turnaround_hours": 24},
    {"name": "HbF (Foetal Haemoglobin)", "code": "HBF", "category": "Haemoglobinopathy", "specialty": "Haematology",
     "unit": "%", "normal_range": "<2 (adults)", "turnaround_hours": 24},
    {"name": "Osmotic Fragility Test", "code": "OFT", "category": "Haematology", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Normal resistance pattern", "turnaround_hours": 24},
    {"name": "G6PD Quantitative", "code": "G6PD", "category": "Haematology", "specialty": "Haematology",
     "unit": "U/g Hb", "normal_range": "6.97–20.5", "turnaround_hours": 24},
    {"name": "Sickling Test", "code": "SICK", "category": "Haematology", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 4},
    {"name": "Bone Marrow Aspiration & Biopsy", "code": "BMA", "category": "Haematology", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Normal cellularity & differential", "turnaround_hours": 72},
    {"name": "LE Cell Preparation", "code": "LECELL", "category": "Haematology", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 24},

    # ═══════════════════════════════════════════════════════
    # COAGULATION
    # ═══════════════════════════════════════════════════════

    {"name": "Prothrombin Time (PT)", "code": "PT", "category": "Coagulation", "specialty": "Haematology",
     "unit": "seconds", "normal_range": "11–14", "turnaround_hours": 4},
    {"name": "INR", "code": "INR", "category": "Coagulation", "specialty": "Haematology",
     "unit": "ratio", "normal_range": "0.8–1.2 (therapeutic: 2–3)", "turnaround_hours": 4},
    {"name": "aPTT (Activated Partial Thromboplastin Time)", "code": "APTT", "category": "Coagulation", "specialty": "Haematology",
     "unit": "seconds", "normal_range": "25–38", "turnaround_hours": 4},
    {"name": "Thrombin Time", "code": "TT", "category": "Coagulation", "specialty": "Haematology",
     "unit": "seconds", "normal_range": "14–21", "turnaround_hours": 4},
    {"name": "Fibrinogen", "code": "FIB", "category": "Coagulation", "specialty": "Haematology",
     "unit": "mg/dL", "normal_range": "200–400", "turnaround_hours": 6},
    {"name": "D-Dimer", "code": "DDIM", "category": "Coagulation", "specialty": "Haematology",
     "unit": "µg/mL FEU", "normal_range": "<0.5", "turnaround_hours": 4},
    {"name": "Bleeding Time", "code": "BT", "category": "Coagulation", "specialty": "Haematology",
     "unit": "minutes", "normal_range": "1–7", "turnaround_hours": 1},
    {"name": "Clotting Time", "code": "CT", "category": "Coagulation", "specialty": "Haematology",
     "unit": "minutes", "normal_range": "4–11", "turnaround_hours": 1},
    {"name": "Factor VIII Activity", "code": "F8", "category": "Coagulation Factor", "specialty": "Haematology",
     "unit": "%", "normal_range": "50–200", "turnaround_hours": 24},
    {"name": "Factor IX Activity", "code": "F9", "category": "Coagulation Factor", "specialty": "Haematology",
     "unit": "%", "normal_range": "50–200", "turnaround_hours": 24},
    {"name": "vWF Antigen", "code": "VWF", "category": "Coagulation", "specialty": "Haematology",
     "unit": "%", "normal_range": "50–200", "turnaround_hours": 48},
    {"name": "Protein C Activity", "code": "PROTC", "category": "Thrombophilia", "specialty": "Haematology",
     "unit": "%", "normal_range": "70–130", "turnaround_hours": 48},
    {"name": "Protein S Activity", "code": "PROTS", "category": "Thrombophilia", "specialty": "Haematology",
     "unit": "%", "normal_range": "65–140", "turnaround_hours": 48},
    {"name": "Antithrombin III", "code": "AT3", "category": "Thrombophilia", "specialty": "Haematology",
     "unit": "%", "normal_range": "80–120", "turnaround_hours": 48},
    {"name": "Lupus Anticoagulant", "code": "LAC", "category": "Thrombophilia", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anticardiolipin Antibody IgG/IgM", "code": "ACLA", "category": "Thrombophilia", "specialty": "Haematology",
     "unit": "GPL/MPL", "normal_range": "<10 (negative)", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # BIOCHEMISTRY — LIVER FUNCTION TESTS
    # ═══════════════════════════════════════════════════════

    {"name": "Total Bilirubin", "code": "TBIL", "category": "LFT", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "0.2–1.2", "turnaround_hours": 4},
    {"name": "Direct Bilirubin (Conjugated)", "code": "DBIL", "category": "LFT", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "0.0–0.4", "turnaround_hours": 4},
    {"name": "Indirect Bilirubin", "code": "IBIL", "category": "LFT", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "0.2–0.8", "turnaround_hours": 4},
    {"name": "SGPT / ALT", "code": "ALT", "category": "LFT", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "M: 7–56 / F: 7–45", "turnaround_hours": 4},
    {"name": "SGOT / AST", "code": "AST", "category": "LFT", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "M: 10–40 / F: 10–35", "turnaround_hours": 4},
    {"name": "Alkaline Phosphatase (ALP)", "code": "ALP", "category": "LFT", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "44–147", "turnaround_hours": 4},
    {"name": "GGT (Gamma-Glutamyl Transferase)", "code": "GGT", "category": "LFT", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "M: 8–61 / F: 5–36", "turnaround_hours": 4},
    {"name": "Total Protein", "code": "TP", "category": "LFT", "specialty": "Biochemistry",
     "unit": "g/dL", "normal_range": "6.0–8.3", "turnaround_hours": 4},
    {"name": "Serum Albumin", "code": "ALB", "category": "LFT", "specialty": "Biochemistry",
     "unit": "g/dL", "normal_range": "3.4–5.0", "turnaround_hours": 4},
    {"name": "Serum Globulin", "code": "GLOB", "category": "LFT", "specialty": "Biochemistry",
     "unit": "g/dL", "normal_range": "2.0–3.5", "turnaround_hours": 4},
    {"name": "A:G Ratio", "code": "AGR", "category": "LFT", "specialty": "Biochemistry",
     "unit": "ratio", "normal_range": "1.0–2.5", "turnaround_hours": 4},
    {"name": "LDH (Lactate Dehydrogenase)", "code": "LDH", "category": "Enzyme", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "140–280", "turnaround_hours": 4},
    {"name": "5'-Nucleotidase", "code": "5NT", "category": "LFT", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "0–11", "turnaround_hours": 24},

    # ═══════════════════════════════════════════════════════
    # BIOCHEMISTRY — RENAL FUNCTION TESTS
    # ═══════════════════════════════════════════════════════

    {"name": "Serum Creatinine", "code": "CREAT", "category": "RFT", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "M: 0.7–1.3 / F: 0.6–1.1", "turnaround_hours": 4},
    {"name": "Blood Urea Nitrogen (BUN)", "code": "BUN", "category": "RFT", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "7–20", "turnaround_hours": 4},
    {"name": "Serum Urea", "code": "UREA", "category": "RFT", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "15–45", "turnaround_hours": 4},
    {"name": "eGFR (CKD-EPI)", "code": "EGFR", "category": "RFT", "specialty": "Biochemistry",
     "unit": "mL/min/1.73m²", "normal_range": ">60 (normal)", "turnaround_hours": 4},
    {"name": "Serum Uric Acid", "code": "UA", "category": "RFT", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "M: 3.4–7.0 / F: 2.4–6.0", "turnaround_hours": 4},
    {"name": "BUN:Creatinine Ratio", "code": "BUNCR", "category": "RFT", "specialty": "Biochemistry",
     "unit": "ratio", "normal_range": "10–20", "turnaround_hours": 4},
    {"name": "24-hr Urine Creatinine Clearance", "code": "CCR", "category": "RFT", "specialty": "Biochemistry",
     "unit": "mL/min", "normal_range": "M: 97–137 / F: 88–128", "turnaround_hours": 24},
    {"name": "Urine Microalbumin (Spot)", "code": "MALB", "category": "RFT", "specialty": "Nephrology",
     "unit": "mg/g creatinine", "normal_range": "<30", "turnaround_hours": 6},
    {"name": "Urine Microalbumin (24-hr)", "code": "MALB24", "category": "RFT", "specialty": "Nephrology",
     "unit": "mg/24hr", "normal_range": "<30", "turnaround_hours": 24},
    {"name": "Urine Protein:Creatinine Ratio", "code": "PCR", "category": "RFT", "specialty": "Nephrology",
     "unit": "mg/mmol", "normal_range": "<15", "turnaround_hours": 6},
    {"name": "Cystatin C", "code": "CYSTC", "category": "RFT", "specialty": "Nephrology",
     "unit": "mg/L", "normal_range": "0.52–0.98", "turnaround_hours": 24},
    {"name": "Beta-2 Microglobulin", "code": "B2MG", "category": "RFT", "specialty": "Nephrology",
     "unit": "mg/L", "normal_range": "0.8–2.4 (serum)", "turnaround_hours": 24},

    # ═══════════════════════════════════════════════════════
    # BIOCHEMISTRY — ELECTROLYTES & MINERALS
    # ═══════════════════════════════════════════════════════

    {"name": "Serum Sodium", "code": "NA", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mEq/L", "normal_range": "136–145", "turnaround_hours": 4},
    {"name": "Serum Potassium", "code": "K", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mEq/L", "normal_range": "3.5–5.0", "turnaround_hours": 4},
    {"name": "Serum Chloride", "code": "CL", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mEq/L", "normal_range": "98–106", "turnaround_hours": 4},
    {"name": "Serum Bicarbonate (CO2)", "code": "HCO3", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mEq/L", "normal_range": "22–29", "turnaround_hours": 4},
    {"name": "Serum Calcium (Total)", "code": "CA", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "8.5–10.5", "turnaround_hours": 4},
    {"name": "Serum Calcium (Ionised)", "code": "ICA", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mmol/L", "normal_range": "1.15–1.33", "turnaround_hours": 4},
    {"name": "Serum Magnesium", "code": "MG", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "1.7–2.3", "turnaround_hours": 4},
    {"name": "Serum Phosphorus", "code": "PHOS", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "2.5–4.5", "turnaround_hours": 4},
    {"name": "Anion Gap", "code": "AG", "category": "Electrolytes", "specialty": "Biochemistry",
     "unit": "mEq/L", "normal_range": "8–12", "turnaround_hours": 4},
    {"name": "Serum Iron", "code": "IRON", "category": "Iron Studies", "specialty": "Biochemistry",
     "unit": "µg/dL", "normal_range": "M: 65–175 / F: 50–170", "turnaround_hours": 6},
    {"name": "TIBC (Total Iron Binding Capacity)", "code": "TIBC", "category": "Iron Studies", "specialty": "Biochemistry",
     "unit": "µg/dL", "normal_range": "250–370", "turnaround_hours": 6},
    {"name": "UIBC (Unsaturated Iron Binding Capacity)", "code": "UIBC", "category": "Iron Studies", "specialty": "Biochemistry",
     "unit": "µg/dL", "normal_range": "150–375", "turnaround_hours": 6},
    {"name": "Serum Ferritin", "code": "FERR", "category": "Iron Studies", "specialty": "Biochemistry",
     "unit": "ng/mL", "normal_range": "M: 12–300 / F: 12–150", "turnaround_hours": 6},
    {"name": "Transferrin Saturation", "code": "TSAT", "category": "Iron Studies", "specialty": "Biochemistry",
     "unit": "%", "normal_range": "20–50", "turnaround_hours": 6},
    {"name": "Vitamin B12 (Cobalamin)", "code": "B12", "category": "Vitamins", "specialty": "Biochemistry",
     "unit": "pg/mL", "normal_range": "200–900", "turnaround_hours": 24},
    {"name": "Folate (Serum)", "code": "FOL", "category": "Vitamins", "specialty": "Biochemistry",
     "unit": "ng/mL", "normal_range": ">3.0", "turnaround_hours": 24},
    {"name": "25-OH Vitamin D", "code": "VITD", "category": "Vitamins", "specialty": "Biochemistry",
     "unit": "ng/mL", "normal_range": "20–100 (optimal >30)", "turnaround_hours": 24},
    {"name": "Zinc (Serum)", "code": "ZN", "category": "Trace Elements", "specialty": "Biochemistry",
     "unit": "µg/dL", "normal_range": "70–120", "turnaround_hours": 48},
    {"name": "Copper (Serum)", "code": "CU", "category": "Trace Elements", "specialty": "Biochemistry",
     "unit": "µg/dL", "normal_range": "70–140", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # BIOCHEMISTRY — LIPID PROFILE
    # ═══════════════════════════════════════════════════════

    {"name": "Total Cholesterol", "code": "CHOL", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "<200 (desirable)", "turnaround_hours": 4},
    {"name": "HDL Cholesterol", "code": "HDL", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "M: >40 / F: >50", "turnaround_hours": 4},
    {"name": "LDL Cholesterol", "code": "LDL", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "<100 (optimal)", "turnaround_hours": 4},
    {"name": "VLDL Cholesterol", "code": "VLDL", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "5–40", "turnaround_hours": 4},
    {"name": "Triglycerides", "code": "TG", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "<150 (normal)", "turnaround_hours": 4},
    {"name": "LDL:HDL Ratio", "code": "LDLHDL", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "ratio", "normal_range": "<3.5", "turnaround_hours": 4},
    {"name": "Non-HDL Cholesterol", "code": "NHDL", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "<130", "turnaround_hours": 4},
    {"name": "Lipoprotein(a) [Lp(a)]", "code": "LPA", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "<30", "turnaround_hours": 24},
    {"name": "ApoA1", "code": "APOA1", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "M: 94–178 / F: 101–199", "turnaround_hours": 24},
    {"name": "ApoB", "code": "APOB", "category": "Lipid Profile", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "M: 66–133 / F: 60–117", "turnaround_hours": 24},
    {"name": "Homocysteine", "code": "HCY", "category": "Cardiovascular Risk", "specialty": "Biochemistry",
     "unit": "µmol/L", "normal_range": "5–15", "turnaround_hours": 24},

    # ═══════════════════════════════════════════════════════
    # BIOCHEMISTRY — GLUCOSE / DIABETES
    # ═══════════════════════════════════════════════════════

    {"name": "Fasting Blood Glucose (FBG)", "code": "FBG", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "70–100", "turnaround_hours": 2},
    {"name": "Post-Prandial Blood Glucose (PPBG)", "code": "PPBG", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "<140", "turnaround_hours": 2},
    {"name": "Random Blood Glucose (RBG)", "code": "RBG", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "<200 (diabetes if ≥200 with symptoms)", "turnaround_hours": 1},
    {"name": "HbA1c (Glycated Haemoglobin)", "code": "HBA1C", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "%", "normal_range": "<5.7% normal; 5.7–6.4% prediabetes; ≥6.5% diabetes", "turnaround_hours": 6},
    {"name": "OGTT (75g Oral Glucose Tolerance Test)", "code": "OGTT", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "mg/dL", "normal_range": "2hr <140 normal; 140–199 prediabetes; ≥200 diabetes", "turnaround_hours": 4},
    {"name": "Fasting Insulin", "code": "FINS", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "µIU/mL", "normal_range": "2–25", "turnaround_hours": 24},
    {"name": "HOMA-IR", "code": "HOMIR", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "index", "normal_range": "<2.5", "turnaround_hours": 24},
    {"name": "C-Peptide", "code": "CPEP", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "ng/mL", "normal_range": "0.5–2.0 (fasting)", "turnaround_hours": 24},
    {"name": "Glucagon", "code": "GLUC", "category": "Glucose", "specialty": "Biochemistry",
     "unit": "pg/mL", "normal_range": "20–100", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # BIOCHEMISTRY — CARDIAC MARKERS
    # ═══════════════════════════════════════════════════════

    {"name": "Troponin I (High Sensitivity)", "code": "HSCTNI", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "ng/L", "normal_range": "<16 (M) / <11 (F)", "turnaround_hours": 2},
    {"name": "Troponin T (High Sensitivity)", "code": "HSCTN T", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "ng/L", "normal_range": "<19", "turnaround_hours": 2},
    {"name": "CK-MB (Creatine Kinase-MB)", "code": "CKMB", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "ng/mL", "normal_range": "<3.5", "turnaround_hours": 2},
    {"name": "Total CK (Creatine Kinase)", "code": "CK", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "U/L", "normal_range": "M: 39–308 / F: 26–192", "turnaround_hours": 4},
    {"name": "BNP (B-type Natriuretic Peptide)", "code": "BNP", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "pg/mL", "normal_range": "<100", "turnaround_hours": 4},
    {"name": "NT-proBNP", "code": "NTBNP", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "pg/mL", "normal_range": "<125 (age <75); <450 (age 75–99)", "turnaround_hours": 4},
    {"name": "Myoglobin", "code": "MYO", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "ng/mL", "normal_range": "M: 28–72 / F: 25–58", "turnaround_hours": 2},
    {"name": "CRP (C-Reactive Protein)", "code": "CRP", "category": "Inflammatory", "specialty": "Biochemistry",
     "unit": "mg/L", "normal_range": "<10", "turnaround_hours": 4},
    {"name": "hs-CRP (High-Sensitivity CRP)", "code": "HSCRP", "category": "Inflammatory", "specialty": "Biochemistry",
     "unit": "mg/L", "normal_range": "<1.0 (low risk); 1.0–3.0 (moderate); >3.0 (high)", "turnaround_hours": 6},
    {"name": "Procalcitonin (PCT)", "code": "PCT", "category": "Inflammatory", "specialty": "Biochemistry",
     "unit": "ng/mL", "normal_range": "<0.05 (normal); >2 suggests sepsis", "turnaround_hours": 4},

    # ═══════════════════════════════════════════════════════
    # ENDOCRINOLOGY — THYROID
    # ═══════════════════════════════════════════════════════

    {"name": "TSH (Thyroid Stimulating Hormone)", "code": "TSH", "category": "Thyroid", "specialty": "Endocrinology",
     "unit": "mIU/L", "normal_range": "0.4–4.0 (Indian adults; age-adjusted upper limit 4.5–6.5 in elderly)", "turnaround_hours": 24},
    {"name": "Free T4 (FT4)", "code": "FT4", "category": "Thyroid", "specialty": "Endocrinology",
     "unit": "ng/dL", "normal_range": "0.8–1.8", "turnaround_hours": 24},
    {"name": "Free T3 (FT3)", "code": "FT3", "category": "Thyroid", "specialty": "Endocrinology",
     "unit": "pg/mL", "normal_range": "2.3–4.2", "turnaround_hours": 24},
    {"name": "Total T4 (TT4)", "code": "TT4", "category": "Thyroid", "specialty": "Endocrinology",
     "unit": "µg/dL", "normal_range": "5.0–12.0", "turnaround_hours": 24},
    {"name": "Total T3 (TT3)", "code": "TT3", "category": "Thyroid", "specialty": "Endocrinology",
     "unit": "ng/dL", "normal_range": "80–200", "turnaround_hours": 24},
    {"name": "Anti-Thyroid Peroxidase Ab (Anti-TPO)", "code": "ANTITPO", "category": "Thyroid Antibodies", "specialty": "Endocrinology",
     "unit": "IU/mL", "normal_range": "<34 (negative)", "turnaround_hours": 48},
    {"name": "Anti-Thyroglobulin Ab (Anti-TG)", "code": "ANTITG", "category": "Thyroid Antibodies", "specialty": "Endocrinology",
     "unit": "IU/mL", "normal_range": "<115 (negative)", "turnaround_hours": 48},
    {"name": "TSH Receptor Antibody (TRAb)", "code": "TRAB", "category": "Thyroid Antibodies", "specialty": "Endocrinology",
     "unit": "IU/L", "normal_range": "<1.75 (negative)", "turnaround_hours": 48},
    {"name": "Thyroglobulin", "code": "TG", "category": "Thyroid", "specialty": "Endocrinology",
     "unit": "ng/mL", "normal_range": "1.4–78.0 (non-thyroidectomy)", "turnaround_hours": 48},
    {"name": "Calcitonin", "code": "CALC", "category": "Thyroid", "specialty": "Endocrinology",
     "unit": "pg/mL", "normal_range": "M: <11.5 / F: <4.6", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # ENDOCRINOLOGY — ADRENAL & PITUITARY
    # ═══════════════════════════════════════════════════════

    {"name": "Cortisol (Morning 8AM)", "code": "CORT", "category": "Adrenal", "specialty": "Endocrinology",
     "unit": "µg/dL", "normal_range": "6.0–18.0", "turnaround_hours": 24},
    {"name": "Cortisol (Evening 4PM)", "code": "CORTE", "category": "Adrenal", "specialty": "Endocrinology",
     "unit": "µg/dL", "normal_range": "3.0–10.0", "turnaround_hours": 24},
    {"name": "ACTH (Adrenocorticotropic Hormone)", "code": "ACTH", "category": "Adrenal", "specialty": "Endocrinology",
     "unit": "pg/mL", "normal_range": "7–63 (morning)", "turnaround_hours": 48},
    {"name": "DHEA-S (Dehydroepiandrosterone Sulfate)", "code": "DHEAS", "category": "Adrenal", "specialty": "Endocrinology",
     "unit": "µg/dL", "normal_range": "M: 80–560 / F: 35–430 (age-dependent)", "turnaround_hours": 48},
    {"name": "Aldosterone (Serum)", "code": "ALDO", "category": "Adrenal", "specialty": "Endocrinology",
     "unit": "ng/dL", "normal_range": "4–31 (supine)", "turnaround_hours": 48},
    {"name": "Renin Activity (PRA)", "code": "PRA", "category": "Adrenal", "specialty": "Endocrinology",
     "unit": "ng/mL/hr", "normal_range": "0.2–2.3 (supine)", "turnaround_hours": 48},
    {"name": "Urine Free Cortisol (24-hr)", "code": "UFC", "category": "Adrenal", "specialty": "Endocrinology",
     "unit": "µg/24hr", "normal_range": "20–90", "turnaround_hours": 48},
    {"name": "GH (Growth Hormone)", "code": "GH", "category": "Pituitary", "specialty": "Endocrinology",
     "unit": "ng/mL", "normal_range": "M: 0–2 / F: 0–10 (basal)", "turnaround_hours": 48},
    {"name": "IGF-1 (Insulin-like Growth Factor-1)", "code": "IGF1", "category": "Pituitary", "specialty": "Endocrinology",
     "unit": "ng/mL", "normal_range": "Age/gender specific; adult ~100–300", "turnaround_hours": 48},
    {"name": "Prolactin", "code": "PRL", "category": "Pituitary", "specialty": "Endocrinology",
     "unit": "ng/mL", "normal_range": "M: 2–18 / F (non-pregnant): 2–29", "turnaround_hours": 24},
    {"name": "PTH (Parathyroid Hormone)", "code": "PTH", "category": "Calcium Metabolism", "specialty": "Endocrinology",
     "unit": "pg/mL", "normal_range": "15–65", "turnaround_hours": 24},
    {"name": "PTH-rP (PTH-related Protein)", "code": "PTHRP", "category": "Calcium Metabolism", "specialty": "Endocrinology",
     "unit": "pmol/L", "normal_range": "<2.0", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # ENDOCRINOLOGY — REPRODUCTIVE HORMONES
    # ═══════════════════════════════════════════════════════

    {"name": "FSH (Follicle Stimulating Hormone)", "code": "FSH", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "mIU/mL", "normal_range": "M: 1.5–12.4 / F follicular: 3.5–12.5 / postmenopausal: 25–135", "turnaround_hours": 24},
    {"name": "LH (Luteinizing Hormone)", "code": "LH", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "mIU/mL", "normal_range": "M: 1.7–8.6 / F follicular: 2.4–12.6 / midcycle: 14–96", "turnaround_hours": 24},
    {"name": "Oestradiol (E2)", "code": "E2", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "pg/mL", "normal_range": "F follicular: 12–166 / ovulatory peak: 85–498 / postmenopausal: <55", "turnaround_hours": 24},
    {"name": "Progesterone", "code": "PROG", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "ng/mL", "normal_range": "F follicular: 0.1–0.8 / luteal: 1.7–27 / M: 0.1–0.6", "turnaround_hours": 24},
    {"name": "Total Testosterone (Male)", "code": "TTEST", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "ng/dL", "normal_range": "M: 270–1070 / F: 15–70", "turnaround_hours": 24},
    {"name": "Free Testosterone", "code": "FTEST", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "pg/mL", "normal_range": "M: 9–30 / F: 0.3–1.9", "turnaround_hours": 48},
    {"name": "AMH (Anti-Müllerian Hormone)", "code": "AMH", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "ng/mL", "normal_range": "F: 1.0–3.5 (optimal reproductive age)", "turnaround_hours": 48},
    {"name": "SHBG (Sex Hormone Binding Globulin)", "code": "SHBG", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "nmol/L", "normal_range": "M: 10–57 / F: 18–144", "turnaround_hours": 48},
    {"name": "Beta-HCG (Serum)", "code": "BHCG", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "mIU/mL", "normal_range": "Non-pregnant: <5; positive if >25", "turnaround_hours": 6},
    {"name": "17-OH Progesterone", "code": "17OHP", "category": "Reproductive Hormones", "specialty": "Endocrinology",
     "unit": "ng/dL", "normal_range": "M: 27–199 / F follicular: 15–70 / luteal: 35–290", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # SEROLOGY / IMMUNOLOGY
    # ═══════════════════════════════════════════════════════

    {"name": "HBsAg (Hepatitis B Surface Antigen)", "code": "HBSAG", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive (negative)", "turnaround_hours": 4},
    {"name": "Anti-HBs (Hepatitis B Surface Antibody)", "code": "ANTIHBS", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "mIU/mL", "normal_range": ">10 mIU/mL (immune)", "turnaround_hours": 24},
    {"name": "Anti-HBc IgM", "code": "HBCIGM", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "Anti-HBc Total", "code": "HBCTOT", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "HBeAg", "code": "HBEAG", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "Anti-HBe", "code": "ANTIHBE", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive / Reactive (seroconversion expected)", "turnaround_hours": 24},
    {"name": "HBV DNA (Hepatitis B Viral Load)", "code": "HBVDNA", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "IU/mL", "normal_range": "Undetectable (<10–20 IU/mL)", "turnaround_hours": 48},
    {"name": "Anti-HCV (Hepatitis C Antibody)", "code": "ANTIHCV", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 4},
    {"name": "HCV RNA (Hepatitis C Viral Load)", "code": "HCVRNA", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "IU/mL", "normal_range": "Undetectable", "turnaround_hours": 48},
    {"name": "Anti-HAV IgM (Hepatitis A IgM)", "code": "HAVIGG", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "Anti-HEV IgM (Hepatitis E IgM)", "code": "HEVIGG", "category": "Viral Hepatitis", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "HIV 1&2 Antibody (ELISA)", "code": "HIV12", "category": "Retrovirus", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 4},
    {"name": "HIV p24 Antigen", "code": "HIVAG", "category": "Retrovirus", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 4},
    {"name": "HIV RNA (Viral Load)", "code": "HIVVL", "category": "Retrovirus", "specialty": "Serology",
     "unit": "copies/mL", "normal_range": "Undetectable (<50 copies/mL on ART)", "turnaround_hours": 48},
    {"name": "CD4 Count", "code": "CD4", "category": "Immunology", "specialty": "Serology",
     "unit": "cells/µL", "normal_range": "500–1500", "turnaround_hours": 24},
    {"name": "VDRL / RPR (Syphilis Screen)", "code": "VDRL", "category": "Serology", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 4},
    {"name": "TPHA / TPPA (Syphilis Confirmatory)", "code": "TPHA", "category": "Serology", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},

    # ═══════════════════════════════════════════════════════
    # AUTOIMMUNE / RHEUMATOLOGY
    # ═══════════════════════════════════════════════════════

    {"name": "ANA (Antinuclear Antibody)", "code": "ANA", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "titre", "normal_range": "Negative (<1:80)", "turnaround_hours": 48},
    {"name": "ANA Pattern (IIF)", "code": "ANAPAT", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anti-dsDNA", "code": "DSDNA", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "IU/mL", "normal_range": "<10 (negative)", "turnaround_hours": 48},
    {"name": "Anti-Sm Antibody", "code": "ANTISM", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anti-SSA (Ro)", "code": "ANTISSA", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anti-SSB (La)", "code": "ANTISSB", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anti-Scl-70 (Topoisomerase I)", "code": "SCL70", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anti-Jo-1", "code": "ANTIJO1", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anti-CCP (Cyclic Citrullinated Peptide)", "code": "ANTICCP", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "U/mL", "normal_range": "<20 (negative)", "turnaround_hours": 48},
    {"name": "Rheumatoid Factor (RF)", "code": "RF", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "IU/mL", "normal_range": "<20 (negative)", "turnaround_hours": 24},
    {"name": "HLA-B27", "code": "HLAB27", "category": "HLA Typing", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative / Not detected", "turnaround_hours": 48},
    {"name": "c-ANCA (PR3-ANCA)", "code": "CANCA", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "p-ANCA (MPO-ANCA)", "code": "PANCA", "category": "Autoimmune", "specialty": "Rheumatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Complement C3", "code": "C3", "category": "Complement", "specialty": "Rheumatology",
     "unit": "mg/dL", "normal_range": "90–180", "turnaround_hours": 24},
    {"name": "Complement C4", "code": "C4", "category": "Complement", "specialty": "Rheumatology",
     "unit": "mg/dL", "normal_range": "16–47", "turnaround_hours": 24},
    {"name": "Total Complement (CH50)", "code": "CH50", "category": "Complement", "specialty": "Rheumatology",
     "unit": "U/mL", "normal_range": "41–90", "turnaround_hours": 48},
    {"name": "Anti-Mitochondrial Ab (AMA)", "code": "AMA", "category": "Autoimmune", "specialty": "Hepatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "Anti-Smooth Muscle Ab (ASMA)", "code": "ASMA", "category": "Autoimmune", "specialty": "Hepatology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},
    {"name": "IgG4 (Immunoglobulin G4)", "code": "IGG4", "category": "Immunoglobulins", "specialty": "Rheumatology",
     "unit": "mg/dL", "normal_range": "3–201", "turnaround_hours": 48},
    {"name": "Serum IgG", "code": "IGG", "category": "Immunoglobulins", "specialty": "Immunology",
     "unit": "mg/dL", "normal_range": "700–1600", "turnaround_hours": 24},
    {"name": "Serum IgA", "code": "IGA", "category": "Immunoglobulins", "specialty": "Immunology",
     "unit": "mg/dL", "normal_range": "70–400", "turnaround_hours": 24},
    {"name": "Serum IgM", "code": "IGM", "category": "Immunoglobulins", "specialty": "Immunology",
     "unit": "mg/dL", "normal_range": "40–230", "turnaround_hours": 24},
    {"name": "Serum IgE (Total)", "code": "IGE", "category": "Allergy", "specialty": "Immunology",
     "unit": "IU/mL", "normal_range": "<100 (adults)", "turnaround_hours": 24},

    # ═══════════════════════════════════════════════════════
    # INFECTIOUS DISEASE — INDIA SPECIFIC
    # ═══════════════════════════════════════════════════════

    # Dengue
    {"name": "Dengue NS1 Antigen (Rapid)", "code": "DENNS1", "category": "Dengue", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Non-reactive (negative)", "turnaround_hours": 2},
    {"name": "Dengue IgM Antibody (ELISA)", "code": "DENIG M", "category": "Dengue", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 6},
    {"name": "Dengue IgG Antibody", "code": "DENIGG", "category": "Dengue", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Non-reactive (indicates past infection if positive)", "turnaround_hours": 6},
    {"name": "Dengue NS1 + IgM/IgG Combo", "code": "DENCOMBO", "category": "Dengue", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "All non-reactive", "turnaround_hours": 2},
    {"name": "Dengue RNA (RT-PCR)", "code": "DENPCR", "category": "Dengue", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 24},

    # Malaria
    {"name": "Malaria Antigen Test (PfHRP2/pLDH)", "code": "MALRAP", "category": "Malaria", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 1},
    {"name": "Malaria Peripheral Smear (Thick & Thin)", "code": "MALSMEAR", "category": "Malaria", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "No parasite seen", "turnaround_hours": 4},
    {"name": "Malaria PCR (P. falciparum / P. vivax)", "code": "MALPCR", "category": "Malaria", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 24},

    # Typhoid / Enteric
    {"name": "Widal Test", "code": "WIDAL", "category": "Typhoid", "specialty": "Infectious Disease",
     "unit": "titre", "normal_range": "O and H titres <1:80 (endemic areas: significant if ≥1:160)", "turnaround_hours": 4},
    {"name": "Typhoid IgM (Tubex / ELISA)", "code": "TYPHIGM", "category": "Typhoid", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 4},
    {"name": "Blood Culture (Enteric)", "code": "BLCULT", "category": "Culture", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No growth", "turnaround_hours": 120},

    # Tuberculosis
    {"name": "Mantoux Test (TST)", "code": "MANT", "category": "Tuberculosis", "specialty": "Infectious Disease",
     "unit": "mm induration", "normal_range": "<10mm (not immunocompromised); <5mm (immunocompromised)", "turnaround_hours": 72},
    {"name": "IGRA (QuantiFERON-TB Gold Plus)", "code": "IGRA", "category": "Tuberculosis", "specialty": "Infectious Disease",
     "unit": "IU/mL", "normal_range": "Negative: <0.35 IU/mL; Positive: ≥0.35", "turnaround_hours": 24},
    {"name": "CBNAAT / GeneXpert (Sputum)", "code": "CBNAAT", "category": "Tuberculosis", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "MTB Not Detected; Rifampicin resistance Not Detected", "turnaround_hours": 4},
    {"name": "Sputum AFB Smear (ZN Stain)", "code": "AFBSMR", "category": "Tuberculosis", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No AFB seen", "turnaround_hours": 4},
    {"name": "Sputum AFB Culture (MGIT)", "code": "AFBCUL", "category": "Tuberculosis", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No growth", "turnaround_hours": 336},
    {"name": "TB Drug Susceptibility Testing (DST)", "code": "TBDST", "category": "Tuberculosis", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "Susceptible to first-line drugs", "turnaround_hours": 336},

    # Scrub Typhus / Rickettsial
    {"name": "Scrub Typhus IgM ELISA", "code": "SCRUBIGM", "category": "Rickettsial", "specialty": "Infectious Disease",
     "unit": "OD / qualitative", "normal_range": "Negative", "turnaround_hours": 24},
    {"name": "Scrub Typhus Rapid Test (IgM ICT)", "code": "SCRUBRP", "category": "Rickettsial", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 2},
    {"name": "Weil-Felix Test", "code": "WEILF", "category": "Rickettsial", "specialty": "Infectious Disease",
     "unit": "titre", "normal_range": "Negative / <1:40", "turnaround_hours": 24},

    # Leptospirosis
    {"name": "Leptospira IgM ELISA", "code": "LEPTIM", "category": "Leptospirosis", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 24},
    {"name": "Leptospira MAT (Microscopic Agglutination Test)", "code": "LEPMAT", "category": "Leptospirosis", "specialty": "Infectious Disease",
     "unit": "titre", "normal_range": "<1:100 (non-endemic); significant ≥1:400 in endemic area", "turnaround_hours": 48},

    # Chikungunya
    {"name": "Chikungunya IgM ELISA", "code": "CHIKIGM", "category": "Arboviral", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "Chikungunya RT-PCR", "code": "CHIKPCR", "category": "Arboviral", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 24},

    # COVID-19
    {"name": "COVID-19 Antigen (Rapid)", "code": "COVAG", "category": "COVID-19", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 1},
    {"name": "COVID-19 RT-PCR (SARS-CoV-2)", "code": "COVPCR", "category": "COVID-19", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 6},
    {"name": "COVID-19 IgG Antibody (S1/RBD)", "code": "COVIGG", "category": "COVID-19", "specialty": "Infectious Disease",
     "unit": "AU/mL", "normal_range": ">50 AU/mL (positive/immune)", "turnaround_hours": 24},

    # Other Infectious
    {"name": "Brucella Serology (RBPT / SAT)", "code": "BRUC", "category": "Serology", "specialty": "Infectious Disease",
     "unit": "titre", "normal_range": "Non-reactive / <1:80", "turnaround_hours": 24},
    {"name": "Toxoplasma IgM", "code": "TOXIGM", "category": "Serology", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "Toxoplasma IgG", "code": "TOXIGG", "category": "Serology", "specialty": "Infectious Disease",
     "unit": "IU/mL", "normal_range": "<3 (negative)", "turnaround_hours": 24},
    {"name": "CMV IgM / IgG", "code": "CMVAB", "category": "Serology", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "IgM negative; IgG indicates past exposure", "turnaround_hours": 24},
    {"name": "EBV (Monospot / VCA IgM)", "code": "EBVAB", "category": "Serology", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Non-reactive", "turnaround_hours": 24},
    {"name": "HSV 1&2 IgM / IgG", "code": "HSVAB", "category": "Serology", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "IgM: Non-reactive", "turnaround_hours": 24},
    {"name": "Rubella IgM / IgG", "code": "RUBAB", "category": "Serology", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "IgM: Non-reactive; IgG: >10 IU/mL (immune)", "turnaround_hours": 24},
    {"name": "Typhus IgG (Epidemic / Murine)", "code": "TYPHGR", "category": "Rickettsial", "specialty": "Infectious Disease",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # MICROBIOLOGY — CULTURES & SENSITIVITIES
    # ═══════════════════════════════════════════════════════

    {"name": "Urine Culture & Sensitivity", "code": "URICULSEN", "category": "Urine", "specialty": "Microbiology",
     "unit": "CFU/mL", "normal_range": "No significant growth (<10^4 CFU/mL)", "turnaround_hours": 48},
    {"name": "Throat Swab Culture", "code": "THROATCUL", "category": "Culture", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No pathogen isolated", "turnaround_hours": 48},
    {"name": "Wound Swab Culture & Sensitivity", "code": "WOUNDCUL", "category": "Culture", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No pathogen isolated", "turnaround_hours": 48},
    {"name": "Stool Culture (Enteric Pathogens)", "code": "STOOLCUL", "category": "Culture", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No pathogen isolated", "turnaround_hours": 72},
    {"name": "CSF Culture & Sensitivity", "code": "CSFCUL", "category": "Culture", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No growth", "turnaround_hours": 72},
    {"name": "Sputum Culture & Sensitivity", "code": "SPUTCUL", "category": "Culture", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No significant pathogen", "turnaround_hours": 48},
    {"name": "MRSA Screening Swab", "code": "MRSA", "category": "Surveillance", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "MRSA not isolated", "turnaround_hours": 48},
    {"name": "KPC / ESBL Screening", "code": "ESBL", "category": "Surveillance", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 48},
    {"name": "Stool Microscopy (Ova & Parasite)", "code": "STOOLOMP", "category": "Stool", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No ova/cysts/parasites seen", "turnaround_hours": 4},
    {"name": "Stool Occult Blood (FOB)", "code": "STOOLFOB", "category": "Stool", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 4},
    {"name": "Stool Rotavirus Antigen", "code": "ROTAAG", "category": "Viral", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 4},
    {"name": "H. pylori Stool Antigen", "code": "HPYLSA", "category": "H. pylori", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 4},
    {"name": "H. pylori IgG Antibody (Serum)", "code": "HPYLGAB", "category": "H. pylori", "specialty": "Serology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 24},
    {"name": "Urea Breath Test (UBT)", "code": "UBT", "category": "H. pylori", "specialty": "Microbiology",
     "unit": "delta over baseline", "normal_range": "<4 (negative)", "turnaround_hours": 1},
    {"name": "KOH Mount / Fungal Smear", "code": "KOHMT", "category": "Fungal", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No fungal elements seen", "turnaround_hours": 2},
    {"name": "Fungal Culture", "code": "FUNGCUL", "category": "Fungal", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No growth", "turnaround_hours": 168},

    # ═══════════════════════════════════════════════════════
    # URINE ANALYSIS
    # ═══════════════════════════════════════════════════════

    {"name": "Urine Routine & Microscopy (R/M)", "code": "URIRM", "category": "Urinalysis", "specialty": "Urology",
     "unit": "qualitative / quantitative", "normal_range": "pH 4.5–8.0; Sp.gravity 1.003–1.030; Protein nil; Glucose nil; RBC 0–2/hpf; WBC 0–5/hpf", "turnaround_hours": 2},
    {"name": "Urine pH", "code": "URIPH", "category": "Urinalysis", "specialty": "Urology",
     "unit": "pH", "normal_range": "4.5–8.0", "turnaround_hours": 1},
    {"name": "Urine Specific Gravity", "code": "URISG", "category": "Urinalysis", "specialty": "Urology",
     "unit": "ratio", "normal_range": "1.003–1.030", "turnaround_hours": 1},
    {"name": "Urine Protein (Spot)", "code": "URIPROT", "category": "Urinalysis", "specialty": "Urology",
     "unit": "mg/dL", "normal_range": "Nil (trace to 8 mg/dL acceptable)", "turnaround_hours": 2},
    {"name": "24-hr Urine Protein", "code": "U24PRO", "category": "Urinalysis", "specialty": "Nephrology",
     "unit": "mg/24hr", "normal_range": "<150", "turnaround_hours": 24},
    {"name": "Urine Glucose (Dipstick)", "code": "URIGLU", "category": "Urinalysis", "specialty": "Urology",
     "unit": "qualitative", "normal_range": "Nil", "turnaround_hours": 1},
    {"name": "Urine Ketones", "code": "URIKET", "category": "Urinalysis", "specialty": "Urology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 1},
    {"name": "Urine Bilirubin", "code": "URIBIL", "category": "Urinalysis", "specialty": "Urology",
     "unit": "qualitative", "normal_range": "Negative", "turnaround_hours": 1},
    {"name": "Urine Urobilinogen", "code": "URIURO", "category": "Urinalysis", "specialty": "Urology",
     "unit": "EU/dL", "normal_range": "0.1–1.0", "turnaround_hours": 1},
    {"name": "Urine Calcium (24-hr)", "code": "URICA24", "category": "Stone Workup", "specialty": "Nephrology",
     "unit": "mg/24hr", "normal_range": "M: <300 / F: <250", "turnaround_hours": 24},
    {"name": "Urine Oxalate (24-hr)", "code": "URIOX", "category": "Stone Workup", "specialty": "Nephrology",
     "unit": "mg/24hr", "normal_range": "<40", "turnaround_hours": 24},
    {"name": "Urine Uric Acid (24-hr)", "code": "URIUA", "category": "Stone Workup", "specialty": "Nephrology",
     "unit": "mg/24hr", "normal_range": "<800", "turnaround_hours": 24},

    # ═══════════════════════════════════════════════════════
    # ONCOLOGY MARKERS
    # ═══════════════════════════════════════════════════════

    {"name": "PSA Total (Prostate Specific Antigen)", "code": "TPSA", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "ng/mL", "normal_range": "<4.0 (age-specific: <50: <2.5; 50–59: <3.5; 60–69: <4.5; >70: <6.5)", "turnaround_hours": 24},
    {"name": "PSA Free", "code": "FPSA", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "ng/mL", "normal_range": "Free:Total PSA ratio >25% (lower malignancy risk)", "turnaround_hours": 24},
    {"name": "CEA (Carcinoembryonic Antigen)", "code": "CEA", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "ng/mL", "normal_range": "<3.0 (non-smokers); <5.0 (smokers)", "turnaround_hours": 24},
    {"name": "CA-125 (Cancer Antigen 125)", "code": "CA125", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "U/mL", "normal_range": "<35", "turnaround_hours": 24},
    {"name": "CA 19-9 (Cancer Antigen 19-9)", "code": "CA199", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "U/mL", "normal_range": "<37", "turnaround_hours": 24},
    {"name": "CA 15-3 (Cancer Antigen 15-3)", "code": "CA153", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "U/mL", "normal_range": "<30", "turnaround_hours": 24},
    {"name": "AFP (Alpha-Fetoprotein)", "code": "AFP", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "ng/mL", "normal_range": "<10 (adults)", "turnaround_hours": 24},
    {"name": "Beta-HCG (Tumour Marker)", "code": "BHCGTM", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "mIU/mL", "normal_range": "<5 (non-pregnant)", "turnaround_hours": 6},
    {"name": "LDH (Tumour Marker)", "code": "LDHTM", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "U/L", "normal_range": "140–280", "turnaround_hours": 4},
    {"name": "CA 72-4", "code": "CA724", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "U/mL", "normal_range": "<6.9", "turnaround_hours": 24},
    {"name": "NSE (Neuron Specific Enolase)", "code": "NSE", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "ng/mL", "normal_range": "<16.3", "turnaround_hours": 24},
    {"name": "SCC Antigen (Squamous Cell Carcinoma)", "code": "SCCAG", "category": "Tumour Markers", "specialty": "Oncology",
     "unit": "ng/mL", "normal_range": "<1.5", "turnaround_hours": 24},
    {"name": "Chromogranin A", "code": "CGA", "category": "Neuroendocrine", "specialty": "Oncology",
     "unit": "ng/mL", "normal_range": "<93", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # NEPHROLOGY SPECIAL
    # ═══════════════════════════════════════════════════════

    {"name": "Serum Complement C3 & C4 (Nephrology)", "code": "NEPHC3C4", "category": "Complement", "specialty": "Nephrology",
     "unit": "mg/dL", "normal_range": "C3: 90–180; C4: 16–47", "turnaround_hours": 24},
    {"name": "Anti-GBM Antibody (Goodpasture)", "code": "ANTIGBM", "category": "Autoimmune", "specialty": "Nephrology",
     "unit": "U/mL", "normal_range": "<20 (negative)", "turnaround_hours": 48},
    {"name": "Urine Osmolality", "code": "URIOSM", "category": "Urinalysis", "specialty": "Nephrology",
     "unit": "mOsm/kg", "normal_range": "50–1200", "turnaround_hours": 6},
    {"name": "Serum Osmolality", "code": "SEROSM", "category": "Biochemistry", "specialty": "Nephrology",
     "unit": "mOsm/kg", "normal_range": "275–295", "turnaround_hours": 6},

    # ═══════════════════════════════════════════════════════
    # REPRODUCTIVE / PRENATAL
    # ═══════════════════════════════════════════════════════

    {"name": "TORCH Panel (IgM & IgG)", "code": "TORCH", "category": "Prenatal", "specialty": "Reproductive Health",
     "unit": "qualitative", "normal_range": "All IgM: Non-reactive", "turnaround_hours": 48},
    {"name": "Semen Analysis (WHO 2021)", "code": "SEMEN", "category": "Fertility", "specialty": "Reproductive Health",
     "unit": "various", "normal_range": "Vol ≥1.4mL; Conc ≥16M/mL; Total motility ≥42%; Progressive motility ≥30%; Normal morphology ≥4%", "turnaround_hours": 4},
    {"name": "Sperm DNA Fragmentation Index (DFI)", "code": "SPMDFI", "category": "Fertility", "specialty": "Reproductive Health",
     "unit": "%", "normal_range": "<15% (good fertility potential)", "turnaround_hours": 48},
    {"name": "PCOS Hormonal Panel (FSH, LH, E2, Testosterone, DHEAS, Prolactin)", "code": "PCOSPANEL", "category": "PCOS", "specialty": "Endocrinology",
     "unit": "various", "normal_range": "LH:FSH ratio <3:1; Testosterone <70 ng/dL (F); Prolactin <29 ng/mL", "turnaround_hours": 48},
    {"name": "Pap Smear (Cervical Cytology)", "code": "PAPSMR", "category": "Gynaecology", "specialty": "Reproductive Health",
     "unit": "Bethesda system", "normal_range": "Negative for intraepithelial lesion or malignancy (NILM)", "turnaround_hours": 48},
    {"name": "HPV DNA (High Risk Genotyping)", "code": "HPVDNA", "category": "Gynaecology", "specialty": "Reproductive Health",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 48},
    {"name": "First Trimester Screening (PAPP-A + free beta-HCG)", "code": "FTS", "category": "Prenatal Screening", "specialty": "Reproductive Health",
     "unit": "MoM", "normal_range": "PAPP-A >0.4 MoM; Risk-based assessment with NT measurement", "turnaround_hours": 24},
    {"name": "Triple Marker / Quadruple Screen", "code": "TRIPLMRK", "category": "Prenatal Screening", "specialty": "Reproductive Health",
     "unit": "MoM", "normal_range": "Risk score <1:250 for Down syndrome", "turnaround_hours": 48},

    # ═══════════════════════════════════════════════════════
    # GENETICS / MOLECULAR
    # ═══════════════════════════════════════════════════════

    {"name": "Karyotype (Peripheral Blood)", "code": "KARY", "category": "Chromosomal", "specialty": "Genetics",
     "unit": "qualitative", "normal_range": "46,XX (female) / 46,XY (male)", "turnaround_hours": 336},
    {"name": "FISH (Fluorescence In Situ Hybridisation)", "code": "FISH", "category": "Chromosomal", "specialty": "Genetics",
     "unit": "qualitative", "normal_range": "No chromosomal abnormality detected", "turnaround_hours": 168},
    {"name": "BRCA1/BRCA2 Gene Mutation Analysis", "code": "BRCA", "category": "Molecular", "specialty": "Genetics",
     "unit": "qualitative", "normal_range": "No pathogenic variant detected", "turnaround_hours": 336},
    {"name": "JAK2 V617F Mutation (MPN Screen)", "code": "JAK2", "category": "Molecular", "specialty": "Haematology",
     "unit": "qualitative / allele burden %", "normal_range": "Not detected", "turnaround_hours": 168},
    {"name": "BCR-ABL1 (CML Monitoring, qPCR)", "code": "BCRABL", "category": "Molecular", "specialty": "Haematology",
     "unit": "% IS (International Scale)", "normal_range": "Undetectable (deep molecular remission)", "turnaround_hours": 168},
    {"name": "FLT3 ITD/TKD Mutation (AML)", "code": "FLT3", "category": "Molecular", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 168},
    {"name": "NPM1 Mutation", "code": "NPM1", "category": "Molecular", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Wild type", "turnaround_hours": 168},
    {"name": "Factor V Leiden Mutation", "code": "FVL", "category": "Thrombophilia", "specialty": "Genetics",
     "unit": "qualitative", "normal_range": "Wild type (normal)", "turnaround_hours": 168},
    {"name": "MTHFR Mutation (C677T / A1298C)", "code": "MTHFR", "category": "Thrombophilia", "specialty": "Genetics",
     "unit": "qualitative", "normal_range": "Wild type", "turnaround_hours": 168},
    {"name": "Beta-Thalassaemia Mutation Analysis", "code": "THALMUT", "category": "Haemoglobinopathy", "specialty": "Genetics",
     "unit": "qualitative", "normal_range": "No pathogenic mutation detected", "turnaround_hours": 336},
    {"name": "Sickle Cell Mutation (HbS)", "code": "SICKMUT", "category": "Haemoglobinopathy", "specialty": "Genetics",
     "unit": "qualitative", "normal_range": "Not detected", "turnaround_hours": 168},

    # ═══════════════════════════════════════════════════════
    # PAEDIATRIC SPECIFIC
    # ═══════════════════════════════════════════════════════

    {"name": "Newborn Screening (NBS) — CH, PKU, CAH, G6PD, Galactosaemia", "code": "NBS", "category": "Newborn Screening", "specialty": "Paediatrics",
     "unit": "various", "normal_range": "TSH <10 mIU/L (CH screen); Phe <2 mg/dL (PKU screen)", "turnaround_hours": 48},
    {"name": "Neonatal Bilirubin (Total)", "code": "NBIL", "category": "Neonatal", "specialty": "Paediatrics",
     "unit": "mg/dL", "normal_range": "Day 1: <6; Day 3: <12; Day 5: <15 (full-term)", "turnaround_hours": 2},
    {"name": "Neonatal Blood Glucose", "code": "NBG", "category": "Neonatal", "specialty": "Paediatrics",
     "unit": "mg/dL", "normal_range": ">45 (neonatal hypoglycaemia <45)", "turnaround_hours": 1},
    {"name": "IgE RAST (Specific Allergen Panel)", "code": "RAST", "category": "Allergy", "specialty": "Paediatrics",
     "unit": "kIU/L", "normal_range": "Class 0 (<0.35): undetectable", "turnaround_hours": 48},
    {"name": "Sweat Chloride (Cystic Fibrosis Screen)", "code": "SWCL", "category": "Paediatrics", "specialty": "Paediatrics",
     "unit": "mmol/L", "normal_range": "<40 normal; 40–59 borderline; ≥60 positive", "turnaround_hours": 24},
    {"name": "Amino Acid Profile (Plasma)", "code": "AMINOAA", "category": "Metabolic", "specialty": "Paediatrics",
     "unit": "µmol/L", "normal_range": "Within age-specific reference ranges", "turnaround_hours": 72},
    {"name": "Lactate (Serum)", "code": "LACT", "category": "Metabolic", "specialty": "Paediatrics",
     "unit": "mmol/L", "normal_range": "0.5–2.2 (venous)", "turnaround_hours": 4},
    {"name": "Ammonia (Blood)", "code": "NH3", "category": "Metabolic", "specialty": "Paediatrics",
     "unit": "µmol/L", "normal_range": "Neonates: 28–110; Children/Adults: 11–32", "turnaround_hours": 2},
    {"name": "Tandem Mass Spectrometry (MS/MS) Metabolic Screen", "code": "MSMS", "category": "Newborn Screening", "specialty": "Paediatrics",
     "unit": "qualitative", "normal_range": "No metabolic disorder detected", "turnaround_hours": 72},

    # ═══════════════════════════════════════════════════════
    # CSF ANALYSIS
    # ═══════════════════════════════════════════════════════

    {"name": "CSF Cell Count & Differential", "code": "CSFCC", "category": "CSF", "specialty": "Neurology",
     "unit": "cells/µL", "normal_range": "0–5 mononuclear cells/µL; no RBCs", "turnaround_hours": 4},
    {"name": "CSF Protein", "code": "CSFPRO", "category": "CSF", "specialty": "Neurology",
     "unit": "mg/dL", "normal_range": "15–45", "turnaround_hours": 4},
    {"name": "CSF Glucose", "code": "CSFGLU", "category": "CSF", "specialty": "Neurology",
     "unit": "mg/dL", "normal_range": "50–80 (60–80% of serum glucose)", "turnaround_hours": 4},
    {"name": "CSF Chloride", "code": "CSFCL", "category": "CSF", "specialty": "Neurology",
     "unit": "mEq/L", "normal_range": "120–130", "turnaround_hours": 4},
    {"name": "CSF ADA (Adenosine Deaminase)", "code": "CSFADA", "category": "CSF", "specialty": "Neurology",
     "unit": "U/L", "normal_range": "<10 U/L (>10 suggestive TB meningitis)", "turnaround_hours": 24},
    {"name": "CSF India Ink Preparation (Cryptococcus)", "code": "CSFIINK", "category": "CSF", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No encapsulated yeast seen", "turnaround_hours": 4},
    {"name": "CSF Gram Stain", "code": "CSFGRAM", "category": "CSF", "specialty": "Microbiology",
     "unit": "qualitative", "normal_range": "No organisms seen", "turnaround_hours": 2},

    # ═══════════════════════════════════════════════════════
    # PLEURAL / PERITONEAL / SYNOVIAL FLUID
    # ═══════════════════════════════════════════════════════

    {"name": "Pleural Fluid Analysis (LDH, Protein, Cell Count, pH)", "code": "PLEURAL", "category": "Body Fluids", "specialty": "Pulmonology",
     "unit": "various", "normal_range": "Light's criteria: Exudate if fluid:serum LDH >0.6 or protein >0.5", "turnaround_hours": 6},
    {"name": "Pleural Fluid ADA", "code": "PLADA", "category": "Body Fluids", "specialty": "Pulmonology",
     "unit": "U/L", "normal_range": ">40 U/L suggestive of TB pleuritis", "turnaround_hours": 24},
    {"name": "Ascitic Fluid Analysis (SAAG, protein, LDH)", "code": "ASCITIC", "category": "Body Fluids", "specialty": "Gastroenterology",
     "unit": "various", "normal_range": "SAAG ≥1.1 g/dL = portal hypertension aetiology", "turnaround_hours": 6},
    {"name": "Synovial Fluid Analysis (Glucose, Protein, Cell Count, Crystals)", "code": "SYNOVIAL", "category": "Body Fluids", "specialty": "Rheumatology",
     "unit": "various", "normal_range": "WBC <200/µL; no crystals; no organisms", "turnaround_hours": 6},

    # ═══════════════════════════════════════════════════════
    # ARTERIAL BLOOD GAS (ABG)
    # ═══════════════════════════════════════════════════════

    {"name": "Arterial Blood Gas (ABG)", "code": "ABG", "category": "Blood Gas", "specialty": "Pulmonology",
     "unit": "various", "normal_range": "pH 7.35–7.45; pO2 75–100 mmHg; pCO2 35–45 mmHg; HCO3 22–26 mEq/L; SpO2 >95%", "turnaround_hours": 1},
    {"name": "Lactate (ABG)", "code": "ABGLAC", "category": "Blood Gas", "specialty": "Pulmonology",
     "unit": "mmol/L", "normal_range": "<2.0 (critical >4.0)", "turnaround_hours": 1},

    # ═══════════════════════════════════════════════════════
    # MISCELLANEOUS / SPECIAL BIOCHEMISTRY
    # ═══════════════════════════════════════════════════════

    {"name": "Amylase (Serum)", "code": "AMYL", "category": "Pancreatic Enzymes", "specialty": "Gastroenterology",
     "unit": "U/L", "normal_range": "30–110", "turnaround_hours": 4},
    {"name": "Lipase (Serum)", "code": "LIP", "category": "Pancreatic Enzymes", "specialty": "Gastroenterology",
     "unit": "U/L", "normal_range": "0–160", "turnaround_hours": 4},
    {"name": "Urine Amylase (24-hr)", "code": "UAMYL", "category": "Pancreatic Enzymes", "specialty": "Gastroenterology",
     "unit": "U/hr", "normal_range": "1–17", "turnaround_hours": 24},
    {"name": "CA 19-9 (Pancreatitis monitoring)", "code": "CA199PAN", "category": "Tumour Markers", "specialty": "Gastroenterology",
     "unit": "U/mL", "normal_range": "<37", "turnaround_hours": 24},
    {"name": "Troponin T / Point-of-care (POC)", "code": "CTNTPOC", "category": "Cardiac Markers", "specialty": "Cardiology",
     "unit": "ng/mL", "normal_range": "<0.01", "turnaround_hours": 1},
    {"name": "Fibrin Degradation Products (FDP)", "code": "FDP", "category": "Coagulation", "specialty": "Haematology",
     "unit": "µg/mL", "normal_range": "<10", "turnaround_hours": 6},
    {"name": "ADA (Serum Adenosine Deaminase)", "code": "SERUMADA", "category": "Enzyme", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "<25", "turnaround_hours": 24},
    {"name": "ACE (Angiotensin Converting Enzyme)", "code": "ACE", "category": "Enzyme", "specialty": "Biochemistry",
     "unit": "U/L", "normal_range": "8–52 (adult)", "turnaround_hours": 48},
    {"name": "Galactomannan (Serum)", "code": "GALMAN", "category": "Fungal Marker", "specialty": "Microbiology",
     "unit": "OD index", "normal_range": "<0.5 (negative)", "turnaround_hours": 24},
    {"name": "Beta-D-Glucan (Fungal Screen)", "code": "BDG", "category": "Fungal Marker", "specialty": "Microbiology",
     "unit": "pg/mL", "normal_range": "<60 (negative)", "turnaround_hours": 24},
    {"name": "Plasma Free Metanephrines", "code": "PMET", "category": "Neuroendocrine", "specialty": "Endocrinology",
     "unit": "nmol/L", "normal_range": "Metanephrine <0.5; Normetanephrine <0.9", "turnaround_hours": 48},
    {"name": "Urine Catecholamines (24-hr)", "code": "UCATECOL", "category": "Neuroendocrine", "specialty": "Endocrinology",
     "unit": "µg/24hr", "normal_range": "Adrenaline <20; Noradrenaline <90; Dopamine <500", "turnaround_hours": 48},
    {"name": "Serum Protein Electrophoresis (SPEP)", "code": "SPEP", "category": "Protein", "specialty": "Haematology",
     "unit": "g/dL fraction", "normal_range": "Albumin 3.5–5.0; Alpha1 0.1–0.3; Alpha2 0.6–1.0; Beta 0.7–1.2; Gamma 0.7–1.6", "turnaround_hours": 48},
    {"name": "Serum Free Light Chains (Kappa/Lambda)", "code": "SFLC", "category": "Protein", "specialty": "Haematology",
     "unit": "mg/L", "normal_range": "Kappa 3.3–19.4; Lambda 5.7–26.3; K:L ratio 0.26–1.65", "turnaround_hours": 48},
    {"name": "Urine Bence Jones Protein", "code": "BJP", "category": "Protein", "specialty": "Haematology",
     "unit": "qualitative", "normal_range": "Absent", "turnaround_hours": 24},
]
